/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import ChapterReview from './ChapterReview';
import {routeCompletion,routeTactics,reserveRestGuidance} from './player-guidance';
import StoryItemSummary from './StoryItemSummary';
import SceneAction from './SceneAction';
import {encounterLabel} from './encounter-labels';
import PanelBody from './PanelBody';
import {coreDescription} from './core-description';
import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Button} from '../components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '../components/ui/dialog';
import {sprite} from './art';
import {PATHS,CONSUMABLES,relicDescription} from './data';
import {CORES,CINEMATICS,SUPPLIES,EXPEDITIONS,defaultGarden,coreEligible} from './expedition-data';
import {EQUIPMENT} from './expedition';
const Btn=({className='',...p})=><Button className={'fr-btn '+className} {...p}/>;
export function AtlasSprite({art,kind='icons',index=0,size=58}){const ref=useRef(null);useEffect(()=>{const c=ref.current;if(!c||!art)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.imageSmoothingEnabled=false;const img=kind==='hanli'?art.hanliPortrait:art[kind]?.[index];if(img)sprite(ctx,img,size*.7,size,size);},[art,kind,index,size]);return <canvas className="exp-sprite" ref={ref} width={size*1.4} height={size} aria-hidden="true"/>;}
export function RouteStrip({b}){return <nav className="route-strip" aria-label="本章路线">{b.routes[b.chapter].map((n,i)=>{const e=n.choices[n.selected??0];return <div key={n.id} className={'route-step '+(i===b.wave?'current ':'')+(b.receipts.includes(n.id)?'cleared':'')}><span>{b.receipts.includes(n.id)?'✓':String(i+1).padStart(2,'0')}</span><div><strong>{n.selected===null?'岔路待择':encounterLabel(e,b.chapter).split(' · ')[0]}</strong><small>{n.selected===null?'二选一':e.risk?'险路 · 数量 +18%':e.special?'固定剧情节点':'稳行'}</small></div>{i<b.routes[b.chapter].length-1&&<i>›</i>}</div>;})}</nav>;}
export function Cinematic({b,art,gate,advanceRef}){useLayoutEffect(()=>{advanceRef.current?.focus({preventScroll:true});},[advanceRef,b.cinematic?.id,b.cinematic?.panel]);const s=CINEMATICS.find(s=>s.id===b.cinematic?.id);if(!s)return null;const panel=s.panels[b.cinematic.panel];return <><PanelBody><div className="cinematic-panel"><div className="portrait-well">{panel[1]>=-1&&<AtlasSprite art={art} kind={panel[1]===-1?'hanli':'portraits'} index={panel[1]} size={240}/>}<small>同人形象 · 纪事改编</small></div><div><span className="eyebrow">{s.name} · {b.cinematic.panel+1} / {s.panels.length}</span><h3>{panel[0]}</h3><p>{panel[2]}</p>{panel[3]&&<p className="cinematic-stage">△ {panel[3]}</p>}<span className="cinematic-dots">{s.panels.map((_,i)=><i key={i} className={i===b.cinematic.panel?'active':''}/>)}</span></div></div><StoryItemSummary b={b}/><details className="cinematic-note"><summary><span className="expand-mark" aria-hidden="true">▸</span> 改编说明与器物状态 <small>点击展开</small></summary><p>{s.note}</p></details></PanelBody><div className="dialog-actions panel-action-dock"><SceneAction gate={gate} onAction={()=>b.advanceCinematic(true)}>跳过过场</SceneAction><SceneAction gate={gate} buttonRef={advanceRef} className="primary-start" onAction={()=>b.advanceCinematic()}>{b.cinematic.panel===s.panels.length-1?'继续历练':'下一幕'} →</SceneAction></div></>;}
export function StoryReplay({art,save,gate}){const [story,setStory]=useState(null),[panel,setPanel]=useState(0),advanceRef=useRef(null);useLayoutEffect(()=>{if(story)advanceRef.current?.focus({preventScroll:true});},[story,panel]);const s=CINEMATICS.find(s=>s.id===story),data=s?.panels[panel];const reached=id=>save?.wins>0||(save?.checkpoint?.expedition?.cinematicHistory||save?.checkpoint?.expedition?.cinematicSeen||[]).includes(id)||({bamboo:0,ruins:0,ghostFog:1,yuanyao:2,treasure:3,innerHall:4,cauldron:5}[id]!==undefined&&(save?.completed||[]).includes({bamboo:0,ruins:0,ghostFog:1,yuanyao:2,treasure:3,innerHall:4,cauldron:5}[id]));const button=s=><Btn key={s.id} variant="outline" onClick={()=>{gate.invalidate();setStory(s.id);setPanel(0);}}>重温 · {s.name}</Btn>;return <><div className="story-replays">{CINEMATICS.filter(s=>reached(s.id)).map(button)}</div><details className="story-spoilers"><summary>▸ 尚未历经的纪事 · 含结局剧透，展开后选择重温</summary><div className="story-replays">{CINEMATICS.filter(s=>!reached(s.id)).map(button)}</div></details><p className="muted">重温仅阅读；同人形象 · 纪事改编，不取得器物、不改写剧情进度。</p><Dialog open={!!s} onOpenChange={v=>{if(!v)setStory(null);}}><DialogContent initialFocus={advanceRef} className="game-dialog story-replay-dialog"><DialogTitle>{s?.name}</DialogTitle><DialogDescription>纪事重温 · 同人形象 · 纪事改编</DialogDescription><PanelBody>{data&&<div className="cinematic-panel"><div className="portrait-well">{data[1]>=-1&&<AtlasSprite art={art} kind={data[1]===-1?'hanli':'portraits'} index={Math.max(0,data[1])} size={220}/>}<small>同人形象 · 纪事改编</small></div><div><h3>{data[0]}</h3><p>{data[2]}</p>{data[3]&&<p className="cinematic-stage">△ {data[3]}</p>}</div></div>}{s&&<details className="cinematic-note"><summary><span className="expand-mark" aria-hidden="true">▸</span> 改编说明与器物状态 <small>点击展开</small></summary><p>{s.note}</p></details>}</PanelBody><div className="panel-action-dock"><Btn variant="outline" onClick={()=>setStory(null)}>关闭重温</Btn><SceneAction gate={gate} buttonRef={advanceRef} onAction={()=>panel===s.panels.length-1?setStory(null):setPanel(panel+1)}>{panel===(s?.panels.length||0)-1?'结束重温':'下一幕'}</SceneAction></div></DialogContent></Dialog></>;}
export function Garden({save,art,onChange,onReset}){const g=save.garden||defaultGarden(),research=SUPPLIES.find(s=>s.id===g.research)||SUPPLIES[1];return <section className="garden-panel"><div className="garden-heading"><div><span className="eyebrow">掌天瓶 · 药性研究</span><h3>洞府药园</h3><p>研究替换出发补给。每局只选一套，3 点补给、最多两种物资。</p></div><div><span className="garden-points">{g.points}<small>可用研究点</small></span><Btn className="garden-reset" variant="outline" disabled={g.unlocked.length<=1} onClick={onReset}>重置药园研究</Btn></div></div><div className="garden-plots">{[0,1,2].map(i=><div key={i}><AtlasSprite art={art} kind="props" index={g.points>i?5:g.points===i?4:3} size={82}/><span>{g.points>i?'药性已成':'待续培育'}</span></div>)}<AtlasSprite art={art} kind="props" index={6} size={70}/></div><p className="muted">主篇与定种历练通过战斗章节各得 1 点，终章再加 1 点；完整一局共 6 点，正式结算时保留。每 3 点研究一套；不按现实时间挂机产出。</p><div className="supply-grid">{SUPPLIES.map(s=>{const unlocked=g.unlocked.includes(s.id);return <button key={s.id} className={'supply-card '+(g.selected===s.id?'selected':'')} onClick={()=>onChange({...g,[unlocked?'selected':'research']:s.id})}><span>{unlocked?(g.selected===s.id?'当前补给':'可选补给'):g.research===s.id?'研究目标':'尚未研究'}</span><h4>{s.name}</h4><p>{s.desc}</p><small>{unlocked?'选中后下次出发生效':'需要 3 研究点'}</small></button>;})}</div>{!g.unlocked.includes(research.id)&&<div className="garden-research"><p>正在研究：<b>{research.name}</b></p><Btn variant="outline" disabled={g.points<3} onClick={()=>onChange({...g,points:g.points-3,unlocked:[...g.unlocked,research.id]})}>完成研究 · 3 点</Btn></div>}<small className="muted">新版洞府修持提供流派战术；旧局仍继承其原有药包。放弃未结算历练会放弃该局待领取的研究点。</small></section>;}
export function SupplyChooser({save,onChange}){const g=save.garden||defaultGarden();return <div className="supply-chooser"><h3>药园出发补给</h3><div className="mode-row">{SUPPLIES.filter(s=>g.unlocked.includes(s.id)).map(s=><Btn key={s.id} variant="outline" className={s.id===g.selected?'selected':''} onClick={()=>onChange({...g,selected:s.id})}>{s.name}</Btn>)}</div><p className="muted">{SUPPLIES.find(s=>s.id===g.selected)?.desc} · 在洞府药园研究更多替代方案</p><p className="muted">主篇 22 个节点、9 次选路；建议预留约 30 分钟，进攻构筑可更快，偏防守构筑可能更长；阅读和整备期间暂停。</p></div>;}
export function ExpeditionPanel({b,save,art,onBuy,onReplace,onSell,replace,setReplace,onContinue}){
 const [pendingCore,setPendingCore]=useState(null);const eventRef=useRef(null),coreRef=useRef(null),routeRef=useRef(null);const rest=b.rest,event=b.eventText(),refresh=b.shopReadiness();if(!rest)return null;const next=!rest.last&&!rest.preparation?b.routes[b.chapter][b.wave+1]:null;
 const readiness=b.restReadiness(),rerollPurchase=b.rerollPurchaseReadiness(),supply=b.supplyQuote(),shieldSupply=b.supplyQuote('shield');
 const tasks=rest.ending?[]:[{label:'机缘',done:readiness.event,target:'event'},{label:'核心',done:rest.coreDone,target:'core'},{label:'路线',done:rest.routeDone,target:'route'}],missing=tasks.filter(t=>!t.done);
 function locate(t){const ref={event:eventRef,core:coreRef,route:routeRef}[t.target];ref.current?.scrollIntoView({block:'start',behavior:'smooth'});ref.current?.focus({preventScroll:true});}
 function equip(id,index=-1){const result=b.equipCore(id,index);if(result==='coreSlots'||result==='replace')setPendingCore(id);else if(result===true)setPendingCore(null);}
 return <div className="expedition-rest"><div className="rest-scroll"><RouteStrip b={b}/><ChapterReview b={b} save={save}/><div className="selection-notice"><strong>{rest.ending?'此行已毕 · 整理所得':'出发前可以反复改选'}</strong><p>{rest.ending?'最后节点的基础灵石已全部收拢；处理尚未完成的悟道后，进入结局与成绩结算。':'机缘与核心先暂选，确认出发时才扣资源、发奖励；下一条路线可直接换选。暂选会自动保存。'}</p>{rest.legacyClaimed&&<small>这份旧记录中已领取的机缘／核心保留原结果，从下一次整备开始支持完整暂选；未出发路线仍可更换。</small>}</div><div className="rest-checklist" aria-label="整备进度"><b>{rest.ending?'① 处理悟道 → ② 收拢所得':'① 完成选择 → ② 处理悟道 → ③ 确认出发'}</b><div>{tasks.map(t=><button key={t.label} onClick={()=>locate(t)}>{t.done?'✓':'待选'} {t.label}{!t.done?' · 前往选择':''}</button>)}</div><small>{rest.ending?'节点已完成 · 可以继续':(missing.length?'还需选择：'+missing.map(t=>t.label).join('、'):'选择齐全 · 可以继续')+(rest.shop?' · 商店购物可跳过':'')}</small></div><div className="node-reward"><div><span>通关经验保底</span><b>{rest.xp}</b><small>包含途中基础经验</small></div><div><span>独立额外经验</span><b>+{Number(((rest.growthReward?.performance||0)+rest.bonus).toFixed(1))}</b><small>表现 +{Number((rest.growthReward?.performance||0).toFixed(1))} · 条款 +{rest.bonus}</small></div><div><span>持有灵石</span><b>{b.gold}</b><small>研究待结算 {b.research} 点</small></div></div>
 {readiness.eventReason&&<output className="rest-invalid">暂选机缘已失效：{readiness.eventReason}。请重新选择机缘。</output>}
 {rest.coreSelection?.replaceId&&<p className="core-replacement-notice">确认出发时将换下「{EQUIPMENT.find(c=>c.id===rest.coreSelection.replaceId)?.name}」，装配「{EQUIPMENT.find(c=>c.id===rest.coreSelection.id)?.name}」。出发前可改选。</p>}
 {reserveRestGuidance(b)&&<p className="rest-reserve">{reserveRestGuidance(b)}</p>}<StoryItemSummary b={b}/>
 {event&&<section ref={eventRef} tabIndex={-1} className="rest-section"><span className="eyebrow">{rest.eventApplied||rest.legacyClaimed&&rest.eventDone?'此前机缘结果 · 已生效':rest.eventDone?'机缘已暂选 · 尚未提交':'途中机缘 · 等待选择'}</span><h3>{event.name}</h3><p>{rest.eventApplied||rest.legacyClaimed&&rest.eventDone?'此前选择已执行，奖励与代价已计入本局；本页不会重复发放。':event.desc}</p><div className="interaction-choices">{event.choices.map((c,i)=>{const state=b.interactionReadiness(i);return <button key={i} disabled={(rest.selectionMode==='draft'?rest.eventApplied:rest.eventDone)||state.blocked} className={(rest.event.choice===i?'selected ':'')+(state.noBenefit?'no-benefit':'')} onClick={()=>b.chooseInteraction(i)}><span>{String(i+1).padStart(2,'0')}</span>{c}{state.noBenefit?' · 当前已满，可改选其他收益':''}{state.blocked&&<small className="choice-unavailable">{state.reason}</small>}{rest.event.choice===i?(rest.eventApplied||rest.legacyClaimed?' · 此前已执行':state.blocked?' · 暂选已失效':' · 已暂选，出发时执行'):''}</button>;})}</div></section>}
 {rest.coreOffers.length>0&&<section ref={coreRef} tabIndex={-1} className="rest-section"><span className="eyebrow">战术核心 · 六格携行位中最多装两件，同方向互斥</span><h3>{rest.coreApplied?'此前核心已领取':rest.coreDone?'核心已暂选 · 出发前可更换':'选择改变打法的核心'}</h3><div className="core-grid">{rest.coreOffers.map(id=>{const c=CORES.find(c=>c.id===id),old=b.relics.map(id=>CORES.find(c=>c.id===id)).find(x=>x?.path===c.path&&x.id!==id);return <button className={'core-card '+((rest.coreSelection?.id===id||rest.coreApplied&&b.relics.includes(id))?'selected':'')} key={id} disabled={(rest.selectionMode==='draft'?rest.coreApplied:rest.coreDone)||!coreEligible(c,b)} onClick={()=>equip(id)}><AtlasSprite art={art} index={c.icon}/><span style={{color:PATHS[c.path].color}}>{PATHS[c.path].name}战术</span><h4>{c.name}</h4><p>{coreDescription(c,b)}</p>{old&&<strong className="core-swap-label">将换下「{old.name}」</strong>}<small>条件：{c.requirement}</small></button>;})}</div>{pendingCore&&<div className="replace-core"><p>选择要换下的携行物；已有两件核心时须换下一件核心。</p>{b.relics.map((id,i)=><Btn key={id} variant="outline" disabled={b.relics.filter(id=>CORES.some(c=>c.id===id)).length>=2&&!CORES.some(c=>c.id===id)} onClick={()=>equip(pendingCore,i)}>替换 {EQUIPMENT.find(c=>c.id===id)?.name}</Btn>)}<Btn variant="ghost" onClick={()=>setPendingCore(null)}>取消替换</Btn></div>}{!rest.coreApplied&&<Btn className={rest.coreSelection?.id===null?'selected':''} variant="outline" onClick={()=>{b.skipCore();setPendingCore(null);}}>暂不装配 · 出发时获得一次悟道重选</Btn>}</section>}
 {rerollPurchase.visible&&(rerollPurchase.count>=2?<p className="reroll-complete">悟道重选 · 本局 2 / 2 已购满 · 库存 {b.rerolls} 次</p>:<section className="rest-section reroll-purchase"><h3>悟道重选 · 有限购置</h3><p>{rest.shop?'本处有行囊货架；重选为独立购置。':'本处无行囊货架，仍可单独购置重选。'}只增加重选库存，在后续悟道时使用；当前候选不变。全局最多 2 次，无尽换轮也不重置。现有重选 {b.rerolls} 次。</p><Btn variant="outline" disabled={!rerollPurchase.ready} onClick={()=>b.buyReroll(rerollPurchase.price)}>{rerollPurchase.count>=2?'本局 2 / 2 已购满':'购买重选 +1 · '+rerollPurchase.price+' 灵石'}</Btn>{rerollPurchase.reason&&<small>{rerollPurchase.reason}</small>}</section>)}
 {supply.visible&&<section className="reroll-purchase late-supply"><h3>有限补养 · 本局 {supply.count} / 3</h3><p>每处整备最多购买一次，整局最多三次，无尽换轮也不重置。立即扣款和恢复；不是出发条件，不补雷源。</p><p className="muted">暂选恢复可能覆盖本次增量，付款可能让原付费暂选失效，届时可重新改选。{rest.last?'本章结束后还会恢复30%生命，请核对下方预计保留量。':''}</p>{supply.count>=3?<p>本局已购满，保留现有资源继续前行。</p>:supply.reason==='node-used'?<p>本处补养已购买；下一处合格整备可再次考虑。</p>:<><div className="supply-offers supply-projections">{[supply,shieldSupply].map(q=><article className="supply-offer" key={q.type}><strong>{q.type==='hp'?'养息':'固盾'}</strong>{q.ready&&q.retainedGain===0&&<strong className="zero-departure-gain">出发后增量 0 · 后续回复将覆盖本次恢复</strong>}<p className="supply-preview">{q.retainedGain===null?q.projectionNote||(!q.ready?'当前不可购买，未扣款。':'暂不能计算出发时增量。'):'当前暂选与换章回复后，预计仍多 '+Number(q.retainedGain.toFixed(1))+(q.type==='hp'?' 生命':' 护盾')+'。'+q.projectionNote}</p>{q.draftImpact&&<p className="supply-impact">{q.draftImpact}</p>}<Btn variant="outline" disabled={!q.ready} onClick={()=>b.buySupply(q.type,q)}>{q.type==='hp'?'养息 · 立即回 ':'固盾 · 立即补 '}{Number(q.gain.toFixed(1))}{q.type==='hp'?' 生命':' 护盾'} · 80 灵石</Btn></article>)}</div><small>养息最多恢复生命上限的25%；固盾最多补12，至常驻上限+12。满状态不收费。</small>{b.gold<80&&<p>还缺 {80-b.gold} 灵石；可以直接跳过补养。</p>}</>}</section>}
 {rest.shop&&<section className="rest-section"><div className="shop-top"><h3>行囊整备</h3><Btn variant="outline" disabled={!refresh.ready} title={refresh.ready?'更换当前货架':'还缺 '+refresh.missing+' 灵石'} onClick={()=>b.refreshShop()}>更换货架 · {refresh.price} 灵石</Btn>{!refresh.ready&&<small className="refresh-missing">还缺 {refresh.missing} 灵石</small>}</div><div className="shop-grid">{b.shop.map((r,i)=><article className="shop-card" key={r.id}><small>{r.kind==='relic'?'携行配置':'药囊物资'}</small><h3>{r.name}</h3><p>{r.kind==='relic'?relicDescription(r):r.desc}</p><Btn disabled={b.gold<r.price||b.purchased.includes(r.id)} onClick={()=>onBuy(i)}>{b.purchased.includes(r.id)?'已购':r.price+' 灵石'}</Btn>{r.kind==='relic'&&<Btn variant="ghost" onClick={()=>b.toggleLock(i)}>{b.locked.some(v=>v.id===r.id)?'取消保留':'保留货架'}</Btn>}</article>)}</div>{replace!==null&&<div className="replace-core"><p>选择要替换的位置；替换不返还灵石，换下核心需再次确认：</p>{(b.shop[replace]?.kind==='relic'?b.relics.map(id=>({name:(CORES.some(c=>c.id===id)?'【核心】':'')+EQUIPMENT.find(r=>r.id===id)?.name})):b.consumables.map(s=>({name:CONSUMABLES.find(c=>c.id===s.id)?.name}))).map((r,i)=><Btn key={i} onClick={()=>onReplace(replace,i)}>替换 {r.name}</Btn>)}<Btn variant="ghost" onClick={()=>setReplace(null)}>取消替换</Btn></div>}</section>}
 {b.relics.length>0&&<div className="equipped-row"><strong>携行 {b.relics.length} / 6</strong>{b.relics.map((id,i)=><button key={id} disabled={!rest.shop} title={rest.shop?'出售可返还实际购价的 40%，免费核心无返还':'在商店节点可以卸下配置'} onClick={()=>onSell(i)}>{CORES.some(c=>c.id===id)?'【核心】':''}{EQUIPMENT.find(r=>r.id===id)?.name}{rest.shop?' · 卸下':''}</button>)}</div>}
 {next&&<section ref={routeRef} tabIndex={-1} className="rest-section"><span className="eyebrow">下一节点</span><h3>{next.choices.length>1?'选择前路':'前路已明'}</h3><div className="route-choices">{next.choices.map((e,i)=><button key={e.id||e.kind} disabled={next.choices.length===1} className={'route-card '+(next.selected===i?'selected':'')} onClick={()=>b.chooseRoute(i)}><AtlasSprite art={art} index={12+(e.family??0)} size={48}/><small>{e.risk?'冒险路线 · 刷新数量 +18%':'稳行路线'}</small><h4>{encounterLabel(e,b.chapter)}</h4><p>{routeTactics(e,b)}</p><span>基础经验 {next.xp}</span><small>{routeCompletion(e)}</small><small>{e.risk?'额外灵石；'+b.contractText(e)+'，经验再加 8%':'所有起手均可通过；无专属技能门槛'}</small></button>)}</div></section>}
 </div><div className="rest-action-dock">{missing.length>0&&<output className="rest-missing">出发前还需：{missing.map(t=><button key={t.label} onClick={()=>locate(t)}>选择{t.label} ↑</button>)}</output>}<div className="rest-footer"><p>{rest.preparation?'宝光阁前的最后整备；进入后先敛息取宝，再辨破幻境。':rest.last&&b.chapter===5?'此行结束后结算研究点与修炼心得。':rest.last?'本章结束，下一章恢复 30% 生命并补满雷源。':b.chapter===5&&b.wave===2?'接下来面对玄骨，保留当前生命与雷源。':'机缘与核心在确认出发时一次结算，暂选不会重复领取奖励。'}</p><Btn className="primary-start" disabled={!readiness.ready} onClick={()=>onContinue?onContinue():b.continueRest()}>{b.queuedChoices?'处理 '+b.queuedChoices+' 次悟道':rest.last&&b.chapter===5?'收拢所得 · 结算':rest.last?'确认前往 '+EXPEDITIONS[(b.chapter+1)%6].name:'确认整备并出发'} →</Btn></div></div></div>;
}

export function BossIdentity({b,art}){const boss=b.boss;if(!boss)return null;const kind=boss.bossType||boss.type,icons={serpent:'蛇',ghost:'鬼',puppet:'狼',swarm:'蚁'},label=kind==='swarm'?'虫潮首领战':'首领';return <span className={'boss-identity boss-identity-'+kind}><span className="boss-emblem">{kind==='xuangu'?<AtlasSprite art={art} kind="portraits" index={2} size={38}/>:icons[kind]||'首'}</span><span><small>{label}</small><b>{boss.name}</b></span></span>;}
