/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import {cultivationMods} from './cultivation.js';
import {FOCUS_VERSION,gnawStatus} from './targeting.js';
import {BALANCE_VERSION,BALANCE4,phase3Balance,phase4Options,puppetReady,sigilCooldown,afterThunderWindow,starterExtrasFor,reserveRestBase,sigilWarn,sigilGrowth,dashCooldown} from './balance.js';
export const RULES_VERSION=2;
export const STARTERS=[
 {name:'御剑',tag:'聚锋破敌',role:'连续集火 · 强化剑击',initial:'飞剑伤害 +10%',action:'同一目标连续命中 4 次剑击，相邻间隔不超过 2 秒，第 4 击强化并追加穿透。',limit:'四击按同一目标累计；小怪提前倒下不会把进度转给下一个目标，优先对厚血目标聚锋。',tips:['飞剑自动出击；按住鼠标左键指定集火点。','优先盯住精英或远处施法者，连续命中积累强化剑击。','前期可选锐意、疾剑、贯穿；需要覆盖时选远驭。'],traits:['锐意','疾剑','贯穿']},
 {name:'雷法',tag:'蓄雷破局',role:'全场解围 · 余雷追击',initial:'初始灵力 50 · 雷源 +20',action:'神雷后 5 秒内飞剑伤害额外 +25%；保留回灵优势。',limit:'回灵不能补充雷源，仍需安排每章的施雷次数。',tips:['本局灵力从 50 起步，第一次神雷更早可用。','敌人数多或弹幕危险时放雷，再靠近飞剑有效射程利用 5 秒余雷追击；无需把敌人聚到一个小圈内。','关注节雷、雷储和余电；回灵药只补灵力。'],traits:['节雷','雷储','余电']},
 {name:'傀儡',tag:'架机交射',role:'移动避招 · 停稳架设',initial:'初始 2 具协战傀儡',action:'停稳 0.6 秒后进入架设，傀儡攻速 +25%；移动即解除。',limit:'站稳输出需要安全空隙，别在预警区域久留。',tips:['两具傀儡会自动跟随并射击，不需要额外召唤键。','移动避招后松开移动片刻完成架设，再按局势换位。','弩机增加数量；精工、连弩与穿弩强化已有傀儡。'],traits:['弩机','连弩','穿弩']},
 {name:'御虫',tag:'金虫蚀甲',role:'虫群缠敌 · 集火收割',initial:'初始 4 只金色噬金虫',action:'有效啃噬逐步附加易伤，最高 12%，停止啃噬 3 秒后消退。',limit:'需要持续缠住目标；加伤害的强化不会直接增加虫数。',tips:['金色噬金虫自动追击；按住鼠标可指引优先目标。','让虫群缠住厚血敌人，再集中飞剑收割。','育虫直接增加数量；虫潮按击杀加虫，最多额外六只。'],traits:['育虫','侵甲','连噬']},
 {name:'符阵',tag:'留火引敌',role:'闪避留符 · 踏入引爆',initial:'飞剑灼烧 · 闪避可留符',action:'闪避起点留下符火，0.8 秒后引爆；独立冷却 6 秒。',limit:'引爆范围有限，要把敌人引入落点。',tips:['闪避可在出发点留下延时符火，留意冷却提示。','让追来的敌人走进符火，再绕向空旷区域。','遁后留符可强化起手符火；火势、缚行便于控场。'],traits:['遁后留符','火势','缚行']},
 {name:'护身',tag:'守元反击',role:'闪避化解 · 反击回盾',initial:'初始 25 护盾 · 基础回盾',action:'脱离受击 4 秒后每秒回盾 2；闪避挡下攻击触发反击并最多回盾 6（补到常规上限 +12，已有额外护盾保留），间隔 4 秒。',limit:'基础闪避冷却 3 秒；反击需在闪避开始约 0.24 秒内挡住攻击，反击本身另有 4 秒间隔。',tips:['保持距离恢复护盾；护盾先于生命承受伤害。','在攻击将命中时闪避，可触发一次反击与回盾。','固元、息调与轻身提升容错，稳守适合闪避后的交锋。'],traits:['固元','息调','稳守']},
];
export function starterStatus(b){if(b.rulesVersion<2)return '旧局起手 · 原规则';switch(b.path){case 0:{const e=b.enemies.filter(e=>e.hp>0&&e.focusHits>0&&e.focusUntil>b.time).sort((a,z)=>z.focusUntil-a.focusUntil)[0];const form=['分击','环护','定向'][b.formation||0];return e?form+' · 聚锋 '+e.focusHits+'/4 · '+Math.max(.1,e.focusUntil-b.time).toFixed(1)+' 秒 · '+e.name:form+' · 四击聚锋 · 等待集火';}case 1:{const window=afterThunderWindow(b);return b.time-b.thunderTime<window?'余雷 '+(window-b.time+b.thunderTime).toFixed(1)+' 秒':'蓄雷待机';}case 2:if(b.hasCore?.('K06'))return b.player.moving?'移动策应 · 弩速 +35%':'移动策应 · 待转移';return puppetReady(b)?(b.player.moving?'架设衔接 '+Math.max(0,b.setupUntil-b.time).toFixed(1)+'s · 弩速 +25%':'已架设 · 弩速 +25%'):'架设 '+Math.min(.6,b.stillTime||0).toFixed(1)+' / 0.6 秒';case 3:return gnawStatus(b);case 4:{const t=Math.max(0,sigilCooldown(b)-(b.time-b.lastSigil));return t>0?'留符 '+t.toFixed(1)+' 秒':'留符已就绪';}case 5:if(phase3Balance(b)){const left=Math.min(b.player.invuln,.24+(b.stats.iframes||0)-b.time+b.player.lastDash);return left>0?b.lastCounter>=b.player.lastDash?'本次闪避已反击':'待化解 '+left.toFixed(2)+' 秒':b.player.dashCD>0?'须挡下来袭 · 闪避 '+b.player.dashCD.toFixed(1)+' 秒':'闪避反击已就绪';}return b.time-b.lastCounter<4?'反击 '+(4-b.time+b.lastCounter).toFixed(1)+' 秒':b.player.dashCD>0?'反击可触发 · 闪避 '+b.player.dashCD.toFixed(1)+' 秒':'反击与闪避已就绪';}}

export function starterDetails(path,options={}){
 const modern=(options.rulesVersion??3)===3&&(options.balanceVersion??BALANCE_VERSION)>=2,m=cultivationMods(options,path),d={...STARTERS[path],tips:[...STARTERS[path].tips]};
 // Balance-4 numbers are read through the same functions the engine uses, from a minimal option-only context, so the departure page shows the actual values.
 const phase4=phase4Options(options),ctx={rulesVersion:options.rulesVersion??3,options:{...options,balanceVersion:options.balanceVersion??BALANCE_VERSION},path,stats:m,level:1,difficulty:{reserve:0}},extras=starterExtrasFor({...options,rulesVersion:options.rulesVersion??3},path),thunderWindow=afterThunderWindow(ctx);
 if(path===0){d.tips[0]=(options.rulesVersion??3)===3&&(options.focusVersion??FOCUS_VERSION)>=2?'按住左键后，新出击飞剑集中射程内最靠近准心的目标；松开恢复剑式分配，穿透仍可命中其他敌人。':'旧局左键调整选敌优先级，分组追击仍分给前三个目标；切定向穿刺可集中首目标。';d.initial='飞剑伤害 +'+Math.round(10+(m.damage||0)*100)+'%'+(extras.pierce?' · 飞剑穿透 +'+extras.pierce:'');d.action='同一目标连续命中 4 次剑击，相邻间隔不超过 '+(2+(m.metaFocusWindow||0))+' 秒，第 4 击强化并追加穿透。';}
 if(path===1){const mana=50+(m.metaStartMana||0);d.initial='回灵 +20% · 初始灵力 '+mana+' · 雷源 +'+((extras.reserve||0)+(m.reserve||0));d.tips[0]='本局起手配置为 '+mana+' 灵力，第一次神雷更早可用。';d.action='神雷后 '+thunderWindow+' 秒内飞剑伤害额外 +'+Math.round(25+(m.afterThunder||0)*100)+'%；保留回灵优势。';if(phase4)d.tips[1]='敌人数多或弹幕危险时放雷，再靠近飞剑有效射程利用 '+thunderWindow+' 秒余雷追击；无需把敌人聚到一个小圈内。';}
 if(path===3){d.initial='初始 '+(4+(m.insects||0))+' 只金色噬金虫';d.action='有效啃噬逐步附加易伤，最高 12%，停止啃噬 '+(3+(m.metaGnawDuration||0))+' 秒后消退。';}
 if(path===4){const cooldown=Number(sigilCooldown(ctx).toFixed(1));d.action=modern?'闪避起点布符 0.35 秒后，敌人踏入即爆；最多留存 '+Number(sigilWarn(ctx).toFixed(1))+' 秒，独立冷却 '+cooldown+' 秒。':'闪避起点留下符火，0.8 秒后引爆；独立冷却 '+cooldown+' 秒。';if(modern){d.limit='墙边落点向场内收拢；合符同燃仍按双符配对引爆。';d.tips[0]='闪避在起点布符，短暂布好后等追兵踏入；遁后留符将布符时间缩短为 0.2 秒。';}if(phase4){d.initial='飞剑灼烧 · 闪避可留符'+(extras.slow?' · 飞剑命中减速 +'+Math.round(extras.slow*100)+'%':'');d.limit='闪避基础冷却 '+Number(dashCooldown({...ctx,stats:{}}).toFixed(1))+' 秒（平衡 3 及更早为 3 秒）；'+d.limit;}}
 if(path===5){d.limit='基础闪避冷却 '+(modern?2:3)+' 秒；反击需在闪避开始约 '+Number((.24+(m.iframes||0)).toFixed(2))+' 秒内挡住攻击，另有 4 秒间隔。';d.tips[1]='基础闪避冷却 '+(modern?2:3)+' 秒；基础反击窗口（含洞府） '+Number((.24+(m.iframes||0)).toFixed(2))+' 秒，反击另有 4 秒间隔。';d.initial='生命 '+(100+(m.hp||0))+' · 初始 '+(25+(m.shield||0))+' 护盾 · 护甲 '+(m.armor||0)+' · 每秒回盾 '+(2+(m.shieldRegen||0));d.action='脱离受击 4 秒后每秒回盾 '+(2+(m.shieldRegen||0))+'；闪避挡下攻击触发反击并最多回盾 6（补到常规上限 +12，已有额外护盾保留），间隔 4 秒。';}
 if(path===2&&(options.balanceVersion??BALANCE_VERSION)>=3)d.action='停稳 0.6 秒后进入架设，傀儡攻速 +25%；移动后保留 0.3 秒，移动策应仍按其自身规则。';
 if(path===1&&modern){d.action+=' 前五章的非章末战斗节点休整最多补回 '+(reserveRestBase(ctx)+(m.metaReserveRest||0))+' 雷源；宝光阁、幻境和终章不补。';d.limit='雷源仍有限；休整补给只结算一次，终章必须保留施雷次数。';}if((options.balanceVersion??BALANCE_VERSION)>=3){if(path===1)d.action+=' 雷法基础消耗 22 雷源，先减节雷、最低 8，再加核心消耗。';if(path===4){d.action+=phase4?' 每一剑都使符爆基础倍率 +'+Number((BALANCE4.sigilGrowthRate*100).toFixed(1))+'%（1 剑 '+Number(sigilGrowth({...ctx,level:1}).toFixed(2))+'、72 剑 '+Number(sigilGrowth({...ctx,level:72}).toFixed(2))+' 倍），最多计 72 剑；布符时锁定伤害。':' 超过 12 剑后，每多一剑符爆基础倍率 +8%，最多计 72 剑；布符时锁定伤害。';d.tips[0]='布符 '+Number(Math.max(.1,.35-(m.metaSigilArming||0)).toFixed(2))+' 秒；遁后留符 '+Number(Math.max(.1,.2-(m.metaSigilArming||0)).toFixed(2))+' 秒。敌人体积与符圈相交即可触发并命中。';}if(path===5){const counter=BALANCE4.guardCounter;d.action=phase4?'每次闪避成功挡下攻击最多反击一次，伤害为 '+Number((32*counter).toFixed(1))+'＋等级×'+Number((.9*counter).toFixed(2))+'，最多回盾 3（补至常规上限 +12，保留已有额外盾）。':'每次闪避成功挡下攻击最多反击一次，伤害为 16＋等级×0.45，最多回盾 3（补至常规上限 +12，保留已有额外盾）。';d.limit='闪避基础冷却 2 秒；需在开始约 '+Number((.24+(m.iframes||0)).toFixed(2))+' 秒内挡下攻击。';d.tips[1]='反击跟随每次成功闪避，同次多发攻击只触发一次，不另设 4 秒门槛。';}}if(path===4&&m.metaSigilArming)d.action=d.action.replace('布符 0.35 秒','布符 0.2 秒');
 if(path===3)d.initial+=' · 虫潮按击杀加虫';return d;
}
