/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';import assert from 'node:assert/strict';
import {LEGACY_META,initialSave} from '../gameplay/data.js';import {META_V2 as META,activeCultivation,needsCultivationUpgrade} from '../gameplay/cultivation.js';import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {planCultivationUpgrade,planMetaRefund} from '../gameplay/respec.js';import {normalizeSave,SaveVault,SAVE_KEY,BACKUP_KEY} from '../gameplay/save-store.js';
const all=META.map(m=>m.id),own=path=>META.filter(m=>m.path===path).map(m=>m.id),make=(path,ids=own(path),extra={})=>new Expedition({balanceVersion:2,metaRulesVersion:2,seed:'cultivation-tests',path,difficulty:1,meta:ids,...extra});
function arena(b){b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};return b;}
void test('all 36 cultivation nodes have independent names, descriptions and matching refundable costs',()=>{assert.equal(META.length,36);assert.equal(new Set(META.map(m=>m.name)).size,36);assert.equal(new Set(META.map(m=>m.desc)).size,36);assert.deepEqual(META.map(m=>[m.id,m.cost]),LEGACY_META.map(m=>[m.id,m.cost]));for(let p=0;p<6;p++)assert.equal(META.filter(m=>m.path===p&&m.capstone).length,1);});
void test('each purchased node contributes its actual modifier only to the selected starter',()=>{for(const m of META){const before=make(m.path,[]),after=make(m.path,[m.id]);for(const [k,v] of Object.entries(m.mods))assert.ok(Math.abs((after.stats[k]||0)-(before.stats[k]||0)-v)<1e-9,m.name+' '+k);const wrong=(m.path+1)%6;assert.deepEqual(make(wrong,[m.id]).stats,make(wrong,[]).stats,m.name+' leaked across branches');}});
void test('owning six trees does not stack generic HP, money, medicine or rerolls',()=>{for(let p=0;p<6;p++){const b=make(p,all),single=make(p);assert.deepEqual(b.stats,single.stats);assert.equal(b.gold,45);assert.equal(b.rerolls,2);assert.deepEqual(b.consumables,[{id:'heal',count:2},{id:'mana',count:1}]);assert.equal(b.player.maxHp,p===5?108:100);assert.equal(activeCultivation(b.options,p).length,6);}});
void test('sword cultivation extends focus, speeds empowered follow-up and recalls only on cooldown',()=>{const b=arena(make(0)),e=b.spawn(0,{x:850,y:520,hp:1e6,spawn:0,speed:0});for(let i=0;i<3;i++)b.hit(e,10,'sword',false);b.time=2.4;assert.equal(b.hit(e,10,'sword',false).empowered,true);assert.equal(b.player.buffs.metaSwordTempo,5.4);b.level=3;b.swords=[];b.syncSwords();b.rebuildHash();b.swords.forEach(s=>s.cool=0);b.updateSwords(.001);assert.equal(b.swords[0].pierce,0);assert.equal(b.swords[2].pierce,1);assert.ok(b.swords[0].cool<1.05);b.swords.forEach(s=>s.cool=1);b.changeFormation();assert.ok(b.swords.every(s=>s.cool===.25));b.swords[0].cool=1;b.time=3;b.changeFormation();assert.equal(b.swords[0].cool,1);b.time=10.4;b.changeFormation();assert.equal(b.swords[0].cool,.25);});
void test('thunder cultivation changes initial charge, real spending and defensive window without resetting on restore',()=>{const b=make(1);assert.equal(b.player.mana,65);assert.equal(b.player.maxReserve,150);arena(b);b.player.mana=100;const reserve=b.player.reserve;assert.equal(b.thunder(),true);assert.equal(b.player.reserve,reserve-23);assert.equal(b.player.mana,0);assert.ok(b.player.invuln>=1);const c=Expedition.restore(JSON.parse(JSON.stringify(b.serialize())));assert.equal(c.player.mana,0);assert.equal(c.player.reserve,reserve-23);});
void test('puppet cultivation moves the formation faster and every sixth normal shot carries suppression',()=>{const b=arena(make(2)),plain=arena(make(2,[]));for(const x of [b,plain])x.puppets=[{x:400,y:400,cool:99},{x:500,y:400,cool:99}];b.updateAllies(.1);plain.updateAllies(.1);assert.ok(b.puppets[0].x>plain.puppets[0].x);const e=b.spawn(0,{x:820,y:520,hp:1e6,spawn:0,speed:0});b.rebuildHash();b.puppets[0].cool=0;b.puppets[0].metaShots=5;b.updateAllies(.01);assert.equal(b.shots.length,1);assert.equal(b.shots[0].metaPin,true);b.updateAllies=()=>{};b.updateSwords=()=>{};const pin={...b.shots[0],x:e.x,y:e.y,vx:0,vy:0,hits:[]};b.shots=[pin];b.update(.01);assert.equal(e.stun,.5);const immunity=e.metaPinUntil;b.shots=[{...pin,ttl:1,hits:[]}];b.update(.01);assert.equal(e.metaPinUntil,immunity);assert.ok(e.stun<.5);});
void test('suppression does not stun bosses and crossbow core bonus volleys are not extra sixth shots',()=>{const b=arena(make(2)),e=b.spawn(0,{x:820,y:520,hp:1e6,boss:true,spawn:0,speed:0,timer:999});b.rebuildHash();b.relics=['K05'];b.stillTime=1;b.puppets=[{x:680,y:520,cool:0,metaShots:5,coreShots:1},{x:600,y:600,cool:99}];b.updateAllies(.01);assert.equal(b.shots.length,3);assert.equal(b.shots.filter(s=>s.metaPin).length,1);b.updateAllies=()=>{};b.updateSwords=()=>{};b.shots=[{...b.shots[0],x:e.x,y:e.y,vx:0,vy:0,hits:[]}];b.update(.01);assert.ok(e.stun<=0);});
void test('insect cultivation adds a bug, expands targeting and extends capped gnaw',()=>{const b=arena(make(3)),e=b.spawn(0,{x:850,y:520,hp:1e6,spawn:0});b.rebuildHash();const ranges=[],target=b.allyTarget.bind(b);b.allyTarget=(x,y,r,meta)=>{ranges.push(r);return target(x,y,r,meta);};b.updateAllies(.01);assert.equal(b.insects.length,5);assert.ok(ranges.includes(300));b.insects.forEach((bug,i)=>{bug.x=e.x+12;bug.y=e.y;bug.cool=i?99:0;});b.updateAllies(.01);assert.equal(e.gnawUntil,4);assert.ok(e.gnaw<=.12);b.relics=['K08'];b.targetCache={};b.enemies=[];const distant=b.spawn(0,{x:1090,y:520,hp:1000});b.rebuildHash();assert.equal(b.allyTarget(640,520,500,{kind:'insect',index:0}),distant);});
void test('only eligible insect finishing blows count toward the eighth-kill recovery',()=>{const b=arena(make(3));b.player.hp=50;for(let i=0;i<7;i++)b.hit(b.spawn(0,{hp:10}),1e6,'insect',false);assert.equal(b.player.hp,50);for(let i=0;i<8;i++)b.hit(b.spawn(0,{hp:10,noDrop:true}),1e6,'insect',false);assert.equal(b.player.metaInsectKills,7);b.hit(b.spawn(0,{hp:10}),1e6,'sword',false);assert.equal(b.player.hp,50);b.hit(b.spawn(0,{hp:10}),1e6,'insect',false);assert.equal(b.player.hp,53);});
void test('talisman cultivation changes real sigil radius and cooldown and never chains echo or twin fire lines',()=>{const b=arena(make(4));b.dash();const first=b.zones.find(z=>z.sigil);assert.ok(Math.abs(first.r-97.75)<1e-8);b.player.dashCD=0;b.time=5.39;b.dash();assert.equal(b.lastSigil,0);b.player.dashCD=0;b.time=5.4;b.dash();assert.equal(b.lastSigil,5.4);b.zones=[];b.onSigilDetonate(first);const echo=b.zones.find(z=>z.metaEcho);assert.equal(echo.damage,first.damage*.25);assert.equal(echo.warn,.4);b.onSigilDetonate(echo);assert.equal(b.zones.length,1);b.zones=[];b.onSigilDetonate({...first,twin:true});assert.equal(b.zones.length,0);});
void test('guard cultivation changes defenses and grants movement only after a successful dodge-counter',()=>{const b=arena(make(5));assert.equal(b.player.maxHp,108);assert.equal(b.player.maxShield,33);assert.equal(b.stats.armor,2);assert.equal(b.stats.shieldRegen,3);assert.equal(b.movementBonus(),0);b.player.invuln=0;b.dash();assert.equal(b.movementBonus(),0);b.hitPlayer(10);assert.equal(b.movementBonus(),.12);b.time+=1.51;assert.equal(b.movementBonus(),0);});
void test('missing cultivation rule markers restore the old money, medicine, HP and preparation unchanged',()=>{const old=make(0,all,{metaRulesVersion:1}),data=JSON.parse(JSON.stringify(old.serialize()));delete data.options.metaRulesVersion;const restored=Expedition.restore(data);assert.equal(restored.options.metaRulesVersion,1);assert.equal(restored.gold,60);assert.equal(restored.player.maxHp,112);assert.equal(restored.rerolls,8);assert.equal(restored.consumables[0].count,3);assert.equal(restored.stats.metaSwordRecall,undefined);assert.equal(new Battle({mode:'training',path:0,meta:['sword-meta-5']}).level,72);});
void test('old-profile conversion is explicit, refunds full cost and preserves the current run and achievements',()=>{const save={...initialSave(),insight:9,meta:all,achievements:['a'],checkpoint:make(0,all,{metaRulesVersion:1}).serialize()};delete save.metaRulesVersion;const parsed=normalizeSave(save),before=JSON.stringify(parsed);assert.equal(needsCultivationUpgrade(parsed),true);const plan=planCultivationUpgrade(parsed);assert.equal(plan.refund,2070);assert.equal(plan.save.insight,2079);assert.equal(plan.save.metaRulesVersion,3);assert.equal(plan.save.meta.length,0);assert.deepEqual(plan.save.checkpoint,parsed.checkpoint);assert.deepEqual(plan.save.achievements,['a']);assert.equal(JSON.stringify(parsed),before);assert.equal(planMetaRefund(plan.save).refund,0);});
void test('a failed conversion write preserves the old profile, and confirmed success makes a backup',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)},old={...initialSave(),metaRulesVersion:1,meta:own(0)};map.set(SAVE_KEY,JSON.stringify(old));const vault=new SaveVault(storage),profile=vault.load(),raw=map.get(SAVE_KEY);assert.equal(map.get(SAVE_KEY),raw);const next=planCultivationUpgrade(profile).save,write=storage.setItem;storage.setItem=(k,v)=>{if(k===SAVE_KEY)throw Error('quota');write(k,v);};assert.throws(()=>vault.commit(next,{backup:true}));assert.equal(map.get(SAVE_KEY),raw);storage.setItem=write;vault.commit(next,{backup:true});assert.equal(JSON.parse(map.get(BACKUP_KEY)).raw,raw);assert.equal(JSON.parse(map.get(SAVE_KEY)).insight,345);});
