/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition,EQUIPMENT} from '../gameplay/expedition.js';import {createRun,restoreRun} from '../gameplay/run-factory.js';import {ENCOUNTERS,CORES,CHAINS,SUPPLIES,defaultGarden,settleGarden} from '../gameplay/expedition-data.js';import {initialSave,xpCost,RELICS} from '../gameplay/data.js';import {normalizeSave} from '../gameplay/save-store.js';
const run=(o={})=>new Expedition({seed:'expedition-tests',path:0,growthVersion:3,encounterVersion:3,economyVersion:2,...o});const round=b=>restoreRun(JSON.parse(JSON.stringify(b.serialize())));const begin=b=>{b.start();if(b.cinematic)b.advanceCinematic(true);};
function settle(b){if(b.cinematic)b.advanceCinematic(true);if(b.scene==='intermission'){if(!b.chooseInteraction(0)&&!b.rest.eventDone)b.chooseInteraction(2);if(!b.rest.coreDone)b.skipCore();if(!b.rest.routeDone)b.chooseRoute(0);b.continueRest();}while(b.modeState==='choice')b.chooseTrait(b.choices[0].id);if(b.scene==='intermission')b.continueRest();}
void test('new runs use isolated rules 3 while rule 1 and 2 saves remain legacy',()=>{assert.equal(createRun().rulesVersion,3);for(const n of [1,2]){const b=createRun({rulesVersion:n});assert.equal(restoreRun(JSON.parse(JSON.stringify(b.serialize()))).rulesVersion,n);}});
void test('content and every route combination keep the agreed XP budget and nine forks',()=>{assert.equal(ENCOUNTERS.length,18);assert.equal(EQUIPMENT.length,48);assert.equal(CORES.length,12);assert.equal(CHAINS.length,8);assert.equal(SUPPLIES.length,6);const b=run(),flat=b.routes.flat();assert.equal(flat.length,22);assert.equal(flat.filter(n=>n.choices.length===2).length,9);assert.equal(flat.reduce((s,n)=>s+n.xp,0),11960);let required=0;for(let n=1;n<72;n++)required+=xpCost(n);assert.equal(required,10971);assert.ok(11960-300>=required);for(let mask=0;mask<512;mask++){let i=0,total=0;for(const n of flat)total+=n.xp+(n.choices.length===2&&(mask>>i++&1)?Math.floor(n.xp*.08):0);assert.ok(total>=11960&&total<=12335);}});
void test('route and event rolls survive a live combat roundtrip without resetting targets or drops',()=>{const b=run();begin(b);for(let i=0;i<400;i++)b.update(.05);const c=round(b);assert.deepEqual(c.routes,b.routes);assert.equal(c.time,b.time);assert.deepEqual(c.drops,b.drops);assert.equal(c.enemies.length,b.enemies.length);assert.equal(c.rng.state(),b.rng.state());assert.equal(c.contentRng.state(),b.contentRng.state());});
void test('legacy growth payout tops up kill XP once and does not pay again after restore',()=>{const b=run({growthVersion:1});begin(b);b.addXP(15);b.completeNode();assert.equal(b.totalXP,80);const gold=b.gold,c=round(b);c.completeNode();assert.equal(c.totalXP,80);assert.equal(c.gold,gold);assert.equal(c.receipts.length,1);assert.equal(c.rest.node,'0:0');});
void test('full chapter transitions preserve 22 receipts, guarantee 72 swords before final, and pay six research points',()=>{const b=run();begin(b);let guard=0;while(!b.finished&&guard++<120){if(b.modeState==='intro')begin(b);if(b.cinematic){b.advanceCinematic(true);continue;}if(b.modeState==='battle'){if(b.chapter===5&&b.wave===3){assert.ok(b.level>=72);assert.equal(b.swords.length,72);}b.completeNode();}settle(b);}assert.ok(b.finished);assert.equal(b.receipts.length,22);assert.equal(b.research,6);assert.equal(b.totalXP,11960);assert.equal(b.won,true);const g=settleGarden(defaultGarden(),b.summary());assert.equal(g.points,6);assert.deepEqual(settleGarden(g,b.summary()),g);});
void test('guaranteed cores include compatible starter options and two-core / same-family limits hold',()=>{for(let path=0;path<6;path++){const b=run({path});assert.ok(b.makeCoreOffers().some(id=>CORES.find(c=>c.id===id).path===path));}const b=run();begin(b);b.completeNode();b.rest.selectionMode='committed';b.rest.coreDone=false;b.rest.coreOffers=['K01','K02','K03','K04'];assert.equal(b.equipCore('K01'),true);b.rest.coreDone=false;assert.equal(b.equipCore('K03'),true);b.rest.coreDone=false;assert.equal(b.equipCore('K02'),true);assert.deepEqual(b.relics,['K03','K02']);});
void test('thunder cores cannot refund reserve or recurse arcs, focused hit preserves other targets',()=>{const b=run();begin(b);b.clearField();b.relics=['K03'];b.recalc();b.player.mana=100;const reserve=b.player.reserve;b.spawn(0,{x:850,y:450,hp:1e5});b.spawn(0,{x:880,y:450,hp:1e5});b.rebuildHash();assert.equal(b.thunder(),true);assert.equal(b.player.reserve,reserve-28);for(let i=0;i<20;i++)b.hit(b.enemies[0],10,'sword',false);assert.equal(b.coreArcs,0);assert.equal(b.player.reserve,reserve-28);assert.ok(b.damageSources.arc>0);});
void test('twin sigils arm at most two, use six-second spacing and one bounded fire line',()=>{const b=run({path:4});begin(b);b.relics=['K10'];b.dash();assert.equal(b.zones.filter(z=>z.twin).length,1);assert.equal(b.zones.find(z=>z.twin).warn,8);b.time=6.1;b.player.dashCD=0;b.player.x+=300;b.dash();const z=b.zones.filter(z=>z.twin);assert.equal(z.length,2);assert.ok(z.every(z=>z.warn===.8));assert.equal(z.filter(z=>z.line).length,1);});
void test('guard breaking consumes real absorption and equipment changes cannot heal',()=>{const b=run({path:5});begin(b);b.relics=['K11'];b.recalc();b.player.shield=12;b.player.invuln=0;b.hitPlayer(100);assert.equal(b.lastShieldBreak,b.time);const stamp=b.lastShieldBreak;b.player.shield=0;b.recalc();assert.equal(b.lastShieldBreak,stamp);b.completeNode();b.rest.shop=true;b.makeShop();const item=RELICS.find(r=>r.mods.hp);b.shop=[{...item,kind:'relic',price:35}];b.gold=100;b.player.hp=b.player.maxHp*.4;assert.equal(b.buy(0),true);b.sell(b.relics.indexOf(item.id));assert.ok(Math.abs(b.player.hp/b.player.maxHp-.4)<1e-8);assert.equal(b.gold,79);});
void test('mechanism rooms grant no enemies or farmable XP; ice does not refill reserve',()=>{const b=run();b.chapter=3;b.wave=0;begin(b);for(let i=0;i<40;i++)b.update(.05);assert.equal(b.enemies.length,0);assert.equal(b.kills,0);b.chapter=5;b.wave=2;b.player.reserve=17;begin(b);b.time=40;b.waveTime=40;b.player.x=1130;b.player.y=640;b.update(.05);settle(b);assert.equal(b.wave,3);assert.equal(b.player.reserve,17);});
void test('research excluded from training and replay, garden corruption is protected',()=>{for(const mode of ['training','replay','endless'])assert.equal(settleGarden(defaultGarden(),{mode,runId:'x',research:6}).points,0);assert.throws(()=>normalizeSave({...initialSave(),garden:{...defaultGarden(),points:-1}}));const b=run();const s=normalizeSave({...initialSave(),checkpoint:b.serialize()});assert.equal(s.checkpoint.options.rulesVersion,3);});
void test('fixed spawn tiers do not punish elapsed time spent on earlier rooms',()=>{const b=run(),c=run();begin(b);begin(c);b.time=100;c.time=5000;b.clearField();c.clearField();const a=b.spawn(0),z=c.spawn(0);assert.equal(a.hp,z.hp);assert.equal(a.dmg,z.dmg);});
void test('each of eighteen objective templates starts with reachable goals and settles through its own rule',()=>{for(const def of ENCOUNTERS){const b=run();b.node.choices=[{...def,risk:false}];b.node.selected=0;b.cinematicSeen=['bamboo'];b.beginNode();const q=b.objective;if(['survival','defend'].includes(def.kind)){b.waveTime=65;b.updateDirector(.01);}if(def.kind==='hunt'){for(let i=0;i<3;i++){if(q.spawned<=i)b.spawnMarked();const e=b.enemies.find(e=>e.mission==='marked'&&!e.dead);b.kill(e);}}if(['break','escape'].includes(def.kind)){for(const e of [...b.enemies].filter(e=>e.mission==='rune'))b.kill(e);if(def.kind==='escape'){b.player.x=q.exit.x;b.player.y=q.exit.y;b.updateDirector(.01);}}if(def.kind==='pursuit')b.kill(b.enemies.find(e=>e.mission==='carrier'));assert.equal(b.receipts.length,1,def.id);assert.equal(b.totalXP,80,def.id);}});
void test('core effects change coverage, focused thunder, puppet rhythm, swarm locks and light-shield dash',()=>{
 const b=run();begin(b);b.clearField();b.relics=['K02'];b.formation=1;const e=b.spawn(0,{x:b.player.x+230,y:b.player.y,hp:1e6,spawn:0});b.rebuildHash();b.swords[0].cool=0;b.updateSwords(.01);assert.equal(b.swords[0].target,e);
 b.relics=['K04'];b.player.mana=100;const e2=b.spawn(0,{x:b.player.x-230,y:b.player.y,hp:1e6,spawn:0});b.input.aim={x:e.x,y:e.y};const before=e.hp,before2=e2.hp;b.thunder();assert.ok((before-e.hp)/(before2-e2.hp)>1.6);
 const c=run({path:2});begin(c);c.clearField();c.relics=['K05'];c.puppets=[{},{}];c.stillTime=1;const a={x:600,y:400},target={x:900,y:400};c.onPuppetShot(a,target,20);assert.equal(c.shots.length,0);c.onPuppetShot(a,target,20);assert.equal(c.shots.length,2);c.relics=['K06'];c.player.moving=true;assert.equal(c.puppetHasteBonus(),.35);c.player.moving=false;assert.equal(c.puppetHasteBonus(),0);
 const bugs=run({path:3});begin(bugs);bugs.clearField();bugs.relics=['K07'];bugs.spawn(0,{x:700,y:500});bugs.spawn(0,{x:760,y:500});bugs.rebuildHash();const t0=bugs.allyTarget(640,500,350,{kind:'insect',index:0}),t1=bugs.allyTarget(640,500,350,{kind:'insect',index:1});assert.notEqual(t0.id,t1.id);assert.equal(bugs.allyTarget(620,500,350,{kind:'insect',index:0}),t0);bugs.relics=['K08'];bugs.targetCache={};const elite=bugs.spawn(0,{x:800,y:600,elite:true});bugs.rebuildHash();assert.equal(bugs.allyTarget(640,500,400,{kind:'insect',index:0}),elite);
 const guard=run({path:5});begin(guard);guard.relics=['K12'];guard.recalc();guard.player.shield=10;assert.equal(guard.movementBonus(),.12);guard.dash();assert.equal(guard.player.shield,5);assert.ok(guard.player.dashCD<3);guard.player.dashCD=0;guard.player.shield=0;assert.equal(guard.dash(),true);
});
void test('lingering sigil creates only one three-second slowing field',()=>{const b=run({path:4});begin(b);b.relics=['K09'];b.dash();const z=b.zones.find(z=>z.sigil);assert.equal(z.ember,true);const original=z.originalDamage;assert.equal(z.damage,original*.8);b.onSigilDetonate(z);const ember=b.zones.find(z=>z.friendly&&z.slow);assert.equal(ember.ttl,3);assert.equal(ember.damage,original*.1);});
void test('all supply schemes preserve the extra meta medicine without losing a slot',()=>{for(const supply of SUPPLIES){const b=run({supply:supply.id,meta:['sword-meta-1'],metaRulesVersion:1});assert.equal(b.consumables.length,2);const base=b.consumables.reduce((a,c)=>a+c.count+(c.bonusHeal||0),0);assert.equal(base,supply.items.reduce((a,c)=>a+c[1],0)+1);const c=round(b);begin(c);c.player.hp=20;const index=c.consumables[0].bonusHeal?0:c.consumables.findIndex(s=>['heal','heal2'].includes(s.id));c.consume(index);assert.ok(c.player.hp>20);}});
void test('malformed new mechanics and rewards are rejected before a save can replace valid bytes',()=>{for(const mutate of [c=>c.expedition.choices=[{id:'unknown'}],c=>c.expedition.rest={node:'x',coreOffers:[]},c=>c.expedition.zones=[{x:1,y:2,r:-5,damage:2,ttl:1,warn:0}],c=>c.expedition.objective={kind:'illusion',gates:[],trueGate:0}]){const b=run(),s={...initialSave(),checkpoint:JSON.parse(JSON.stringify(b.serialize()))};mutate(s.checkpoint);assert.throws(()=>normalizeSave(s));}});
void test('side contracts only add XP after success and never remove the base allowance',()=>{for(const contract of ['hits','time','thunder']){const b=run();b.node.choices[0].risk=true;b.node.choices[0].contract=contract;begin(b);b.hitCount=6;b.waveTime=80;b.thunders=1;b.completeNode();assert.equal(b.totalXP,80);}});
void test('new Xuan Gu retains both phase gates and the final thirteen-second escape',()=>{const b=run();b.chapter=5;b.wave=3;begin(b);const boss=b.boss;boss.spawn=0;b.hit(boss,1e9,'thunder',false);assert.equal(boss.phase,1);boss.phaseShield=0;b.hit(boss,1e9,'thunder',false);assert.equal(boss.phase,2);boss.phaseShield=0;b.hit(boss,1e9,'thunder',false);assert.equal(b.bossEnding,13);assert.equal(boss.hp,1);assert.equal(b.receipts.length,0);b.player.invuln=100;for(let i=0;i<280;i++){b.update(.05);while(b.modeState==='choice')b.chooseTrait(b.choices[0].id);}assert.equal(b.receipts.length,1);assert.equal(b.scene,'intermission');});
void test('stationary rune objectives receive existing burn damage while unlocked',()=>{const b=run({path:4});begin(b);b.clearField();const e=b.spawn(23,{mission:'rune',hp:1000,untargetable:false,burn:3,burnDamage:20,burnTick:0});const hp=e.hp;b.updateEnemy(e,.05);assert.ok(e.hp<hp);e.untargetable=true;const blocked=e.hp;e.burnTick=0;b.updateEnemy(e,.05);assert.equal(e.hp,blocked);});
void test('marked suicide enemies count as resolved exactly once when self-destructing',()=>{const b=run();b.chapter=2;b.wave=0;b.node.choices=[{...ENCOUNTERS.find(e=>e.kind==='hunt'&&e.variant===2),risk:false}];b.node.selected=0;b.beginNode();const marked=b.enemies.find(e=>e.mission==='marked');marked.ai='suicide';marked.timer=0;marked.fuse=.01;marked.spawn=0;marked.x=b.player.x+20;marked.y=b.player.y;const before=b.objective.done;b.updateEnemy(marked,.05);assert.equal(b.objective.done,before+1);b.recordMarked(marked);assert.equal(b.objective.done,before+1);});
