/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {RELICS,TRAITS,STAT_NAMES,modText,relicDescription} from '../gameplay/data.js';import {traitDescription} from '../gameplay/descriptions.js';import {healthFraction,drawHealthBar} from '../gameplay/meters.js';
function arena(){const b=new Expedition({seed:'health-fix',difficulty:1});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};return b;}
const round=b=>Expedition.restore(JSON.parse(JSON.stringify(b.serialize())));
void test('health meters shrink independently of a thick elite outline and do not divide by zero',()=>{const draw=[],ctx={lineWidth:8,globalAlpha:.2,fillStyle:'',save(){this.saved={lineWidth:this.lineWidth,globalAlpha:this.globalAlpha,fillStyle:this.fillStyle};},restore(){Object.assign(this,this.saved);},fillRect(x,y,w,h){draw.push({x,y,w,h,color:this.fillStyle});},strokeRect(){assert.fail('health bars must not inherit stroke width');}};for(const hp of [1000,500,100,0]){draw.length=0;const m=drawHealthBar(ctx,20,30,80,7,hp,1000);assert.equal(m.fill,hp*.08);assert.equal(draw.filter(r=>r.color==='#081712')[0].w,80);assert.equal(ctx.lineWidth,8);assert.equal(ctx.globalAlpha,.2);}assert.equal(healthFraction(1,0),0);assert.equal(healthFraction(-3,100),0);assert.equal(healthFraction(200,100),1);});
void test('custom-life mission targets and elite guards keep a stable maximum while taking damage',()=>{const b=arena();for(const mission of ['marked','carrier','runeGuard','rune',undefined]){const e=b.spawn(0,{mission,elite:mission!=='rune',x:800,y:350,hp:1000,speed:0});b.hit(e,250,'fire',false);assert.equal(e.hp,750);assert.equal(e.maxHp,1000);assert.equal(healthFraction(e.hp,e.maxHp),.75);}});
void test('every trait and equipment attribute has Chinese display text, including old saved raw descriptions',()=>{const all=[...RELICS,...TRAITS];for(const item of all)for(const k of Object.keys(item.mods))assert.ok(STAT_NAMES[k],k);for(const r of RELICS){assert.doesNotMatch(r.desc,/[a-z]+[A-Z][a-z]+|shield\s+\d/);assert.doesNotMatch(modText(r.mods),/[A-Za-z]/);}assert.equal(relicDescription({id:'kit-5-2',desc:'携行配置：shield 25 / shieldRegen 2'}),'护盾上限 +25 · 护盾恢复 +2 / 秒');assert.equal(modText({iframes:.03}),'闪避无敌时间 +0.03 秒');assert.doesNotMatch(modText({unrecognizedInternalKey:2}),/unrecognizedInternalKey/);});
void test('stationary runes stay at designed positions and cannot be displaced by sword, crossbow or shock',()=>{const b=arena();b.player.x=640;b.player.y=520;const e=b.spawn(23,{mission:'rune',x:660,y:520,hp:10000,speed:0});assert.equal(e.x,660);assert.equal(e.y,520);b.rebuildHash();b.swords=[{x:655,y:520,px:655,py:520,a:0,cool:1,target:e,hits:[],life:1,pierce:0}];b.updateSwords(.01);assert.equal(e.x,660);b.stats.puppetKnock=1;b.updateSwords=()=>{};b.updateAllies=()=>{};b.shots=[{x:e.x,y:e.y,vx:520,vy:0,damage:1,ttl:1,r:5,friendly:true,hits:[],pierce:0,source:'puppet'}];b.update(.01);assert.equal(e.x,660);b.consumables=[{id:'shock',count:1}];b.consume(0);assert.equal(e.x,660);assert.equal(e.y,520);});
void test('explicit spawn speed and damage are honored rather than overwritten by chapter scaling',()=>{const b=arena(),e=b.spawn(0,{speed:0,dmg:0});assert.equal(e.speed,0);assert.equal(e.dmg,0);});
void test('a lethal mission thunder saves shield and resource effects, then stops hitting the cleared room',()=>{let checkpoint;const b=arena();b.emit=ev=>{if(ev.type==='checkpoint')checkpoint=JSON.parse(JSON.stringify(ev.checkpoint));};b.objective={kind:'hunt',done:2,spawned:3};const target=b.spawn(0,{hp:1,elite:true,mission:'marked'}),other=b.spawn(0,{hp:1});b.player.mana=100;b.stats.thunderShield=18;const reserve=b.player.reserve;b.thunder();assert.equal(target.hp,0);assert.equal(other.hp,1);assert.equal(b.kills,1);assert.equal(b.scene,'intermission');assert.equal(b.drops.length,0);assert.equal(checkpoint.player.shield,18);assert.equal(checkpoint.player.reserve,reserve-25);assert.equal(checkpoint.player.mana,0);});
void test('finishing explosions and sigils cannot add post-checkpoint rewards or new fire zones',()=>{const b=arena();b.objective={kind:'hunt',done:2,spawned:3};b.spawn(0,{hp:1,mission:'marked',x:800,y:400});const other=b.spawn(0,{hp:1,x:810,y:400});b.rebuildHash();b.explode(800,400,100,100,'fire');assert.equal(b.scene,'intermission');assert.equal(b.kills,1);assert.equal(other.hp,1);assert.equal(b.drops.length,0);const c=arena();c.objective={kind:'hunt',done:2,spawned:3};c.spawn(0,{hp:1,mission:'marked',x:800,y:400,speed:0});c.updateSwords=()=>{};c.updateAllies=()=>{};c.stats.metaSigilEcho=1;c.zones=[{x:800,y:400,r:100,ttl:1,warn:0,sigil:true,friendly:true,kind:'sigil',damage:100}];c.update(.01);assert.equal(c.scene,'intermission');assert.equal(c.zones.length,0);});
void test('resume preserves entity sequence, passive cooldowns and peak enemy counts',()=>{const b=arena();b.time=10;b.id=99;b.lastChain=8;b.lastWard=9;b.maxEnemies=140;const c=round(b);assert.equal(c.id,99);assert.equal(c.lastChain,8);assert.equal(c.lastWard,9);assert.equal(c.maxEnemies,140);assert.equal(c.spawn(0).id,99);});
void test('older snapshots avoid reusing IDs already referenced by active arrows or swords',()=>{const b=arena();b.shots=[{x:400,y:400,px:400,py:400,vx:1,vy:0,hits:[91],damage:1,ttl:1,r:5,pierce:0,friendly:true}];b.swords[0].hits=[120];const data=JSON.parse(JSON.stringify(b.serialize()));delete data.expedition.nextEntityId;const c=Expedition.restore(data);assert.equal(c.spawn(0).id,121);});
void test('sigil upgrade text reflects the equipped cultivation range instead of a fixed radius',()=>{const b=new Expedition({path:4,meta:['talisman-meta-1']}),t=TRAITS.find(t=>t.id==='talisman-10');assert.match(traitDescription(t,b),/115/);assert.match(traitDescription(t,b),/布符缩短到 0.2 秒/);});
void test('the thunder core bank is included in a finishing-cast checkpoint',()=>{const b=arena();let saved;b.emit=e=>{if(e.type==='checkpoint')saved=JSON.parse(JSON.stringify(e.checkpoint));};b.relics=['K03'];b.objective={kind:'hunt',done:2,spawned:3};b.spawn(0,{mission:'marked',hp:1});b.player.mana=100;b.thunder();assert.equal(b.coreArcs,10);assert.equal(saved.expedition.coreArcs,10);assert.equal(round(b).coreArcs,10);});
void test('lethal damage resolves defeat before retaliation and cannot save a negative-health clear',()=>{const b=arena();b.player.hp=1;b.player.shield=0;b.player.invuln=0;b.stats.thorns=1;b.objective={kind:'hunt',done:2,spawned:3};const e=b.spawn(0,{mission:'marked',hp:1});e.x=b.player.x+40;e.y=b.player.y;b.rebuildHash();let saves=0;b.emit=ev=>{if(ev.type==='checkpoint')saves++;};b.hitPlayer(999);assert.equal(b.player.hp,0);assert.equal(b.finished,true);assert.equal(b.won,false);assert.equal(e.hp,1);assert.equal(saves,0);});
