/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {META,CONSUMABLES} from '../gameplay/data.js';import {damageRows,shieldReward} from '../gameplay/combat-feedback.js';
const copy=x=>JSON.parse(JSON.stringify(x)),own=p=>META.filter(m=>m.path===p).map(m=>m.id);
function arena(path=0){const b=new Expedition({balanceVersion:2,metaRulesVersion:2,seed:'player-feedback',path,difficulty:1,meta:own(path)});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};b.player.invuln=0;return b;}
function target(b,extra={}){const e=b.spawn(4,{x:850,y:400,hp:10000,spawn:0,...extra});b.rebuildHash();return e;}
void test('shield recovery never reduces existing extra shields across boundary values',()=>{for(const shield of [0,25,33,50,57,63,78,195,10000]){const p={maxShield:33,shield},gain=shieldReward(p,30,30);assert.ok(gain>=0&&gain<=30);assert.equal(p.shield,shield);assert.equal(gain,Math.max(0,Math.min(30,63-shield)));}});
void test('both chain rewards preview the actual gain and settle exactly once without removing extra shields',()=>{for(const id of [1,6])for(const prior of [0,1])for(const shield of [0,55,78,195]){const b=arena(5);b.completeNode();b.queuedChoices=0;b.player.shield=shield;const c=b.chains[0];c.chain='chain-'+id;c.choice=prior;c.state='active';b.rest.event={type:'chain',id:c.chain,stage:'end',choice:null};b.rest.eventDone=false;b.rest.eventApplied=false;b.rest.coreOffers=[];b.rest.coreDone=true;b.rest.coreApplied=true;const amount=shieldReward(b.player,prior===0?30:24,30);assert.match(b.eventText().choices[0],new RegExp('当前可恢复 '+amount+' 护盾'));assert.equal(b.chooseInteraction(0),true);assert.equal(b.player.shield,shield);b.chooseRoute(0);assert.equal(b.commitRestSelections(),true);assert.equal(b.player.shield,shield+amount);b.commitRestSelections();assert.equal(b.player.shield,shield+amount);}});
// Round-2 C-1 moved this announcement from the single toast slot to the cue channel; the four semantics below are unchanged.
void test('guard counter preserves excess shields and announces only a real gain',()=>{for(const shield of [0,195]){const b=arena(5);const opening=b.toastText;b.player.shield=shield;b.dash();b.hitPlayer(10);assert.equal(b.hitCount,0);assert.equal(b.recentHits.length,0);assert.equal(b.player.shield,shield+(shield===0?6:0));const cue=b.combatCues.find(c=>c.key==='counter');assert.ok(cue,'guard counter announces on the cue channel');assert.match(cue.text,shield===0?/回盾 \+6/:/额外护盾保留/);assert.equal(b.toastText,opening,'the counter confirmation no longer takes the single battle toast slot');assert.ok(b.player.buffs.metaGuardSwift>b.time);}});
void test('pure healing and mana consumables cannot be wasted at full and remain usable near full',()=>{for(const c of CONSUMABLES.filter(c=>['heal','mana'].includes(c.effect))){const b=arena();b.consumables=[{id:c.id,count:2}];b.player.hp=b.player.maxHp;b.player.mana=100;assert.equal(b.consume(0),false);assert.equal(b.consumables[0].count,2);const field=c.effect==='heal'?'hp':'mana';b.player[field]-=.6;assert.ok(Math.abs(b.itemReadiness(0).gain-.6)<1e-10);assert.equal(b.consume(0),true);assert.equal(b.consumables[0].count,1);assert.equal(b.player[field],100);assert.equal(b.consume(0),false);}});
void test('shield, timed recovery and mixed-effect consumables still work at full health',()=>{for(const id of ['shield','recovery','blink','guard','shield2','sword','puppet','insect']){const b=arena();b.consumables=[{id,count:1}];assert.equal(b.consume(0),true,id);assert.equal(b.consumables[0].count,0,id);}});
void test('old bonus medicine is retained at full health while the underlying item remains usable',()=>{const b=arena();b.consumables=[{id:'shield',count:1,bonusHeal:1}];assert.equal(b.itemReadiness(0).item.id,'shield');assert.equal(b.consume(0),true);assert.equal(b.consumables[0].bonusHeal,1);assert.equal(b.consume(0),false);b.player.hp=50;assert.equal(b.itemReadiness(0).bonus,true);assert.equal(b.consume(0),true);assert.equal(b.player.hp,85);assert.equal(b.consumables[0].bonusHeal,0);b.consumables=[{id:'mana',count:1,bonusHeal:1}];b.player.hp=100;b.player.mana=100;assert.equal(b.consume(0),false);assert.deepEqual(b.consumables[0],{id:'mana',count:1,bonusHeal:1});});
void test('legacy very large but valid accumulated damage stays readable after adding classification',()=>{const b=arena(4),d=copy(b.serialize());delete d.fireBreakdown;d.damageSources.fire=1e180;const r=Expedition.restore(d);assert.equal(Expedition.restore(copy(r.serialize())).fireBreakdown.history,1e180);});
void test('new fire damage splits actual damage and sums to the retained aggregate',()=>{const b=arena(4),e=target(b);for(const k of ['burn','sigil','echo','ember','line','other'])b.hit(e,10,'fire',false,k);assert.ok(Math.abs(Object.values(b.fireBreakdown).reduce((a,v)=>a+v,0)-b.damageSources.fire)<1e-6);assert.equal(b.fireBreakdown.history,0);assert.equal(damageRows(b).filter(r=>r.key.startsWith('fire-')).length,6);e.untargetable=true;const before=copy(b.fireBreakdown);b.hit(e,100,'fire',false,'sigil');assert.deepEqual(b.fireBreakdown,before);e.untargetable=false;e.hp=2;b.hit(e,1000,'fire',false,'echo');assert.equal(b.fireBreakdown.echo,before.echo+2);});
void test('old unclassified fire survives restore without inventing a historical breakdown',()=>{for(const rulesVersion of [1,2,3]){const b=rulesVersion===3?arena(4):new Battle({rulesVersion,path:4});const d=copy(b.serialize());delete d.fireBreakdown;delete d.recentHits;d.damageSources.fire=123;const restore=d=>rulesVersion===3?Expedition.restore(d):Battle.restore(d),r=restore(d);assert.equal(r.fireBreakdown.history,123);assert.equal(r.fireBreakdown.burn,0);assert.deepEqual(r.recentHits,[]);assert.equal(restore(copy(r.serialize())).fireBreakdown.history,123);assert.equal(r.rulesVersion,rulesVersion);}});
void test('sigil, echo, ember and line hooks attribute their own real effects',()=>{const b=arena(4);b.relics=['K09'];b.recalc();const e=target(b);b.player.x=e.x;b.player.y=e.y;b.updateSwords=()=>{};b.updateAllies=()=>{};b.updateEnemy=()=>{};b.input={x:1,y:0};b.dash();const origin={x:e.x,y:e.y};b.update(.05);assert.equal(b.zones[0].x,origin.x);assert.ok(b.player.x>origin.x);for(let i=0;i<28;i++)b.update(.05);assert.ok(b.fireBreakdown.sigil>0);assert.ok(b.fireBreakdown.echo>0);assert.ok(b.fireBreakdown.ember>0);b.onSigilDetonate({x:e.x+10,y:e.y,line:{x:e.x-10,y:e.y,damage:10}});assert.ok(b.fireBreakdown.line>0);assert.ok(Math.abs(Object.values(b.fireBreakdown).reduce((a,v)=>a+v,0)-b.damageSources.fire)<1e-6);assert.equal(b.damageSources.fire>0,true);});
void test('recent hits keep the last five actual losses, survive pause and restore, and identify a fatal source',()=>{let b=arena();b.player.shield=15;for(let i=0;i<5;i++){b.time=i;b.player.invuln=0;b.hitPlayer(4,false,{name:'邪修弩手',x:900,y:300,kind:'弹幕'});}assert.equal(b.recentHits[0].shield,4);assert.equal(b.recentHits.at(-1).hp,4);b.pause();const d=copy(b.serialize());b.update(.05);assert.deepEqual(b.recentHits,d.recentHits);b=Expedition.restore(d);assert.deepEqual(b.recentHits,d.recentHits);b.resume();b.player.invuln=0;b.hitPlayer(1000,true,{name:'毒雾',x:600,y:400,kind:'险地'});assert.equal(b.recentHits.length,5);assert.equal(b.recentHits[0].time,1);assert.equal(b.recentHits.at(-1).remaining,0);assert.equal(b.summary().recentHits.at(-1).name,'毒雾');assert.equal(b.failureReason,'生命耗尽');});
void test('new projectile provenance survives save and reaches the hit report',()=>{const b=arena(),e=target(b);b.attackOrigin={name:e.name,x:e.x,y:e.y};b.shoot(b.player.x-15,b.player.y,0,10,100);b.attackOrigin=null;const r=Expedition.restore(copy(b.serialize()));r.updateDirector=()=>{};r.updateEnemy=()=>{};r.updateSwords=()=>{};r.updateAllies=()=>{};r.player.invuln=0;r.update(.01);assert.equal(r.recentHits[0].name,e.name);assert.equal(r.recentHits[0].kind,'弹幕');});
void test('defense objective failures identify the array separately from player deaths',()=>{const b=arena();b.objective={kind:'defend',x:500,y:400,hp:20,maxHp:20,invuln:0};b.hitObjective(25,{name:'妖兽',x:600,y:400,kind:'近身'});assert.equal(b.failureReason,'阵盘失守');assert.equal(b.recentHits[0].target,'阵盘');assert.equal(b.recentHits[0].hp,20);assert.equal(b.player.hp,100);});
void test('malformed telemetry is refused and missing old fields are accepted',()=>{for(const mutate of [d=>d.fireBreakdown.sigil=1,d=>d.fireBreakdown.history=-1,d=>d.recentHits=Array(6).fill({}),d=>d.recentHits=[{time:99999}],d=>d.expedition.shots[0].origin={name:'bad',x:Infinity,y:0},d=>d.expedition.zones[0].fireKind='history']){const b=arena();b.shoot(400,300,0,5);b.danger(700,400,30,5);const d=copy(b.serialize());mutate(d);assert.throws(()=>Expedition.restore(d),/反馈|来源/);}});
void test('feedback remains bounded without drawing ordinary damage numbers',()=>{const b=arena(4),e=target(b,{hp:1e9});b.options.settings={numbers:false};const rng=b.rng.state();for(let i=0;i<500;i++){b.hit(e,1,'fire',false,'sigil');b.cue('sigil','符阵爆发');}assert.equal(b.combatCues.length,1);assert.ok(b.fx.filter(f=>f.kind==='number').length<=1);assert.equal(b.rng.state(),rng);assert.ok(b.fx.some(f=>f.key));});
