/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {SaveVault,SAVE_KEY,BACKUP_KEY,RAW_BACKUP_KEY,JOURNAL_KEY,recoveryPreview,recoveryImportCandidates,normalizeSave} from '../gameplay/save-store.js';
import {recoverRecords,recordReceipt,settleRunResult} from '../gameplay/records.js';
import {Expedition} from '../gameplay/expedition.js';
import {initialSave} from '../gameplay/data.js';
import {battleCamera,offscreenDirection} from '../gameplay/camera.js';
const memory=()=>{const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
function fixture(){let save=initialSave();for(let path=0;path<5;path++){const b=new Expedition({segmentVersion:0,challengeVersion:0,seed:'recover-five',runId:'recover-five-'+path,path});b.chapter=5;b.wave=3;b.receipts=b.routes.flat().map(n=>n.id);b.time=120+path;b.won=true;b.finished=true;save=settleRunResult(save,b.summary());}save.records.receipts.push(recordReceipt('older-settled-result','finish'));save.records.entries.push({...save.records.entries[0],timeMs:-1});save.insight=4321;save.kills=98765;save.checkpoint=new Expedition({segmentVersion:0,challengeVersion:0,seed:'valid-checkpoint'}).serialize();return save;}
void test('A1 preview and cancel keep bytes; adoption preserves five scores, all receipts, checkpoint and original across three new saves',()=>{const store=memory(),raw=JSON.stringify(fixture());store.setItem(SAVE_KEY,raw);const v=new SaveVault(store);assert.throws(()=>v.load());const before=JSON.stringify([...store.map]),c=v.recoveryCandidates().find(c=>c.id==='primary');assert.equal(c.save.insight,4321);assert.equal(c.save.kills,98765);assert.equal(c.save.records.entries.length,5);assert.equal(c.save.records.receipts.length,6);assert.ok(c.save.checkpoint);assert.equal(c.recordReport.isolated,1);assert.equal(JSON.stringify([...store.map]),before);v.adoptRecovery(c.save,{expectedSnapshot:c.expectedSnapshot,sourceRaw:c.raw});assert.equal(v.load().records.entries.length,5);assert.ok(v.rawRecords().some(r=>r.raw===raw));for(let i=0;i<3;i++)v.commit({...v.load(),checkpoint:new Expedition({segmentVersion:0,challengeVersion:0,seed:'new-'+i}).serialize()},{backup:true});assert.ok(v.recoveryCandidates().some(c=>c.save?.insight===4321&&c.recordReport?.kept===5));});
void test('A1 historical wrappers and recovery export reimport in fresh storage without pre-confirmation writes',()=>{const raw=JSON.stringify(fixture());for(const input of [raw,JSON.stringify({raw,savedAt:1}),JSON.stringify({records:[{raw,savedAt:1}]}),JSON.stringify({format:'fanren-preserved-state',primary:raw}),JSON.stringify({format:'fanren-recovery-records',primary:null,records:[{raw,savedAt:1}]})]){const s=memory(),v=new SaveVault(s);v.load();const before=JSON.stringify([...s.map]),rows=recoveryImportCandidates(input);assert.equal(rows.length,1);assert.equal(rows[0].save.records.entries.length,5);assert.equal(JSON.stringify([...s.map]),before);v.adoptRecovery(rows[0].save,{expectedSnapshot:v.snapshot(),sourceRaw:input});assert.equal(v.load().insight,4321);assert.ok(v.rawRecords().some(r=>r.raw===input));}});
void test('A1 conflicting groups isolate both entries while keeping valid receipt history; unknown schema stays explicit',()=>{const f=fixture();f.records.entries.push(structuredClone(f.records.entries[1]));f.records.receipts.push('bad',f.records.receipts[0]);const r=recoverRecords(f.records);assert.equal(r.report.kept,4);assert.equal(r.report.isolated,3);assert.equal(r.report.isolatedReceipts,2);assert.equal(r.records.receipts.length,6);const p=recoveryPreview(JSON.stringify({...f,records:{schema:99,entries:[{}]}}));assert.equal(p.recordReport.unknownSchema,true);assert.equal(p.save.insight,4321);assert.equal(recoveryPreview('{').save,null);assert.equal(recoveryPreview('{"version":99}').status,'未知格式');assert.throws(()=>recoveryImportCandidates('{"format":"fanren-recovery-records","records":[{}]}'));});
void test('A1 each write/remove failure leaves primary, backup, invalid journal and prior quarantine recoverable',()=>{for(let failAt=1;failAt<=9;failAt++){const s=memory(),raw=JSON.stringify(fixture()),backup=JSON.stringify({raw:JSON.stringify({...initialSave(),insight:701}),savedAt:1}),journal='{"invalid":true}';s.setItem(SAVE_KEY,raw);s.setItem(BACKUP_KEY,backup);s.setItem(JOURNAL_KEY,journal);s.setItem(RAW_BACKUP_KEY,JSON.stringify({raw:'old protected bytes',savedAt:1}));const v=new SaveVault(s);assert.throws(()=>v.load());const c=v.recoveryCandidates().find(c=>c.id==='primary');let calls=0;const set=s.setItem,remove=s.removeItem;s.setItem=(k,value)=>{if(++calls===failAt)throw Error('quota');set(k,value);};s.removeItem=k=>{if(++calls===failAt)throw Error('remove');remove(k);};try{v.adoptRecovery(c.save,{expectedSnapshot:c.expectedSnapshot,sourceRaw:c.raw});}catch{}s.setItem=set;s.removeItem=remove;const bundle=v.recoveryBundle(),protectedValues=bundle.records.flatMap(r=>{try{const x=JSON.parse(r.raw);return [r.raw,x.primary,x.backup,x.pendingBackup];}catch{return [r.raw];}});for(const original of [raw,backup,journal,'old protected bytes'])assert.ok([bundle.primary,bundle.backup,bundle.pendingBackup,...protectedValues].includes(original),'lost pre-state at write '+failAt);assert.ok(s.getItem(SAVE_KEY)===raw||normalizeSave(JSON.parse(s.getItem(SAVE_KEY))).insight===4321);}});
void test('A1 any concurrent primary/backup/journal/quarantine change aborts stale preview with no new writes',()=>{for(const key of [SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY]){const s=memory();s.setItem(SAVE_KEY,JSON.stringify(fixture()));const v=new SaveVault(s);assert.throws(()=>v.load());const c=v.recoveryCandidates()[0];s.setItem(key,'concurrent');const before=JSON.stringify([...s.map]);assert.throws(()=>v.adoptRecovery(c.save,{expectedSnapshot:c.expectedSnapshot,sourceRaw:c.raw}),/窗口/);assert.equal(JSON.stringify([...s.map]),before);}});
void test('A1 busy journal presents its original logical backup separately from intermediate candidates',()=>{const s=memory(),primary=JSON.stringify(initialSave()),before=JSON.stringify({raw:JSON.stringify({...initialSave(),insight:777})}),after=JSON.stringify({raw:primary});s.setItem(SAVE_KEY,primary);s.setItem(BACKUP_KEY,after);s.setItem(JOURNAL_KEY,JSON.stringify({key:BACKUP_KEY,before,after,primaryAfter:JSON.stringify({...initialSave(),insight:2}),owner:'other',createdAt:Date.now()}));const v=new SaveVault(s);v.load();assert.equal(v.recoveryCandidates().find(c=>c.id==='backup').save.insight,777);assert.ok(v.recoveryCandidates().some(c=>c.id==='pending-primary'));});
void test('A3 camera preserves readable player edges, phone width, inverse coordinates and offscreen boss directions',()=>{for(const [w,h]of [[390,844],[360,640],[320,568],[844,390],[1440,1000]])for(const x of [28,640,1252])for(const y of [36,400,772]){const c=battleCamera(w,h,{x,y},{top:140,bottom:h<430?125:200,left:w>900?180:0});assert.ok(w>900||(c.right-c.left)/c.scale/1280>=.59);const px=c.x+x*c.scale,py=c.y+y*c.scale;assert.ok(px>=c.left&&px<=c.right);assert.ok(py>=c.top&&py<=c.bottom);assert.ok(Math.abs((px-c.x)/c.scale-x)<1);assert.ok(Math.abs((py-c.y)/c.scale-y)<1);const marker=offscreenDirection(c,{x:10000,y:-10000});assert.ok(marker&&marker.x>=c.left&&marker.x<=c.right&&marker.y>=c.top&&marker.y<=c.bottom);}});
void test('A0 invalid difficulty, route, starter, flag and version fail before any simulated result',()=>{for(const env of [{BATTLE_DIFFICULTY:'3'},{BATTLE_DIFFICULTY:''},{BATTLE_RISK:'2'},{BATTLE_PATHS:'0,6'},{BATTLE_SHARED_SEED:'yes'},{BATTLE_GROWTH_VERSION:'99'}]){const r=spawnSync(process.execPath,['scripts/expedition-simulate.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,...env},encoding:'utf8'});assert.notEqual(r.status,0);assert.equal(r.stdout,'');assert.match(r.stderr,/BATTLE_/);}});
