/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';import {SaveVault,SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY,normalizeSave,recoveryImportCandidates} from '../gameplay/save-store.js';import {initialSave} from '../gameplay/data.js';import {Expedition} from '../gameplay/expedition.js';import {settleRunResult} from '../gameplay/records.js';import {createSceneInput} from '../gameplay/scene-input.js';
const memory=()=>{const map=new Map();return{map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}};
void test('round12 confirmed latest checks every source without writes, then adopts only current validated bytes',()=>{for(const key of [SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY]){const s=memory();s.setItem(SAVE_KEY,JSON.stringify({...initialSave(),insight:120}));const v=new SaveVault(s);v.load();s.setItem(SAVE_KEY,JSON.stringify({...initialSave(),insight:333,kills:2222}));const raw=JSON.stringify([...s.map]);const p=v.previewLatest();assert.equal(p.save.insight,333);assert.equal(JSON.stringify([...s.map]),raw);s.setItem(key,'changed');const changed=JSON.stringify([...s.map]);assert.throws(()=>v.loadConfirmed(p.expectedSnapshot),/已变化/);assert.equal(JSON.stringify([...s.map]),changed);}const s=memory();const v=new SaveVault(s);v.load();s.setItem(SAVE_KEY,JSON.stringify({...initialSave(),insight:777}));const p=v.previewLatest();assert.equal(v.loadConfirmed(p.expectedSnapshot).insight,777);});
void test('round12 ordinary backup recovery protects complete pre-state and source, and stale preview never writes',()=>{for(const key of [SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY]){const s=memory(),v=new SaveVault(s);v.load();v.commit({...initialSave(),insight:222});v.commit({...initialSave(),insight:444},{backup:true});const c=v.recoveryCandidates().find(c=>c.id==='backup');assert.equal(c.save.insight,222);s.setItem(key,'another page');const raw=JSON.stringify([...s.map]);assert.throws(()=>v.adoptRecovery(c.save,{expectedSnapshot:c.expectedSnapshot,sourceRaw:c.raw}),/窗口/);assert.equal(JSON.stringify([...s.map]),raw);}const s=memory(),v=new SaveVault(s);v.load();v.commit({...initialSave(),insight:222});v.commit({...initialSave(),insight:444},{backup:true});const before=v.snapshot(),c=v.recoveryCandidates().find(c=>c.id==='backup');v.adoptRecovery(c.save,{expectedSnapshot:c.expectedSnapshot,sourceRaw:c.raw});const protectedText=JSON.stringify(v.rawRecords());assert.ok(protectedText.includes('444'));assert.ok(v.rawRecords().some(r=>r.raw===c.raw));assert.ok(v.rawRecords().some(r=>{try{return JSON.parse(r.raw).backup===before.backup;}catch{return false;}}));});
void test('round12 pending result export contains actual receipts and retry/reimport cannot settle twice',()=>{const s=memory(),v=new SaveVault(s);v.load();const b=new Expedition({segmentVersion:0,challengeVersion:0,seed:'r12-result',runId:'r12-result'});b.time=111;b.receipts=b.routes.flat().map(n=>n.id);b.won=true;b.kills=234;b.research=6;const summary=b.summary(),next=settleRunResult(initialSave(),summary),originalSet=s.setItem;s.setItem=()=>{throw Error('denied')};assert.throws(()=>v.commit(next));const raw=JSON.stringify(next),preview=recoveryImportCandidates(raw)[0];assert.equal(preview.save.kills,234);assert.equal(preview.save.garden.points,6);assert.equal(preview.save.records.receipts.length,1);s.setItem=originalSet;const saved=v.commit(preview.save);assert.equal(settleRunResult(saved,summary),saved);assert.deepEqual(normalizeSave(JSON.parse(raw)).records,saved.records);});
void test('round12 complete, drag, cancelled, cross-scene and repeat physical input cycles are distinct',()=>{const g=createSceneInput(),p={pointerId:7,clientX:20,clientY:20,button:0};g.pointerDown(p);const valid=g.armPointer(p);g.pointerUp(p);assert.equal(g.consume(valid,{detail:1}),true);assert.equal(g.consume(valid,{detail:1}),false);g.pointerDown(p);const old=g.armPointer(p);g.invalidate();g.pointerUp(p);assert.equal(g.consume(old,{detail:1}),false);g.pointerDown(p);const drag=g.armPointer(p);g.pointerMove({...p,clientX:40});g.pointerUp(p);assert.equal(g.consume(drag,{detail:1}),false);g.pointerDown(p);const cancel=g.armPointer(p);g.pointerCancel(p);assert.equal(g.consume(cancel,{detail:1}),false);g.keyDown({code:'Space'});const held=g.armKey({code:'Space'});g.invalidate();g.keyUp({code:'Space'});assert.equal(g.consume(held,{detail:0}),false);g.keyDown({code:'Enter'});const key=g.armKey({code:'Enter'});assert.equal(g.consume(key,{detail:0}),true);assert.equal(g.armKey({code:'Enter',repeat:true}),null);});
