/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import {EVENTS} from '../gameplay/data.js';
import test from 'node:test';import assert from 'node:assert/strict';import {BALANCE4} from '../gameplay/balance.js';import {Expedition} from '../gameplay/expedition.js';import {beginPracticeStep as currentPractice,updatePractice} from '../gameplay/practice.js';import {beginPracticeStep as priorPractice} from '../scripts/fixtures/qa-round12-practice-before.js';import {starterStatus,starterDetails} from '../gameplay/starters.js';import {cultivationUse,META} from '../gameplay/cultivation.js';
void test('R12 S0 places the actual training target near the player without changing RNG or rewards',()=>{for(let seed=0;seed<12;seed++){const options={seed:'r12-s0-check-'+seed,path:4,mode:'training',guidedPractice:true},a=new Expedition(options),b=new Expedition(options);a.start();b.start();priorPractice(a,5);currentPractice(b,5);const target=b.enemies.find(e=>e.practiceTarget);assert.deepEqual({x:target.x,y:target.y},{x:640,y:410});assert.equal(a.rng.state(),b.rng.state());assert.equal(b.totalXP,0);assert.equal(b.research,0);assert.equal(b.receipts.length,0);updatePractice(b,1/60);assert.match(b.practice.sigilHint,/靠近|距离合适/);}});
void test('R12 guard status reports the real available window without causing a counter or touching the run',()=>{const b=new Expedition({path:5,seed:'r12-status',balanceVersion:3});b.beginNode();b.clearField();b.input={x:1,y:0};b.requestDash();const snapshot=structuredClone(b.serialize());assert.match(starterStatus(b),/待化解 0.24/);assert.ok(b.combatCues.some(c=>c.key==='guard-window'&&c.until===b.time+.24));assert.deepEqual(b.serialize(),snapshot);b.hitPlayer(10);assert.match(starterStatus(b),/本次闪避已反击/);const shield=b.player.shield;b.hitPlayer(10);assert.equal(b.player.shield,shield);});
void test('R12 focused insect targeting and per-target sword progress are explained without changing rules',()=>{assert.match(cultivationUse(META.find(m=>m.id==='insect-meta-3')),/明确集火.*远敌.*双群巡猎.*凝群穿甲/);assert.match(starterDetails(0).limit,/小怪提前倒下不会把进度转给下一个目标/);const b=new Expedition({path:4,seed:'r12-kept-rules'});assert.equal(b.options.balanceVersion,4);assert.equal(b.options.metaRulesVersion,3);assert.equal(b.options.growthVersion,5);assert.equal(b.options.economyVersion,4);b.beginNode();b.input={x:1,y:0};b.requestDash();assert.equal(b.zones.find(z=>z.sigil).fuseDuration,BALANCE4.sigilWarn);const kept=new Expedition({path:4,seed:'r12-kept-rules',balanceVersion:3});kept.beginNode();kept.input={x:1,y:0};kept.requestDash();assert.equal(kept.zones.find(z=>z.sigil).fuseDuration,2.4);});

void test('R12 guard cue is fresh on a 0.9-second cooldown and clears waiting immediately after counter',()=>{const b=new Expedition({path:5,seed:'r12-cue-repeat',balanceVersion:3});b.beginNode();b.clearField();b.updateDirector=b.updateEnvironment=b.updateSwords=b.updateAllies=()=>{};b.stats.dashHaste=.65;b.input={x:1,y:0};b.requestDash();assert.equal(b.player.dashCD,.9);assert.ok(b.combatCues.some(c=>c.key==='guard-window'));b.hitPlayer(10);assert.ok(!b.combatCues.some(c=>c.key==='guard-window'));assert.ok(b.combatCues.some(c=>c.key==='counter'&&c.text.includes('已化解')));for(let f=0;f<19;f++)b.update(.05);assert.equal(b.requestDash(),true);assert.ok(b.combatCues.some(c=>c.key==='guard-window'&&c.until>b.time));b.hitPlayer(10);assert.ok(!b.combatCues.some(c=>c.key==='guard-window'));assert.ok(b.combatCues.some(c=>c.key==='counter'&&c.until>=b.time+.99));});
function restFixture(node){const b=new Expedition({path:0,seed:'r12-quote',runId:'r12-quote'});for(let step=0;step<600;step++){if(b.scene==='intermission'&&b.rest.node===node)break;if(b.scene==='cinematic')b.advanceCinematic(true);else if(b.modeState==='intro')b.start();else if(b.modeState==='choice')b.chooseTrait(b.choices[0].id);else if(b.modeState==='battle'){b.time+=1;b.waveTime=1;b.completeNode();}else if(b.scene==='intermission'){if(!b.rest.eventDone)b.chooseInteraction(b.eventText().choices.length-1);if(!b.rest.coreDone)b.skipCore();if(!b.rest.routeDone)b.chooseRoute(0);b.continueRest();}}if(!b.rest.eventDone)b.chooseInteraction(b.eventText().choices.length-1);if(!b.rest.coreDone)b.skipCore();if(!b.rest.routeDone)b.chooseRoute(0);b.gold=500;return b;}
void test('R12 supply quote is read-only, exposes chapter healing overlap, permits the unchanged zero-retained policy and rejects stale quotes',()=>{const b=restFixture('4:3');b.player.hp=b.player.maxHp-20;const before=b.serialize(),rng=b.rng.state(),q=b.supplyQuote('hp');assert.deepEqual(b.serialize(),before);assert.equal(b.rng.state(),rng);assert.equal(q.retainedGain,0);b.gold--;const changed=b.serialize();assert.equal(b.buySupply('hp',q),false);assert.deepEqual(b.serialize(),changed);const fresh=b.supplyQuote('hp');assert.equal(b.buySupply('hp',fresh),true);assert.equal(b.economy.supplyPurchases.length,1);assert.equal(b.economy.supplyPurchases[0].price,80);assert.equal(b.player.hp,b.player.maxHp);});

void test('R12 quote identifies the paid draft invalidated by spending; failed departure keeps it editable',()=>{const b=restFixture('4:0'),event=EVENTS.find(e=>e.choices.some(c=>c.effect==='buyHeal')),choice=event.choices.findIndex(c=>c.effect==='buyHeal');b.rest.event={type:'single',index:event.id,choice:null};b.rest.eventDone=false;b.rest.eventApplied=false;b.player.hp=b.player.maxHp-40;b.gold=90;assert.equal(b.chooseInteraction(choice),true);const q=b.supplyQuote('hp');assert.ok(q.draftImpact.includes(event.name));assert.match(q.draftImpact,/不可提交|改选/);assert.equal(b.buySupply('hp',q),true);assert.equal(b.gold,10);assert.equal(b.restReadiness().ready,false);const node=b.node.id;b.continueRest();assert.equal(b.node.id,node);assert.equal(b.chooseInteraction(event.choices.length-1),true);assert.equal(b.restReadiness().ready,true);Expedition.restore(b.serialize());});
