/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {createRun} from '../gameplay/run-factory.js';
import {growthGuidance,reserveRestGuidance,objectiveGuidance,routeCompletion,storyItemStates} from '../gameplay/player-guidance.js';
import {CURRENT_RECORD_RULES,browseRecordEntries,recordRuleKey} from '../gameplay/record-browser.js';
const run=(options={})=>{const b=createRun({seed:'r12-guidance',mode:'story',...options});b.beginNode();return b;};
await test('guidance is read-only across all 22 nodes and growth rules, with fixed goal deadline separate from remaining time',()=>{for(const growthVersion of [1,2,3,4]){const b=run({growthVersion});for(let chapter=0;chapter<6;chapter++)for(let wave=0;wave<b.routes[chapter].length;wave++){b.chapter=chapter;b.wave=wave;b.node.selected??=0;b.beginNode();b.waveTime=10;const before=JSON.stringify(b.serialize());const first=growthGuidance(b);if(growthVersion===4){assert.match(first.detail,/固定期限 \d+ 秒 · 剩余 \d+ 秒/);b.waveTime=20;const next=growthGuidance(b);assert.equal(first.detail.match(/固定期限 \d+/)[0],next.detail.match(/固定期限 \d+/)[0]);b.waveTime=10;}else if(first)assert.doesNotMatch(first.detail,/期限/);objectiveGuidance(b);routeCompletion(b.encounter);storyItemStates(b);assert.equal(JSON.stringify(b.serialize()),before);}}});
await test('reserve display splits actual receipt under capacity and does not claim rest on old balance1',()=>{for(const extra of [0,5])for(const room of [0,3,15,18,40]){const b=run({path:1,balanceVersion:3,metaRulesVersion:3,meta:extra?['thunder-meta-3']:[]});b.player.reserve=b.player.maxReserve-room;b.completeNode();const before=JSON.stringify(b.serialize()),text=reserveRestGuidance(b);assert.match(text,new RegExp('实际到账 '+Math.min(room,15+extra)));assert.match(text,/受储量上限限制/);assert.equal(JSON.stringify(b.serialize()),before);}const b=run({path:1,balanceVersion:1});b.player.reserve=0;b.completeNode();assert.equal(reserveRestGuidance(b),'');});
await test('current and historical browsing never mutates or merges original record groups',()=>{const entries=[{segmentVersion:1,mode:'story',difficulty:0,path:1,timeMs:5,touchLockUsed:false,rules:{...CURRENT_RECORD_RULES}},{mode:'story',difficulty:0,path:1,timeMs:2,touchLockUsed:false,rules:{...CURRENT_RECORD_RULES,growthVersion:3}},{mode:'story',difficulty:0,path:1,timeMs:1,touchLockUsed:true,rules:{...CURRENT_RECORD_RULES,growthVersion:3}}],before=JSON.stringify(entries);assert.equal(browseRecordEntries(entries,{rules:'current'}).length,1);assert.equal(browseRecordEntries(entries,{rules:'historical'}).length,2);assert.equal(browseRecordEntries(entries,{rules:recordRuleKey(entries[1].rules),lock:'used'}).length,1);assert.equal(browseRecordEntries(entries,{rules:'all'}).length,3);assert.equal(JSON.stringify(entries),before);});
await test('objective and item text keeps fixed conditions and possession separate from active effects',()=>{const b=run();b.chapter=5;b.wave=2;b.beginNode();b.waveTime=39;assert.match(objectiveGuidance(b),/39 \/ 40/);b.waveTime=40;assert.equal(objectiveGuidance(b),'退路已开 · 前往右侧出口');b.waveTime=88;assert.doesNotMatch(objectiveGuidance(b),/88 \/ 40/);b.storyInventory=['weeping','five-rings'];b.relics=[];assert.match(storyItemStates(b)[0].state,/未启用协战/);b.relics=['weeping'];assert.equal(storyItemStates(b)[0].state,'协战配置生效');assert.match(storyItemStates(b)[1].state,/未配置/);assert.doesNotMatch(routeCompletion({kind:'treasure',goal:'每阵14秒'}),/14/);assert.doesNotMatch(routeCompletion({kind:'illusion',goal:'每10秒'}),/10/);});
