/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Battle} from '../gameplay/engine.js';
import {SaveVault,SAVE_KEY,BACKUP_KEY,RAW_BACKUP_KEY,checkpointDirty} from '../gameplay/save-store.js';
import {initialSave} from '../gameplay/data.js';
function memory(){const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};}
const profile=()=>({...initialSave(),checkpoint:new Battle({path:3,seed:'checkpoint'}).serialize()});
void test('legacy checkpoints keep original starter rules while new runs gain identities',()=>{const old=new Battle({path:3,rulesVersion:1});const snapshot=old.serialize();delete snapshot.options.rulesVersion;const restored=Battle.restore(snapshot,()=>{});assert.equal(restored.rulesVersion,1);assert.equal(restored.stats.insects,2);const fresh=new Battle({path:3});assert.equal(fresh.rulesVersion,2);assert.equal(fresh.stats.insects,4);assert.equal(new Battle({path:2}).stats.puppets,2);assert.equal(new Battle({path:1}).player.mana,50);});
void test('four sword hits empower the fourth and leave earlier strikes normal',()=>{const b=new Battle({path:0}),e=b.spawn(0,{hp:10000});const hits=Array.from({length:4},()=>b.hit(e,10,'sword',false));assert.deepEqual(hits.map(h=>h.empowered),[false,false,false,true]);assert.equal(e.hp,9956);});
void test('sigil detonates once and has a separate cooldown from dodge',()=>{const b=new Battle({path:4});b.start();b.enemies=[];b.spawnBudget=-1e5;b.updateSwords=()=>{};b.updateAllies=()=>{};const e=b.spawn(0,{x:b.player.x,y:b.player.y,speed:0,hp:1000,spawn:0});b.dash();assert.equal(b.zones.filter(z=>z.sigil).length,1);for(let i=0;i<100;i++)b.update(1/60);assert.ok(Math.abs(e.hp-(1000-56.2))<.01);b.player.dashCD=0;b.dash();assert.equal(b.lastSigil,0);});
void test('successful guard dodge counters once and restores shield without endless overlap procs',()=>{const b=new Battle({path:5});b.start();b.enemies=[];b.spawn(0,{x:650,y:400,hp:1000,spawn:0});b.rebuildHash();b.dash();b.hitPlayer(25);const damage=b.damageSources.guard,shield=b.player.shield;assert.ok(damage>0);assert.equal(shield,31);for(let i=0;i<50;i++)b.hitPlayer(25);assert.equal(b.damageSources.guard,damage);assert.equal(b.player.shield,shield);});
void test('priority targeting guides allies toward the selected focus point',()=>{const b=new Battle({path:3});b.spawn(0,{x:650,y:400});const chosen=b.spawn(0,{x:800,y:400});b.rebuildHash();b.input.focus=true;b.input.aim={x:800,y:400};assert.equal(b.allyTarget(640,400,350).id,chosen.id);});
void test('new-run commits retain the previous valid record as a recoverable backup',()=>{const storage=memory(),v=new SaveVault(storage);v.load();v.commit(profile());const previous=storage.getItem(SAVE_KEY);v.commit({...initialSave(),wins:2},{backup:true});assert.equal(JSON.parse(storage.getItem(BACKUP_KEY)).raw,previous);assert.equal(v.backup().save.checkpoint.options.path,3);});
void test('storage failure preserves prior disk bytes and expected revision',()=>{const storage=memory(),v=new SaveVault(storage);v.load();v.commit(profile());const old=storage.getItem(SAVE_KEY),write=storage.setItem;storage.setItem=(key,val)=>{if(key===SAVE_KEY)throw Error('quota');write(key,val);};assert.throws(()=>v.commit({...initialSave(),wins:8},{backup:true}),e=>e.code==='storage');assert.equal(storage.getItem(SAVE_KEY),old);assert.equal(v.expectedRaw,old);});
void test('stale windows cannot overwrite a newer profile',()=>{const storage=memory(),one=new SaveVault(storage),two=new SaveVault(storage);one.load();one.commit(profile());two.load();one.commit({...profile(),wins:4});const latest=storage.getItem(SAVE_KEY);assert.throws(()=>two.commit({...profile(),wins:9}),e=>e.code==='conflict');assert.equal(storage.getItem(SAVE_KEY),latest);});
void test('unreadable source is never implicitly replaced; confirmed new save quarantines original',()=>{const storage=memory();storage.setItem(SAVE_KEY,'{broken');const v=new SaveVault(storage);assert.throws(()=>v.load());assert.throws(()=>v.commit(initialSave()),e=>e.code==='invalid');assert.equal(storage.getItem(SAVE_KEY),'{broken');v.commit(initialSave(),{allowCorrupt:true,backup:true});assert.equal(JSON.parse(storage.getItem(RAW_BACKUP_KEY)).raw,'{broken');});
void test('dirty detection covers a running wave and changes made at a rest stop',()=>{const b=new Battle(),save={checkpoint:b.serialize()};assert.equal(checkpointDirty(b,save),false);b.start();b.update(.05);b.update(.05);assert.equal(checkpointDirty(b,save),true);b.pause();assert.equal(checkpointDirty(b,save),true);const c=new Battle(),saved={checkpoint:c.serialize()};c.relics=['kit-0-0'];assert.equal(checkpointDirty(c,saved),true);});

void test('committed checkpoint remains detached from mutable live equipment',()=>{const storage=memory(),v=new SaveVault(storage),b=new Battle();v.load();const saved=v.commit({...initialSave(),checkpoint:b.serialize()});b.relics.push('kit-0-0');b.consumables[0].count=0;assert.deepEqual(saved.checkpoint.relics,[]);assert.equal(saved.checkpoint.consumables[0].count,2);assert.equal(checkpointDirty(b,saved),true);});

void test('malformed key bindings and future-crashing checkpoint statistics are rejected before disk write',()=>{const storage=memory(),v=new SaveVault(storage);v.load();v.commit(profile());const original=storage.getItem(SAVE_KEY);assert.throws(()=>v.commit({...profile(),keymap:{thunder:null}}));const bad=profile();bad.checkpoint.damageSources=null;assert.throws(()=>v.commit(bad));assert.equal(storage.getItem(SAVE_KEY),original);});

void test('new-run damage totals exclude overkill when comparing starter contribution',()=>{const b=new Battle();const e=b.spawn(0,{hp:10});b.hit(e,999,'thunder',false);assert.equal(b.damageSources.thunder,10);});
void test('thunder starter opens a five-second damage window but still spends reserve',()=>{const b=new Battle({path:1,difficulty:1});b.start();const original=b.swordDamage();b.player.mana=100;assert.equal(b.thunder(),true);assert.equal(b.player.reserve,115);assert.ok(Math.abs(b.swordDamage()/original-1.25)<1e-8);b.time=6;assert.equal(b.swordDamage(),original);});
void test('puppet deployment speeds shots only while stopped long enough',()=>{const b=new Battle({path:2});b.enemies=[];b.spawn(0,{x:700,y:400,hp:10000,spawn:0});b.rebuildHash();b.updateAllies(.01);b.stillTime=.6;for(const a of b.puppets)a.cool=0;b.updateAllies(.01);assert.ok(b.puppets.every(a=>Math.abs(a.cool-.56)<1e-8));b.stillTime=0;for(const a of b.puppets)a.cool=0;b.updateAllies(.01);assert.ok(b.puppets.every(a=>Math.abs(a.cool-.7)<1e-8));});
void test('insect gnaw is capped and expires after the target is released',()=>{const b=new Battle({path:3});const e=b.spawn(0,{x:640,y:400,hp:10000,spawn:0});b.rebuildHash();b.updateAllies(.001);for(let n=0;n<3;n++){for(const bug of b.insects){bug.x=e.x;bug.y=e.y;bug.cool=0;}b.updateAllies(.001);}assert.equal(e.gnaw,.12);b.time=3.1;const before=e.hp;b.hit(e,100,'puppet',false);assert.ok(Math.abs(before-e.hp-100)<1e-8);});
