/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {ENCOUNTERS} from '../gameplay/expedition-data.js';import {initialSave,RELICS,CONSUMABLES} from '../gameplay/data.js';import {SaveVault,normalizeSave,SAVE_KEY,BACKUP_KEY,JOURNAL_KEY} from '../gameplay/save-store.js';
const copy=x=>JSON.parse(JSON.stringify(x)),arena=()=>{const b=new Expedition({seed:'report-fixes'});b.cinematicSeen=['bamboo','ruins'];b.beginNode();b.clearField();return b;};
const memory=()=>{const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
void test('bad player, enemy, sword and endless fields are rejected with readable errors before commit',()=>{const mutations=[d=>d.player.buffs=null,d=>delete d.player.x,d=>delete d.expedition.enemies[0].speed,d=>delete d.expedition.enemies[0].cost,d=>d.expedition.enemies[0].ai='unknown',d=>d.endlessLoop=1000000,d=>d.endlessLoop='abc',d=>d.time=1e308,d=>d.level=1.5,d=>delete d.expedition.swords[0].cool,d=>d.options.meta=[null],d=>d.notices={},d=>d.consumables=[null]];for(const mutate of mutations){const b=arena();b.spawn(0);const data=copy(b.serialize());mutate(data);assert.throws(()=>normalizeSave({...initialSave(),checkpoint:data}),e=>/无效|不兼容/.test(e.message)&&!(e instanceof TypeError));}});
void test('missing optional buffs merge safe defaults and normal snapshots continue for six starters',()=>{for(let path=0;path<6;path++){const b=new Expedition({path,seed:'schema-roundtrip'});b.cinematicSeen=['bamboo'];b.beginNode();for(let i=0;i<100;i++)b.update(.01);const d=copy(b.serialize());delete d.player.buffs;const c=Expedition.restore(d);assert.deepEqual(c.player.buffs,{});c.update(.01);assert.ok(Number.isFinite(c.player.x));}});
void test('unknown top-level fields are not carried into future saves',()=>{const s=normalizeSave({...initialSave(),unrecognizedBlob:'junk',arbitrary:{x:1}});assert.equal(s.unrecognizedBlob,undefined);assert.equal(s.arbitrary,undefined);});
void test('failed primary write restores the previous backup byte for byte',()=>{const st=memory(),old=JSON.stringify({...initialSave(),insight:1}),current=JSON.stringify({...initialSave(),insight:2});st.setItem(SAVE_KEY,current);st.setItem(BACKUP_KEY,old);const v=new SaveVault(st);v.load();const write=st.setItem;st.setItem=(k,val)=>{if(k===SAVE_KEY)throw Error('quota');write(k,val);};assert.throws(()=>v.commit({...initialSave(),insight:3},{backup:true}));assert.equal(st.getItem(SAVE_KEY),current);assert.equal(st.getItem(BACKUP_KEY),old);assert.equal(st.getItem(JOURNAL_KEY),null);});
void test('interrupted rollback keeps a persisted recovery record which restores after reload',()=>{const st=memory(),v=new SaveVault(st);st.setItem(SAVE_KEY,JSON.stringify({...initialSave(),insight:2}));const oldBackup=JSON.stringify({raw:JSON.stringify({...initialSave(),insight:1}),savedAt:1});st.setItem(BACKUP_KEY,oldBackup);v.load();const write=st.setItem;let backupWrites=0;st.setItem=(k,val)=>{if(k===SAVE_KEY)throw Error('primary blocked');if(k===BACKUP_KEY&&++backupWrites>1)throw Error('rollback blocked');write(k,val);};assert.throws(()=>v.commit({...initialSave(),insight:3},{backup:true}));assert.ok(st.getItem(JOURNAL_KEY));assert.equal(v.backup().save.insight,1);assert.equal(JSON.parse(st.getItem(JOURNAL_KEY)).before,oldBackup);st.setItem=write;const j=JSON.parse(st.getItem(JOURNAL_KEY));j.createdAt=0;st.setItem(JOURNAL_KEY,JSON.stringify(j));const reloaded=new SaveVault(st);assert.equal(reloaded.load().insight,2);assert.equal(st.getItem(BACKUP_KEY),oldBackup);assert.equal(st.getItem(JOURNAL_KEY),null);});
void test('a failure before journal creation leaves both existing slots untouched',()=>{const st=memory(),v=new SaveVault(st);st.setItem(SAVE_KEY,JSON.stringify(initialSave()));st.setItem(BACKUP_KEY,'original-backup');v.load();const prior=st.getItem(SAVE_KEY);st.setItem=()=>{throw Error('all writes blocked');};assert.throws(()=>v.commit({...initialSave(),insight:9},{backup:true}));assert.equal(st.getItem(SAVE_KEY),prior);assert.equal(st.getItem(BACKUP_KEY),'original-backup');});
void test('a foreign active transaction cannot be taken over before its owner finishes',()=>{const st=memory(),a=new SaveVault(st),b=new SaveVault(st);a.load();a.commit(initialSave());b.load();st.setItem(JOURNAL_KEY,JSON.stringify({key:BACKUP_KEY,before:null,after:'new',primaryAfter:'not-written',owner:a.owner,createdAt:Date.now()}));assert.throws(()=>b.commit({...initialSave(),insight:2},{backup:true}),e=>e.code==='busy');assert.ok(st.getItem(JOURNAL_KEY));});
void test('multiple quarantined records remain exportable and profile-only recovery never writes implicitly',()=>{const st=memory(),v=new SaveVault(st);for(const raw of ['{bad-first','{bad-second']){st.setItem(SAVE_KEY,raw);assert.throws(()=>v.load());v.commit(initialSave(),{allowCorrupt:true,backup:true});}assert.deepEqual(v.recoveryBundle().records.map(r=>r.raw),['{bad-first','{bad-second']);const broken={...initialSave(),insight:56,checkpoint:{broken:true}};st.setItem(SAVE_KEY,JSON.stringify(broken));assert.throws(()=>v.load());const raw=st.getItem(SAVE_KEY),profile=v.profileOnly();assert.equal(profile.insight,56);assert.equal(profile.checkpoint,null);assert.equal(st.getItem(SAVE_KEY),raw);v.commit(profile,{allowCorrupt:true,backup:true});assert.equal(v.rawRecords().length,3);});
void test('shops preserve the full current shield across medicine, equipment cycles and core changes',()=>{for(const path of [0,5]){const b=new Expedition({path});b.cinematicSeen=['bamboo','ruins'];b.beginNode();b.completeNode();b.player.shield=65;b.gold=1000;b.shop=[{...CONSUMABLES[0],kind:'consumable',price:25},{...RELICS.find(r=>r.id==='kit-5-2'),kind:'relic',price:50}];b.buy(0);assert.equal(b.player.shield,65);b.buy(1);assert.equal(b.player.shield,65);b.sell(b.relics.indexOf('kit-5-2'));assert.equal(b.player.shield,65);b.rest.selectionMode='applying';b.rest.coreOffers=['K01'];b.rest.coreDone=false;b.equipCore('K01');assert.equal(b.player.shield,65);}});
void test('escort reinforcements trigger once per crossed interval outside the normal spawn loop',()=>{const b=arena();b.options.encounterVersion=1;b.options.contentVersion=2;b.pursuitState=null;b.directorState=null;b.node.choices=[{...ENCOUNTERS.find(e=>e.kind==='pursuit'&&e.variant===1),risk:false}];b.node.selected=0;b.beginNode();while(b.enemies.length<180)b.spawn(0);b.spawnBudget=0;b.nextElite=999;const spawn=b.spawn.bind(b),times=[];b.spawn=(t,o)=>{if(o?.elite)times.push(b.waveTime);return spawn(t,o);};for(const t of [14.99,15.01,15.02,29.99,30.01]){b.time=t;b.waveTime=t;b.updateDirector(.02);}assert.deepEqual(times,[15.01,30.01]);const saved=Expedition.restore(copy(b.serialize()));assert.equal(saved.nextEscort,45);});
void test('invalid trading indexes have no effects and replacement keeps the existing no-refund rule',()=>{const old=new Battle();old.modeState='rest';old.sell(99);assert.equal(old.gold,45);const b=arena();b.completeNode();b.gold=100;b.relics=['K01',...RELICS.filter(r=>!r.story).slice(0,5).map(r=>r.id)];b.shop=[{...RELICS.find(r=>r.id==='kit-5-2'),kind:'relic',price:35}];assert.equal(b.buy(0,42),false);assert.equal(b.relics.length,6);assert.equal(b.gold,100);b.paidPrices.K01=0;assert.equal(b.buy(0,0),true);assert.equal(b.gold,65);assert.equal(b.hasCore('K01'),false);assert.equal(b.paidPrices.K01,undefined);});
void test('seal consumables stop after a node ends instead of leaking kills and drops',()=>{const b=arena();b.objective={kind:'hunt',done:2,spawned:3};b.spawn(0,{mission:'marked',hp:1});for(let i=0;i<5;i++)b.spawn(0,{hp:1});b.consumables=[{id:'seal',count:1}];b.consume(0);assert.equal(b.kills,1);assert.equal(b.drops.length,0);assert.equal(b.scene,'intermission');});
void test('armor facing is continuous across the negative and positive pi boundary',()=>{const damage=[];for(const a of [-Math.PI+.01,Math.PI-.01]){const b=arena(),e=b.spawn(7,{x:850,y:400,hp:1000});b.player.x=e.x-100;b.player.y=e.y+1;e.a=a;b.hit(e,100,'sword',false);damage.push(1000-e.hp);}assert.deepEqual(damage,[60,60]);});
void test('restored shop and choice labels come from verified content rather than arbitrary saved objects',()=>{const b=arena();b.completeNode();b.shop=[{...RELICS[4],kind:'relic',price:42}];b.choices=b.traitChoices();const d=copy(b.serialize());d.expedition.shop[0].name={bad:true};d.expedition.shop[0].mods=null;d.expedition.choices[0].name={bad:true};const c=Expedition.restore(d);assert.equal(typeof c.shop[0].name,'string');assert.equal(c.shop[0].price,42);assert.equal(typeof c.choices[0].name,'string');assert.ok(c.shop[0].mods);});
void test('defeat results distinguish a destroyed array from losing player life',()=>{const b=arena();b.objective={kind:'defend',hp:1,maxHp:100,invuln:0};b.hitObjective(2);assert.equal(b.player.hp,100);assert.equal(b.summary().failureReason,'阵盘失守');const c=arena();c.player.invuln=0;c.hitPlayer(1e6);assert.equal(c.summary().failureReason,'生命耗尽');});
