/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {EVENTS,META,RELICS,initialSave} from '../gameplay/data.js';import {defaultGarden,settleGarden} from '../gameplay/expedition-data.js';import {planMetaRefund,planGardenRefund} from '../gameplay/respec.js';import {normalizeSave} from '../gameplay/save-store.js';
const restore=b=>Expedition.restore(JSON.parse(JSON.stringify(b.serialize())));
function rest(core=false){const b=new Expedition({seed:'reselection',path:0});if(core)b.wave=3;b.cinematicSeen=['bamboo','ruins'];b.beginNode();b.completeNode();b.queuedChoices=0;if(core)b.rest.coreOffers=['K01','K02','K03'];return b;}
function cashEvent(b){const index=EVENTS.findIndex(e=>e.choices.some(c=>c.effect==='gold')&&e.choices.some(c=>c.effect==='shield'));b.rest.event={type:'single',index,choice:null};b.rest.eventDone=false;return EVENTS[index];}
void test('changing route, event and restoring a draft neither rerolls nor grants a reward',()=>{const b=rest(),event=cashEvent(b),gold=b.gold,shield=b.player.shield,coin=event.choices.findIndex(c=>c.effect==='gold'),ward=event.choices.findIndex(c=>c.effect==='shield');b.chooseInteraction(coin);b.chooseInteraction(ward);b.chooseInteraction(coin);assert.equal(b.gold,gold);assert.equal(b.player.shield,shield);b.chooseRoute(0);b.chooseRoute(1);const c=restore(b);assert.equal(c.rest.event.choice,coin);assert.equal(c.routes[0][1].selected,1);assert.deepEqual(c.rest.event,b.rest.event);const amount=c.rest.cashReserve;c.continueRest();assert.equal(c.gold,gold+amount);assert.equal(c.wave,1);c.continueRest();assert.equal(c.gold,gold+amount);});
void test('a changed healing choice never stacks healing while selecting',()=>{const b=rest(),index=EVENTS.findIndex(e=>e.choices.some(c=>c.effect==='heal'));b.rest.event={type:'single',index,choice:null};b.rest.eventDone=false;b.player.hp=20;const choice=EVENTS[index].choices.findIndex(c=>c.effect==='heal');for(let i=0;i<5;i++){b.chooseInteraction(choice);b.chooseInteraction(2);}b.chooseInteraction(choice);assert.equal(b.player.hp,20);b.chooseRoute(0);b.continueRest();assert.equal(b.player.hp,38);});
void test('core and skip can be changed repeatedly, including after reload, with one final award',()=>{let b=rest(true);cashEvent(b);const initial=b.rerolls;b.equipCore('K01');b.skipCore();b.equipCore('K02');assert.deepEqual(b.relics,[]);assert.equal(b.rerolls,initial);b=restore(b);b.skipCore();b.equipCore('K03');b.chooseInteraction(2);b.continueRest();assert.deepEqual(b.relics,['K03']);assert.equal(b.rerolls,initial);assert.equal(b.chapter,1);});
void test('skipped core adds one reroll only at departure',()=>{const b=rest(true);cashEvent(b);const initial=b.rerolls;b.skipCore();b.skipCore();assert.equal(b.rerolls,initial);b.chooseInteraction(2);b.continueRest();assert.equal(b.rerolls,initial+1);});
void test('queued insight choices keep the pending intermission editable until departure',()=>{const b=rest();cashEvent(b);b.chooseInteraction(2);b.chooseRoute(0);b.queuedChoices=1;b.continueRest();assert.equal(b.modeState,'choice');b.chooseTrait(b.choices[0].id);assert.equal(b.scene,'intermission');assert.equal(b.rest.eventApplied,false);assert.equal(b.chooseInteraction(0),true);assert.equal(b.chooseRoute(1),true);});
void test('changed equipment slot aborts final settlement without partially granting event money',()=>{const b=rest(true);cashEvent(b);b.relics=RELICS.filter(r=>!r.story).slice(0,6).map(r=>r.id);b.recalc();b.equipCore('K01',1);b.chooseInteraction(2);b.sell(1);const gold=b.gold,relics=[...b.relics];b.continueRest();assert.equal(b.scene,'intermission');assert.equal(b.gold,gold);assert.deepEqual(b.relics,relics);assert.equal(b.rest.eventApplied,false);assert.match(b.toastText,/位置已变化/);assert.equal(b.equipCore('K02'),true);b.continueRest();assert.equal(b.chapter,1);});
void test('old claimed rewards remain intact, while their undecided route can be changed',()=>{const b=rest();cashEvent(b);delete b.rest.selectionMode;delete b.rest.eventApplied;delete b.rest.coreApplied;delete b.rest.coreSelection;b.chooseInteraction(2);b.chooseRoute(0);const gold=b.gold,c=restore(b);assert.equal(c.rest.eventApplied,true);assert.equal(c.chooseInteraction(0),false);assert.equal(c.chooseRoute(1),true);assert.equal(c.gold,gold);c.continueRest();assert.equal(c.gold,gold);});
void test('an unclaimed intermission from an old snapshot gains draft choices',()=>{const b=rest();delete b.rest.selectionMode;delete b.rest.eventApplied;delete b.rest.coreApplied;delete b.rest.coreSelection;const c=restore(b);const gold=c.gold;c.chooseInteraction(2);c.chooseInteraction(0);assert.equal(c.rest.selectionMode,'draft');assert.equal(c.gold,gold);});
void test('invalid pending selections are rejected during save validation',()=>{for(const mutate of [r=>{r.eventDone=true;r.event.choice=999;},r=>{r.coreOffers=['K01'];r.coreDone=true;r.coreSelection={id:'K99',replaceId:null};}]){const b=rest();mutate(b.rest);assert.throws(()=>normalizeSave({...initialSave(),checkpoint:b.serialize()}));}});
void test('withdrawing a middle meta node refunds it and later nodes while preserving the run and other branches',()=>{const save={...initialSave(),insight:7,meta:['sword-meta-0','sword-meta-1','sword-meta-2','insect-meta-0'],checkpoint:{options:{meta:['sword-meta-0','sword-meta-1','sword-meta-2']}}};const before=structuredClone(save),plan=planMetaRefund(save,{path:0,fromStep:1});assert.equal(plan.refund,85);assert.equal(plan.save.insight,92);assert.deepEqual(plan.save.meta,['sword-meta-0','insect-meta-0']);assert.deepEqual(plan.save.checkpoint,save.checkpoint);assert.deepEqual(save,before);assert.equal(planMetaRefund(plan.save,{path:0,fromStep:1}).refund,0);});
void test('full respec refunds all unique learned nodes, leaving achievements and history intact',()=>{const save={...initialSave(),insight:10,meta:META.map(m=>m.id),achievements:['a'],history:[{won:true}]},plan=planMetaRefund(save);assert.equal(plan.refund,META.reduce((a,m)=>a+m.cost,0));assert.equal(plan.save.meta.length,0);assert.deepEqual(plan.save.achievements,['a']);assert.deepEqual(plan.save.history,save.history);assert.equal(planMetaRefund(plan.save).refund,0);});
void test('garden respec refunds research costs without erasing paid-run receipts or changing a current supply',()=>{const save={...initialSave(),garden:{...defaultGarden(),points:2,unlocked:['steady','heal','mana'],selected:'heal',receipts:['paid-run']},checkpoint:{options:{supply:'heal'}}},plan=planGardenRefund(save);assert.equal(plan.refund,6);assert.equal(plan.save.garden.points,8);assert.deepEqual(plan.save.garden.unlocked,['steady']);assert.equal(plan.save.garden.selected,'steady');assert.equal(plan.save.checkpoint.options.supply,'heal');assert.equal(settleGarden(plan.save.garden,{mode:'story',runId:'paid-run',research:6}).points,8);assert.equal(planGardenRefund(plan.save).refund,0);});

void test('settling a draft preserves unrelated combat clocks and random sequence',()=>{const b=rest();cashEvent(b);b.chooseInteraction(2);b.chooseRoute(0);b.time=130;b.id=987;b.lastChain=123;b.lastWard=125;const rng=b.rng.state(),content=b.contentRng.state();assert.equal(b.commitRestSelections(),true);assert.equal(b.id,987);assert.equal(b.lastChain,123);assert.equal(b.lastWard,125);assert.equal(b.rng.state(),rng);assert.equal(b.contentRng.state(),content);});
