/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {initialSave,META} from '../gameplay/data.js';import {SaveVault,normalizeSave,SAVE_KEY} from '../gameplay/save-store.js';import {capturePointer} from '../gameplay/pointer-input.js';import {starterDetails} from '../gameplay/starters.js';
const copy=x=>JSON.parse(JSON.stringify(x)),own=p=>META.filter(m=>m.path===p).map(m=>m.id);
function arena(path=0,meta=own(path)){const b=new Expedition({balanceVersion:2,metaRulesVersion:2,seed:'round3-tests',path,meta});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};b.player.x=640;b.player.y=400;b.player.invuln=0;return b;}
function shotSave(){const b=arena(2);b.spawn(1,{x:810,y:400,hp:1e6,spawn:0,speed:0});b.shoot(810,400,0,10,0,true);return copy(b.serialize());}
void test('invalid gnaw values are refused before they can corrupt enemy life',()=>{for(const value of ['abc',null,{},-1,.121,99,Infinity]){const d=shotSave();d.expedition.enemies[0].gnaw=value;d.expedition.enemies[0].gnawUntil=20;assert.throws(()=>normalizeSave({...initialSave(),checkpoint:d}),/虫群易伤/);}const d=shotSave();d.expedition.enemies[0].gnaw=.12;assert.equal(Expedition.restore(d).enemies[0].gnaw,.12);});
void test('projectile source, faction and suppression flags cannot use coercible strings',()=>{for(const [field,value] of [['source','constructor'],['source','__proto__'],['source','unknown'],['source',null],['source','enemy'],['friendly','false'],['metaPin','false'],['color',{}],['color','#12345']]){const d=shotSave();d.expedition.shots[0][field]=value;assert.throws(()=>Expedition.restore(d),/弹幕/);}const d=shotSave();d.expedition.shots[0].metaPin=false;assert.equal(Expedition.restore(d).shots[0].metaPin,false);});
void test('legacy arrows missing only source regain the actual faction source without mutating input',()=>{const d=shotSave();delete d.expedition.shots[0].source;const raw=JSON.stringify(d),b=Expedition.restore(d);assert.equal(b.shots[0].source,'puppet');assert.equal(JSON.stringify(d),raw);b.updateAllies=()=>{};b.updateSwords=()=>{};b.updateDirector=()=>{};b.updateEnvironment=()=>{};b.update(.01);assert.equal(b.damageSources.puppet,10);});
void test('guard and core timing/accumulation reject bad values but accept default negative sentinels',()=>{for(const field of ['lastCounter','shieldAbsorbed','lastShieldBreak','coreArcUntil','coreArcs','corePair'])for(const value of ['abc',null,1e300]){const d=shotSave();(field==='lastCounter'?d:d.expedition)[field]=value;assert.throws(()=>Expedition.restore(d),/计时|累计|次数|计数/);}const d=shotSave();d.lastCounter=-100;d.expedition.lastShieldBreak=-100;assert.equal(Expedition.restore(d).lastCounter,-100);});
void test('resource serialization rejects astronomical numbers and preserves earned extra shields',()=>{const d=shotSave();d.player.shield=1e199;assert.throws(()=>Expedition.restore(d),/角色资源/);d.player.shield=195;d.player.maxShield=0;const r=Expedition.restore(d);assert.equal(r.player.shield,195);assert.equal(r.player.maxShield,0);});
void test('rejected incoming records leave primary storage byte-for-byte unchanged',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},vault=new SaveVault(storage);vault.load();vault.commit({...initialSave(),insight:123,checkpoint:shotSave()});const raw=map.get(SAVE_KEY),d=shotSave();d.expedition.shots[0].source='constructor';assert.throws(()=>vault.commit({...initialSave(),checkpoint:d},{backup:true}),/弹幕来源/);assert.equal(map.get(SAVE_KEY),raw);assert.equal(vault.load().insight,123);});
void test('unknown runtime damage source cannot write an inherited Object property',()=>{const b=arena(),e=b.spawn(1,{hp:100});assert.throws(()=>b.hit(e,10,'constructor'),/伤害来源/);assert.equal(e.hp,100);assert.equal(Object.hasOwn(b.damageSources,'constructor'),false);});
void test('optional delayed zone payloads and movement directions are validated',()=>{for(const mutate of [d=>d.expedition.enemies[0].chargeA='abc',d=>d.expedition.enemies[0].guarded='abc',d=>d.expedition.zones[0].originalDamage='abc',d=>d.expedition.zones[0].friendly='false',d=>d.expedition.zones[0].slow=10]){const d=shotSave();d.expedition.zones=[{x:600,y:400,r:80,ttl:1,warn:.2,damage:50,sigil:true,friendly:true,ember:true,originalDamage:60}];mutate(d);assert.throws(()=>Expedition.restore(d),/无效/);}});
void test('K01 strikes only during actual return movement, at most once per launch',()=>{const b=arena(0,[]);b.relics=['K01'];b.recalc();b.spawn(1,{x:800,y:400,hp:1e6,spawn:0,speed:0});const hits=[],hit=b.hit.bind(b);b.hit=(e,d,s,c)=>{if(s==='sword'||s==='return')hits.push({source:s,time:b.time,x:b.swords[0].x,px:b.swords[0].px});return hit(e,d,s,c);};for(let i=0;i<600;i++)b.update(1/60);const returning=hits.filter(h=>h.source==='return');assert.ok(returning.length>0);assert.ok(returning.length<=hits.filter(h=>h.source==='sword').length);for(const h of returning){assert.ok(h.x<h.px,'the tested enemy is east, so return must move west');assert.ok(!hits.some(g=>g.source==='sword'&&g.time===h.time),'outgoing strike cannot share the return frame');}});
void test('a consumed return strike stays consumed through a live snapshot',()=>{const b=arena(0,[]);b.relics=['K01'];const e=b.spawn(1,{x:800,y:400,hp:1e6,spawn:0,speed:0});Object.assign(b.swords[0],{x:821,y:400,cool:1.05,returnReady:true});b.rebuildHash();b.updateSwords(.01);assert.ok(e.hp<1e6);assert.equal(b.swords[0].returnReady,false);const d=copy(b.serialize()),r=Expedition.restore(d),hp=r.enemies[0].hp;r.updateDirector=()=>{};r.updateEnvironment=()=>{};r.updateAllies=()=>{};for(let i=0;i<20;i++)r.update(.01);assert.equal(r.enemies[0].hp,hp);});
void test('a pending return resumes exactly once and may hit the outgoing target',()=>{const b=arena(0,[]);b.relics=['K01'];const e=b.spawn(1,{x:800,y:400,hp:1e6,spawn:0,speed:0});Object.assign(b.swords[0],{x:835,y:400,cool:1.05,returnReady:true,hits:[e.id]});const r=Expedition.restore(copy(b.serialize()));r.updateDirector=()=>{};r.updateEnvironment=()=>{};r.updateAllies=()=>{};for(let i=0;i<20;i++)r.update(.01);assert.ok(r.enemies[0].hp<1e6);assert.equal(r.swords[0].returnReady,false);assert.ok(r.damageSources.return>0);});
void test('return damage completing a node cannot keep hitting the old field',()=>{const b=arena(0,[]);b.relics=['K01'];b.objective={kind:'hunt',done:2,spawned:3};b.spawn(1,{x:800,y:400,hp:1,mission:'marked',spawn:0,speed:0});const other=b.spawn(1,{x:805,y:400,hp:1,spawn:0,speed:0});Object.assign(b.swords[0],{x:821,y:400,cool:1.05,returnReady:true});b.rebuildHash();b.updateSwords(.01);assert.equal(b.kills,1);assert.equal(other.hp,1);assert.equal(b.scene,'intermission');assert.equal(b.drops.length,0);});
void test('shielded insect bites consume their attack cooldown but grant no gnaw, break or mana',()=>{const b=arena(3),e=b.spawn(1,{x:680,y:400,hp:1e6,phaseShield:3,spawn:0,speed:0});b.stats.insectBreak=.1;b.stats.insectMana=1;b.player.mana=0;b.rebuildHash();b.updateAllies(.01);for(const bug of b.insects)Object.assign(bug,{x:e.x+12,y:e.y,cool:0});b.updateAllies(.01);assert.equal(e.hp,1e6);assert.equal(e.gnaw,undefined);assert.equal(e.break,0);assert.equal(b.player.mana,0);assert.ok(b.insects.every(i=>i.cool>0));e.phaseShield=0;for(const bug of b.insects)bug.cool=0;b.updateAllies(.01);assert.ok(e.hp<1e6&&e.gnaw>0&&e.break>0&&b.player.mana>0);});
void test('insect recovery shows only the actual heal, without accumulating full-health charges',()=>{for(const [hp,text] of [[100,null],[99,'+1'],[50,'+3']]){const b=arena(3);b.player.hp=hp;b.player.metaInsectKills=7;b.hit(b.spawn(1,{hp:1}),1000,'insect',false);assert.equal(b.player.hp,Math.min(100,hp+3));const numbers=b.fx.filter(f=>f.kind==='number'&&f.text.startsWith('+'));assert.deepEqual(numbers.map(f=>f.text),text?[text]:[]);assert.equal(b.player.metaInsectKills,8);}});
void test('thunder UI readiness uses the real cost including cultivation and the extra core cost',()=>{const b=arena(1);b.relics=['K03'];b.player.mana=100;b.player.reserve=25;assert.equal(b.thunderReadiness().cost,26);assert.equal(b.thunderReadiness().label,'雷源不足');assert.equal(b.thunder(),false);assert.equal(b.player.mana,100);b.player.reserve=26;assert.equal(b.thunderReadiness().ready,true);assert.equal(b.thunder(),true);assert.equal(b.player.reserve,0);});
void test('documented thunder control and guard veil still protect against persistent hazards',()=>{const damage=meta=>{const b=arena(1,meta);b.player.mana=100;b.danger(640,400,70,20,.45,1,'fire');b.thunder();for(let i=0;i<48;i++)b.update(1/60);return b.player.hp;};assert.equal(damage([]),80);assert.equal(damage(['thunder-meta-5']),100);const b=arena(1),e=b.spawn(1,{hp:1000,untargetable:true});b.player.mana=100;b.thunder();assert.equal(e.hp,1000);assert.equal(e.stun,1.1);});
void test('pointer capture ignores synthetic and expired IDs without queuing an action',()=>{let calls=0;assert.equal(capturePointer({isTrusted:false,currentTarget:{setPointerCapture(){calls++;}}}),false);assert.equal(calls,0);assert.equal(capturePointer({isTrusted:true,currentTarget:{setPointerCapture(){throw Error('expired');}}}),false);assert.equal(capturePointer({isTrusted:true,pointerId:5,currentTarget:{setPointerCapture(id){assert.equal(id,5);calls++;}}}),true);assert.equal(calls,1);});
void test('guard starting details include HP, armor and shield, while legacy rules remain distinct',()=>{const s=starterDetails(5,{metaRulesVersion:2,meta:own(5)});assert.match(s.initial,/生命 108/);assert.match(s.initial,/护甲 2/);assert.match(s.initial,/33 护盾/);const b=new Battle({path:5,rulesVersion:1});const r=Battle.restore(copy(b.serialize()));assert.equal(r.rulesVersion,1);assert.equal(r.options.metaRulesVersion,1);});
