/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';import assert from 'node:assert/strict';import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {TRAITS,META} from '../gameplay/data.js';import {sigilFuse} from '../gameplay/sigil-metrics.js';import {cultivationStatus} from '../gameplay/cultivation.js';import {starterStatus} from '../gameplay/starters.js';import {traitDescription} from '../gameplay/descriptions.js';
const copy=x=>JSON.parse(JSON.stringify(x)),own=path=>META.filter(m=>m.path===path).map(m=>m.id);
function arena(path=4,meta=[]){const b=new Expedition({metaRulesVersion:2,seed:'round6-test',balanceVersion:1,path,meta,difficulty:1});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.player.invuln=0;b.updateDirector=()=>{};b.updateEnvironment=()=>{};b.updateSwords=()=>{};b.updateAllies=()=>{};return b;}
function enemy(b,hp=20,opts={}){const e=b.spawn(4,{hp,spawn:0,noDrop:true,...opts});e.x=b.player.x+40;e.y=b.player.y;e.speed=0;b.rebuildHash();return e;}
function burst(b,z={}){b.zones.push({x:b.player.x,y:b.player.y,r:85,ttl:1,warn:0,fuseDuration:.8,kind:'sigil',friendly:true,sigil:true,damage:56.2,...z});b.update(.01);}
void test('guard revival records the actual recovery and only a later fatal hit is a defeat',()=>{const b=arena(5);b.traits[TRAITS.find(t=>t.mods.revive).id]=1;b.recalc();b.player.hp=1;b.player.shield=0;b.hitPlayer(10);assert.equal(b.player.hp,25);assert.equal(b.finished,false);assert.deepEqual(Object.fromEntries(['outcome','hp','remaining','recovered'].map(k=>[k,b.recentHits[0][k]])),{outcome:'revived',hp:1,remaining:25,recovered:25});const r=Expedition.restore(copy(b.serialize()));assert.equal(r.recentHits[0].outcome,'revived');r.player.invuln=0;r.hitPlayer(999);assert.equal(r.recentHits.at(-1).outcome,'defeated');assert.equal(r.recentHits.at(-1).recovered,0);});
void test('legacy zero-life records remain unspecified while impossible new revival records are refused',()=>{const b=arena();b.hitPlayer(10);const d=copy(b.serialize());d.recentHits[0].remaining=0;delete d.recentHits[0].outcome;delete d.recentHits[0].recovered;assert.equal(Expedition.restore(d).recentHits[0].outcome,undefined);d.recentHits[0].outcome='revived';d.recentHits[0].recovered=25;assert.throws(()=>Expedition.restore(d),/反馈/);});
void test('failed refresh preserves gold, shelf, RNG and revision; a real refresh saves once',()=>{const b=arena();b.completeNode();b.rest.shop=true;b.makeShop();b.gold=0;const before={s:copy(b.shop),rng:b.rng.state(),rev:b.revision};assert.equal(b.refreshShop(),false);assert.deepEqual(b.shop,before.s);assert.equal(b.rng.state(),before.rng);assert.equal(b.revision,before.rev);assert.match(b.toastText,/还缺 10/);b.gold=15;assert.equal(b.refreshShop(),true);assert.equal(b.gold,5);assert.equal(b.revision,before.rev+1);assert.equal(b.shopReadiness().missing,13);});
void test('thunder veil notification and active-state label end with the one-second effect',()=>{const b=arena(1,own(1));b.player.mana=100;b.thunder();assert.equal(b.combatCues.find(c=>c.key==='veil').until,1);assert.match(cultivationStatus(b),/1.0 秒/);for(let i=0;i<24;i++)b.update(.05);assert.equal(b.player.invuln,0);assert.ok(b.combatCues.filter(c=>c.until>b.time).every(c=>c.key!=='veil'));assert.match(cultivationStatus(b),/随神雷触发/);});
void test('temporary insects expire once, keep permanent allies and preserve pause semantics',()=>{const b=arena(3);b.updateAllies=Battle.prototype.updateAllies.bind(b);b.consumables=[{id:'insect',count:1}];b.consume(0);b.update(.01);assert.equal(b.insects.length,8);b.pause();b.update(.05);assert.equal(b.time,.01);b.resume();for(let i=0;i<501;i++)b.update(.05);assert.equal(b.insects.length,4);assert.equal(b.combatCues.filter(c=>c.key==='expire-insect').length,1);assert.match(b.combatCues.find(c=>c.key==='expire-insect').text,/结束/);});
void test('mana readiness labels reflect current source reserve and include the resource name',()=>{const a=arena(1);assert.match(a.thunderReadiness().label,/灵力/);a.player.mana=100;a.update(.01);assert.match(a.toastText,/可以施放/);const b=arena();b.player.mana=100;b.player.reserve=0;b.update(.01);assert.match(b.toastText,/雷源不足.*还缺 25/);});
void test('main sigil killing a target records a hit and a kill instead of an empty explosion',()=>{const b=arena();enemy(b);burst(b);assert.deepEqual(b.sigilStats.sigil,{casts:1,hits:1,kills:1,damage:20,blocked:0,empty:0});assert.match(b.combatCues.at(-1).text,/命中 1 · 击杀 1/);assert.equal(Expedition.restore(copy(b.serialize())).sigilStats.sigil.kills,1);});
void test('empty explosions and protected targets are distinct and use actual center-radius geometry',()=>{for(const opts of [{},{untargetable:true},{phaseShield:2}]){const b=arena();const e=enemy(b,1000,opts);if(!Object.keys(opts).length)e.x=b.player.x+90;burst(b);assert.equal(b.sigilStats.sigil.hits,0);assert.equal(b.sigilStats.sigil.empty,1);assert.equal(b.sigilStats.sigil.blocked,Object.keys(opts).length?1:0);}});
void test('last-target node completion saves the lethal sigil hit before the result changes scenes',()=>{const b=arena();enemy(b,20,{mission:'carrier',waypoint:0});let saved;b.emit=e=>{if(e.type==='checkpoint')saved=copy(e.checkpoint);};burst(b);assert.equal(b.scene,'intermission');assert.ok(saved);assert.equal(saved.sigilStats.sigil.kills,1);assert.equal(saved.sigilStats.sigil.empty,0);assert.equal(Expedition.restore(saved).sigilStats.sigil.hits,1);});
void test('normal sigils, echoes and K09 retain their rules while attribution stays separate',()=>{const b=arena(4,own(4));b.relics=['K09'];b.recalc();enemy(b,1000);b.dash();const z=b.zones[0];assert.equal(z.fuseDuration,.8);for(let i=0;i<28;i++)b.update(.05);assert.equal(b.sigilStats.sigil.casts,1);assert.equal(b.sigilStats.echo.casts,1);assert.equal(b.sigilStats.sigil.damage,b.fireBreakdown.sigil);assert.equal(b.sigilStats.echo.damage,b.fireBreakdown.echo);assert.ok(b.fireBreakdown.ember>0);});
void test('per-sigil countdown does not change when a later trait shortens future fuses',()=>{const b=arena();b.dash();const z=b.zones[0];b.traits['talisman-10']=1;b.recalc();assert.equal(sigilFuse(z,b.stats),.8);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.zones[0].fuseDuration,.8);assert.equal(r.zones[0].warn,.8);});
void test('legacy pending fuses migrate only their visual denominator, never remaining time',()=>{const b=arena();b.dash();const d=copy(b.serialize());delete d.expedition.zones[0].fuseDuration;d.traits['talisman-10']=1;const r=Expedition.restore(d);assert.equal(r.zones[0].warn,.8);assert.equal(r.zones[0].ttl,1.15);assert.equal(r.zones[0].fuseDuration,.8);});
void test('paired K10 sigils use their real eight-second wait and paired 0.8-second fuse',()=>{const b=arena();b.relics=['K10'];b.recalc();b.dash();assert.equal(b.zones[0].fuseDuration,8);for(let i=0;i<121;i++)b.update(.05);b.dash();assert.equal(b.zones.length,2);assert.ok(b.zones.every(z=>z.fuseDuration===.8&&z.warn===.8));assert.equal(Expedition.restore(copy(b.serialize())).zones[0].warn,.8);});
void test('missing old sigil metrics start at the restored time and never invent old casts',()=>{const b=arena();b.update(.05);const d=copy(b.serialize());delete d.sigilStats;const r=Expedition.restore(d);assert.equal(r.sigilStats.fromTime,.05);assert.equal(r.sigilStats.sigil.casts,0);});
void test('metrics retain at most forty bursts and reject corrupt totals and fuses',()=>{const b=arena();for(let i=0;i<45;i++)burst(b);assert.equal(b.sigilStats.recent.length,40);assert.equal(b.sigilStats.sigil.casts,45);for(const mutate of [d=>d.sigilStats.sigil.empty=46,d=>d.sigilStats.sigil.damage=999,d=>d.sigilStats.recent[0].id=999,d=>d.expedition.zones[0].fuseDuration=-1]){const d=copy(b.serialize());mutate(d);assert.throws(()=>Expedition.restore(d),/统计|引信/);}});
void test('focus window follows an actually hit target and all puppets expose their shot counters',()=>{const b=arena(0);const e=enemy(b,1000);b.hit(e,1,'sword',false);assert.match(starterStatus(b),/1\/4.*秒/);b.time=3;assert.match(starterStatus(b),/等待集火/);const p=arena(2,own(2));p.updateAllies=Battle.prototype.updateAllies.bind(p);p.updateAllies(.01);p.puppets[0].metaShots=2;p.puppets[1].metaShots=5;assert.match(cultivationStatus(p),/最近就绪 2号.*还差 1 箭/);p.pinCue();p.pinCue();assert.match(p.combatCues.find(c=>c.key==='pin').text,/2 次/);});
void test('sigil descriptions include the cultivated cooldown and the other-starter distinction',()=>{const t=TRAITS.find(t=>t.id==='talisman-10');assert.match(traitDescription(t,arena(4,own(4))),/5.4 秒/);assert.match(traitDescription(t,arena(0)),/非符阵.*闪避冷却/);});
