/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';import {Expedition} from '../gameplay/expedition.js';import {CINEMATICS} from '../gameplay/expedition-data.js';import {initialSave} from '../gameplay/data.js';import {setTouchAim,updateTouchLock,touchLockRange,touchSettings,clearTouchLock} from '../gameplay/touch-controls.js';import {completeRecordLoop,recordDetails,elapsedBattle} from '../gameplay/record-rules.js';import {emptyRecords,normalizeRecords,recordGroup,recordReceipt,withProgressRecord,settleRunResult,formatRecordTime} from '../gameplay/records.js';import {normalizeSave,SaveVault,SAVE_KEY,BACKUP_KEY} from '../gameplay/save-store.js';
const copy=structuredClone;
function arena(options={}){const b=new Expedition({segmentVersion:0,challengeVersion:0,seed:'phase5-tests',difficulty:1,...options});b.cinematicSeen=CINEMATICS.map(c=>c.id);b.beginNode();b.clearField();b.updateDirector=b.updateEnvironment=b.updateEnemy=()=>{};return b;}
function foe(b,x=800,extra={}){const e=b.spawn(4,{x,y:520,hp:100000,spawn:0,speed:0,...extra});b.rebuildHash();return e;}
function bad(d,mutate,re){const x=copy(d);mutate(x);const raw=JSON.stringify(x);assert.throws(()=>Expedition.restore(x),re);assert.equal(JSON.stringify(x),raw);}
function result(runId='result-a',options={}){const b=arena({...options,runId});b.chapter=5;b.wave=3;b.receipts=b.routes.flat().map(n=>n.id);b.time=120.125;b.kills=90;b.level=72;b.won=true;b.finished=true;return b;}
void test('M20 new touch options default to the original layout and locking off; invalid preferences do not alter key bindings',()=>{const s=initialSave();assert.deepEqual(touchSettings(s.settings),{joystickSide:'left',joystickSize:'standard',skillSide:'right',touchLock:false});const n=normalizeSave({...s,keymap:{dash:'ControlLeft'},settings:{...s.settings,joystickSide:'up',joystickSize:'huge',skillSide:42,touchLock:'yes'}});assert.deepEqual(touchSettings(n.settings),touchSettings(s.settings));assert.equal(n.keymap.dash,'ControlLeft');const b=arena();assert.equal(b.options.focusVersion,3);assert.equal(b.options.touchLockEnabled,false);assert.equal(b.options.touchLockUsed,false);});
void test('M20 old focus1/2 never acquires a touch lock even when the device preference is enabled',()=>{for(const focusVersion of [1,2]){const b=arena({focusVersion,settings:{touchLock:true}}),e=foe(b);setTouchAim(b,e);assert.equal(b.touchLockId,null);assert.deepEqual(b.input.aim,{x:e.x,y:e.y});assert.equal(b.options.focusVersion,focusVersion);assert.equal(b.options.touchLockEnabled,undefined);assert.equal(b.serialize().expedition.touchLockId,undefined);}});
void test('M20 opt-in tap follows a target while off mode and drag remain fixed points',()=>{const b=arena({settings:{touchLock:true}}),e=foe(b);setTouchAim(b,e);assert.equal(b.touchLockId,e.id);const fixed={...b.input.aim};e.x+=35;updateTouchLock(b);assert.equal(b.input.aim.x,e.x);assert.equal(b.options.touchLockUsed,true);setTouchAim(b,{x:600,y:300},{allowLock:false});assert.equal(b.touchLockId,null);e.x+=30;updateTouchLock(b);assert.deepEqual(b.input.aim,{x:600,y:300});const off=arena(),target=foe(off);setTouchAim(off,target);target.x+=20;updateTouchLock(off);assert.equal(off.touchLockId,null);assert.equal(off.input.aim.x,fixed.x);});
void test('M20 acquisition and release honor real grouped-orbit range, protected targets and fixed fallback coordinates',()=>{for(const formation of [0,1,2]){const b=arena({touchLockEnabled:true});b.formation=formation;b.level=72;b.swords=[];b.syncSwords();const r=touchLockRange(b),e=foe(b,b.player.x+r-1);setTouchAim(b,e);assert.equal(b.touchLockId,e.id);const aim={...b.input.aim};e.x=b.player.x+r;updateTouchLock(b);assert.equal(b.touchLockId,null);assert.deepEqual(b.input.aim,aim);assert.equal(b.input.focus,true);assert.ok(b.combatCues.some(c=>c.key==='touch-lock-release'));}for(const extra of [{untargetable:true},{phaseShield:1},{hp:0}]){const b=arena({touchLockEnabled:true}),e=foe(b,800,extra);setTouchAim(b,e);assert.equal(b.touchLockId,null);}});
void test('M20 a lost, dead or newly protected target releases once and does not redirect to another enemy',()=>{for(const mutate of [e=>e.hp=0,e=>e.untargetable=true,e=>e.phaseShield=1]){const b=arena({touchLockEnabled:true}),e=foe(b);foe(b,805);setTouchAim(b,e);const aim={...b.input.aim};mutate(e);updateTouchLock(b);assert.equal(b.touchLockId,null);assert.deepEqual(b.input.aim,aim);const cueCount=b.combatCues.length;updateTouchLock(b);assert.equal(b.combatCues.length,cueCount);}});
void test('M20 locking does not mutate RNG, in-flight sword targets, cooldowns, pierce or existing projectiles',()=>{const b=arena({touchLockEnabled:true}),a=foe(b),z=foe(b,900);const sw=b.swords[0];Object.assign(sw,{target:a,cool:.7,life:.8,pierce:2,hits:[7]});b.shoot(600,520,0,10,520,true);const before={rng:b.rng.state(),swords:b.swords.map(({target,...s})=>({...s,targetId:target?.id})),shots:copy(b.shots),range:b.stats.range};setTouchAim(b,z);updateTouchLock(b);assert.deepEqual({rng:b.rng.state(),swords:b.swords.map(({target,...s})=>({...s,targetId:target?.id})),shots:b.shots,range:b.stats.range},before);assert.equal(sw.target,a);});
void test('M20 snapshot saves only the valid target ID, restores it in battle and clears aim for pause, choices and scenes',()=>{const b=arena({touchLockEnabled:true}),e=foe(b);setTouchAim(b,e);const d=copy(b.serialize());assert.equal(d.expedition.touchLockId,e.id);assert.equal(d.input,undefined);const r=Expedition.restore(d);assert.equal(r.touchLockId,e.id);assert.equal(r.input.aim.x,e.x);r.pause();assert.equal(r.touchLockId,null);assert.equal(r.input.aim,null);r.resume();assert.equal(r.input.focus,false);setTouchAim(r,r.enemies[0]);r.queuedChoices=1;r.openChoices();assert.equal(r.touchLockId,null);assert.equal(r.serialize().expedition.touchLockId,null);for(const mutate of [d=>d.expedition.touchLockId=999999,d=>d.expedition.touchLockId='1',d=>delete d.expedition.touchLockId,d=>d.options.touchLockEnabled=false,d=>d.modeState='pause'])bad(d,mutate,/锁敌/);});
void test('M20 disabling lock is safe and the used flag remains sticky for score grouping',()=>{const b=arena({touchLockEnabled:true}),e=foe(b);setTouchAim(b,e);b.options.touchLockEnabled=false;updateTouchLock(b);assert.equal(b.touchLockId,null);assert.equal(b.input.aim,null);assert.equal(b.options.touchLockUsed,true);clearTouchLock(b,true);assert.equal(b.options.focusVersion,3);});
void test('M20 point targeting on default focus3 yields the same actual sword attack as focus2',()=>{const rows=[];for(const focusVersion of [2,3]){const b=arena({focusVersion});b.level=12;b.swords=[];b.syncSwords();const a=foe(b),z=foe(b,820);b.input={x:0,y:0,focus:true,touchAim:true,aim:{x:a.x,y:a.y}};for(let i=0;i<20;i++)b.update(.05);rows.push({a:a.hp,z:z.hp,rng:b.rng.state(),damage:b.damageSources,swords:b.swords.map(s=>[s.cool,s.pierce,s.hits])});}assert.deepEqual(rows[0],rows[1]);});
void test('M21 absent books remain empty and old history is not backfilled into a ranked record',()=>{const old=initialSave();delete old.records;old.history=[{time:42,kills:1,path:0,won:true}];const s=normalizeSave(old);assert.deepEqual(s.records,emptyRecords());assert.deepEqual(s.history,old.history);const b=arena({recordVersion:0});const d=b.serialize();delete d.options.recordVersion;const r=Expedition.restore(d);assert.equal(r.options.recordVersion,0);assert.equal(r.summary().recordDetails,null);});
void test('M21 replay clock excludes chapter preset time and paused updates add no battle time',()=>{const b=arena({mode:'replay',chapter:3});assert.equal(elapsedBattle(b),0);b.update(.05);assert.equal(recordDetails(b).battleMs,50);b.pause();b.update(10);assert.equal(recordDetails(b).battleMs,50);const r=Expedition.restore(copy(b.serialize()));assert.equal(recordDetails(r).battleMs,50);r.resume();r.update(.05);assert.equal(recordDetails(r).battleMs,100);assert.equal(recordDetails(r).eligibleStart,false);});
void test('M21 main bests replace only on improvement and keep mode, difficulty, path, rules and lock-use separate',()=>{let s=initialSave();const a=result();s=settleRunResult(s,a.summary());assert.equal(s.records.entries.length,1);assert.equal(s.records.entries[0].timeMs,120125);const slower=result('slower');slower.time=130;s=settleRunResult(s,slower.summary());assert.equal(s.records.entries[0].runId,'result-a');const faster=result('faster');faster.time=110;s=settleRunResult(s,faster.summary());assert.equal(s.records.entries[0].runId,'faster');for(const options of [{path:1},{difficulty:0},{mode:'seed'},{focusVersion:2},{touchLockEnabled:true}]){const b=result('separate-'+JSON.stringify(options),options);s=settleRunResult(s,b.summary());}assert.equal(s.records.entries.length,6);assert.equal(new Set(s.records.entries.map(recordGroup)).size,6);normalizeSave(s);});
void test('M21 duplicate result settlement cannot add scores, insight, research, runs, kills or history again',()=>{const b=result();b.research=6;const summary=b.summary(),s=settleRunResult(initialSave(),summary),raw=JSON.stringify(s);assert.equal(s.runs,1);assert.equal(s.garden.points,6);assert.equal(settleRunResult(s,summary),s);assert.equal(JSON.stringify(settleRunResult(s,summary)),raw);assert.equal(s.records.receipts.filter(x=>x===recordReceipt(b.runId,'finish')).length,1);});
void test('M21 historical run IDs already present in the profile cannot be cashed again',()=>{const b=result('historical'),summary=b.summary(),s=initialSave();s.history=[summary];assert.equal(settleRunResult(s,summary),s);const garden=initialSave();garden.garden={points:6,unlocked:['steady'],selected:'steady',research:'mana',receipts:['historical']};assert.equal(settleRunResult(garden,summary),garden);});
void test('M21 failed main runs and replay/training never enter best-time rankings',()=>{for(const mode of ['story','seed','replay','training']){const b=result('exclude-'+mode,{mode});if(['story','seed'].includes(mode))b.won=false;const s=settleRunResult(initialSave(),b.summary());assert.equal(s.records.entries.length,0);assert.equal(s.runs,mode==='training'?0:1);}});
void test('M21 endless records count completed loops and use completion time rather than later failure time',()=>{const b=result('endless-a',{mode:'endless'});b.won=false;completeRecordLoop(b);const summary=b.summary();let s=withProgressRecord(initialSave(),summary);assert.equal(s.records.entries[0].loops,1);assert.equal(s.records.entries[0].timeMs,120125);assert.equal(s.runs,0);assert.equal(s.insight,0);const raw=JSON.stringify(s);s=withProgressRecord(s,summary);assert.equal(JSON.stringify(s),raw);b.endlessLoop=1;b.time=260;completeRecordLoop(b);s=withProgressRecord(s,b.summary());assert.equal(s.records.entries[0].loops,2);b.time=300;s=settleRunResult(s,b.summary());assert.equal(s.records.entries[0].timeMs,260000);assert.equal(s.runs,1);assert.equal(s.records.receipts.length,3);normalizeSave(s);});
void test('M21 an unfinished first endless loop does not manufacture a completed-loop record',()=>{const b=arena({mode:'endless'});b.time=80;b.won=false;const s=settleRunResult(initialSave(),b.summary());assert.equal(s.records.entries.length,0);assert.equal(s.records.receipts.length,1);});
void test('M21 switching lock after a completed loop does not retroactively change that loop category',()=>{const b=result('endless-switch',{mode:'endless'});b.won=false;completeRecordLoop(b);assert.equal(b.recordState.lastLoopLockUsed,false);b.options.touchLockEnabled=true;b.options.touchLockUsed=true;const s=withProgressRecord(initialSave(),b.summary());assert.equal(s.records.entries[0].touchLockUsed,false);});
void test('M21 record snapshot guards reject missing clocks, time travel, impossible loops and unknown versions without changing input',()=>{const b=arena();for(const mutate of [d=>delete d.expedition.recordState,d=>d.expedition.recordState.startedAt=d.time+1,d=>d.expedition.recordState.startedAt='0',d=>d.expedition.recordState.completedLoops=1,d=>d.options.recordVersion=2])bad(b.serialize(),mutate,/成绩/);});
void test('M21 malformed records cannot replace profile data; duplicate groups and receipts are rejected',()=>{const s=settleRunResult(initialSave(),result().summary());for(const mutate of [x=>x.schema=2,x=>x.receipts.push(x.receipts[0]),x=>x.entries.push(copy(x.entries[0])),x=>x.entries[0].timeMs=-1,x=>x.entries[0].difficulty=3,x=>x.entries[0].rules.focusVersion='3',x=>x.receipts=[]]){const x=copy(s.records);mutate(x);const raw=JSON.stringify(x);assert.throws(()=>normalizeRecords(x),/成绩/);assert.equal(JSON.stringify(x),raw);}});
void test('M21 record writes honor backup, write-failure protection and exact-once retry',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};map.set(SAVE_KEY,JSON.stringify(initialSave()));const vault=new SaveVault(storage),s=vault.load(),raw=map.get(SAVE_KEY),next=settleRunResult(s,result().summary()),write=storage.setItem;storage.setItem=(k,v)=>{if(k===SAVE_KEY)throw Error('quota');write(k,v);};assert.throws(()=>vault.commit(next,{backup:true}));assert.equal(map.get(SAVE_KEY),raw);storage.setItem=write;const saved=vault.commit(next,{backup:true});assert.equal(JSON.parse(map.get(BACKUP_KEY)).raw,raw);assert.equal(saved.records.entries.length,1);assert.equal(settleRunResult(saved,result().summary()),saved);});
void test('M21 time formatting distinguishes an absent metric from zero',()=>{assert.equal(formatRecordTime(null),'未记录');assert.equal(formatRecordTime(0),'00:00.0');assert.equal(formatRecordTime(120125),'02:00.1');});

void test('M21 real complete-node and loop transitions persist two finished circles without paying result rewards twice',()=>{let save=initialSave();const b=new Expedition({segmentVersion:0,challengeVersion:0,mode:'endless',seed:'two-loop-records',runId:'two-loop-fixed'});b.emit=e=>{if(e.type==='checkpoint')save=normalizeSave({...withProgressRecord(save,b.summary()),checkpoint:e.checkpoint});if(e.type==='finish')save=normalizeSave(settleRunResult(save,e.summary));};for(let guard=0;guard<1000&&b.endlessLoop!==2;guard++){if(b.scene==='cinematic')b.advanceCinematic(true);else if(b.modeState==='intro')b.start();else if(b.modeState==='battle'){b.time+=2;b.waveTime+=2;b.completeNode();}else if(b.modeState==='choice')b.chooseTrait(b.choices[0].id);else if(b.scene==='intermission'){if(!b.rest.eventDone)b.chooseInteraction(b.eventText().choices.length-1);if(!b.rest.coreDone)b.skipCore();if(!b.rest.routeDone)b.chooseRoute(0);b.continueRest();}}assert.equal(b.endlessLoop,2);assert.equal(save.records.entries[0].loops,2);assert.equal(save.runs,0);assert.equal(save.records.receipts.length,2);const at=save.records.entries[0].timeMs;b.time+=10;b.finish(false);assert.equal(save.records.entries[0].timeMs,at);assert.equal(save.runs,1);const raw=JSON.stringify(save);save=settleRunResult(save,b.summary());assert.equal(JSON.stringify(save),raw);});

void test('M21 corrupt optional records have an explicit recovery plan that preserves a valid battle and original bytes',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},checkpoint=arena().serialize(),input={...initialSave(),insight:123,checkpoint,records:{schema:99}};const raw=JSON.stringify(input);map.set(SAVE_KEY,raw);const vault=new SaveVault(storage);assert.throws(()=>vault.load());const plan=vault.profileRecoveryPlan();assert.deepEqual(plan.discarded,['records']);assert.equal(plan.save.insight,123);assert.deepEqual(plan.save.checkpoint,checkpoint);assert.equal(map.get(SAVE_KEY),raw);vault.commit(plan.save,{backup:true,allowCorrupt:true});assert.equal(vault.rawRecords().some(r=>r.raw===raw),true);assert.deepEqual(vault.load().checkpoint,checkpoint);});
