/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';import {Expedition} from '../gameplay/expedition.js';import {TRAITS,ENEMIES,initialSave} from '../gameplay/data.js';import {traitReadiness} from '../gameplay/growth-rules.js';import {ordinaryLimit,budgetSpawns,clearing} from '../gameplay/director-rules.js';import {normalizeSave} from '../gameplay/save-store.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function run(options={}){const b=new Expedition({seed:'phase2',growthVersion:3,encounterVersion:3,economyVersion:2,...options});b.cinematicSeen=['bamboo','ruins','yuanyao','treasure','cauldron','ending'];b.beginNode();return b;}
function fixture(kind,variant=0,options={}){for(let seed=0;seed<100;seed++){const b=new Expedition({seed:'p2-kind-'+seed,growthVersion:3,encounterVersion:3,economyVersion:2,...options});for(let c=0;c<6;c++)for(let w=0;w<b.routes[c].length;w++){const i=b.routes[c][w].choices.findIndex(e=>e.kind===kind&&e.variant===variant);if(i<0)continue;b.chapter=c;b.wave=w;b.node.selected=i;b.beginNode();return b;}}throw Error(kind);}
const trait=id=>TRAITS.find(t=>t.id===id);
for(let path=0;path<6;path++)void test('M11 first offer is effective, unique and on-path, path '+path,()=>{for(let seed=0;seed<50;seed++){const b=run({path,seed:'offer-'+seed});b.queuedChoices=1;b.openChoices();assert.equal(b.choices.length,3);assert.equal(new Set(b.choices.map(t=>t.id)).size,3);assert.ok(b.choices.some(t=>t.path===path));for(const t of b.choices)assert.ok(traitReadiness(t,b).eligible);const before=JSON.stringify(b.serialize()),copy=Expedition.restore(JSON.parse(before));assert.deepEqual(copy.choices,b.choices);assert.equal(copy.growth.firstOfferUsed,true);assert.equal(JSON.stringify(b.serialize()),before);}});
void test('M11 dependency filtering preserves cross-path entry, mixed bonuses and mark activation',()=>{const b=run();for(const id of ['puppet-1','puppet-5','insect-1','talisman-1','talisman-6','talisman-8','guard-8','sword-11'])assert.equal(traitReadiness(trait(id),b).eligible,false,id);for(const id of ['puppet-0','insect-0','talisman-0','puppet-4','puppet-8','insect-9'])assert.equal(traitReadiness(trait(id),b).eligible,true,id);b.player.buffs.puppet=100;b.player.buffs.insect=100;assert.equal(traitReadiness(trait('puppet-1'),b).eligible,false);assert.equal(traitReadiness(trait('insect-1'),b).eligible,false);b.traits['puppet-0']=1;b.traits['talisman-0']=1;b.recalc();assert.equal(traitReadiness(trait('puppet-1'),b).eligible,true);assert.equal(traitReadiness(trait('talisman-1'),b).eligible,true);assert.equal(traitReadiness(trait('puppet-11'),b).eligible,false);b.traits['thunder-5']=1;b.recalc();assert.equal(traitReadiness(trait('puppet-11'),b).eligible,true);});
void test('M11 caps, small pools and empty pools do not consume rerolls or strand choices',()=>{const b=run();b.stats.thunderSave=17;b.stats.crit=.8;b.stats.dashHaste=.65;for(const id of ['thunder-2','sword-3','guard-5'])assert.equal(traitReadiness(trait(id),b).eligible,false);for(const t of TRAITS)b.traits[t.id]=t.max;b.traits['sword-0']=2;b.recalc();b.queuedChoices=3;b.openChoices();assert.deepEqual(b.choices.map(t=>t.id),['sword-0']);b.chooseTrait('sword-0');assert.equal(b.queuedChoices,0);assert.equal(b.modeState,'battle');const count=b.rerolls;b.openChoices();assert.equal(b.modeState,'battle');assert.equal(b.rerolls,count);});
function kill(b,type=1,opts={}){const e=b.spawn(type,{x:900,y:400,...opts});assert.ok(e);e.hp=0;b.kill(e);b.enemies=b.enemies.filter(e=>e.hp>0);return e;}
void test('M12 performance survives base top-up, collection, merging, restore and repeated settlement',()=>{const b=run();b.chapter=2;b.wave=0;b.node.selected=0;b.beginNode();assert.equal(b.node.xp,400);b.clearField();for(let i=0;i<61;i++)kill(b);b.collectAll();near(b.growth.ledger.baseCollected,288);near(b.growth.ledger.bonusCollected,40);const before=b.totalXP;b.completeNode();near(b.totalXP,440);near(b.totalXP-before,112);const copy=Expedition.restore(b.serialize());copy.completeNode();near(copy.totalXP,440);assert.equal(copy.growth.settlements.length,1);assert.equal(copy.rest.growthReward.total,440);});
void test('M12 reward allocation is immutable and zero-valued XP gems stop at both caps',()=>{const b=run();b.clearField();const e=kill(b);const drop=b.drops[0],value=drop.value;b.collectDrop(drop);b.collectDrop(drop);near(b.growth.ledger.baseCollected,value);b.drops=b.drops.filter(d=>!d.done);b.kill(e);near(b.growth.ledger.rawKillXP,value);for(let i=0;i<180;i++)kill(b);assert.ok(b.drops.every(d=>d.value>0||d.heal>0));near(b.growth.ledger.bonusAllocated,20);b.collectAll();b.completeNode();near(b.totalXP,100);normalizeSave({...initialSave(),checkpoint:b.serialize()});});
void test('M12 merged drops keep both XP parts and healing; runes do not add performance weight',()=>{const b=run();b.clearField();for(let i=0;i<80;i++)kill(b);const base=b.growth.ledger.baseAllocated,bonus=b.growth.ledger.bonusAllocated;const medical={x:640,y:500,life:0,value:0,gold:0,heal:8,xpBase:0,xpBonus:0};b.drops.push(medical);b.drops=[b.mergeDrops(b.drops)];b.player.hp=20;b.collectAll();near(b.growth.ledger.baseCollected,base);near(b.growth.ledger.bonusCollected,bonus);assert.ok(b.player.hp>=28);const c=fixture('break');const rune=c.enemies.find(e=>e.mission==='rune'&&e.runeIndex===0);c.kill(rune);near(c.growth.ledger.rawKillXP,0);near(c.growth.ledger.bonusAllocated,0);assert.ok(c.growth.ledger.baseCollected>0);});
void test('M12 forged XP parts, missing ledgers and duplicate receipts are refused without altering input',()=>{const b=run();b.clearField();for(let i=0;i<40;i++)kill(b);const raw=b.serialize();for(const mutate of [d=>delete d.expedition.growth,d=>d.expedition.drops[0].xpBonus=900,d=>d.expedition.growth.ledger.bonusCollected=9]){const d=structuredClone(raw);mutate(d);const before=JSON.stringify(d);assert.throws(()=>Expedition.restore(d),/经验|成长|额度/);assert.equal(JSON.stringify(d),before);}b.completeNode();const d=b.serialize();d.expedition.growth.settlements.push({...d.expedition.growth.settlements[0]});assert.throws(()=>Expedition.restore(d),/凭据/);});
void test('M13 insufficient budget preserves selected type and consumes no repeated draw',()=>{const b=run();b.clearField();b.directorState.pendingType=7;b.spawnBudget=1;const rng=b.rng.state();budgetSpawns(b,0,.01,180,()=>({x:900,y:500}));assert.equal(b.directorState.pendingType,7);assert.equal(b.rng.state(),rng);assert.equal(b.enemies.length,0);const copy=Expedition.restore(b.serialize());assert.equal(copy.directorState.pendingType,7);b.spawnBudget=3;budgetSpawns(b,0,.01,180,()=>({x:900,y:500}));assert.equal(b.enemies[0].index,7);near(b.spawnBudget,0);});
void test('M13 costly enemies appear through the ordinary channel; budget and frame work stay bounded',()=>{const b=run();b.chapter=4;b.wave=0;b.node.selected=0;b.beginNode();b.options.encounterVersion=1;b.pursuitState=null;b.clearField();const counts={};for(let i=0;i<30000;i++){budgetSpawns(b,3,.05,180,()=>({x:900,y:500}));for(const e of b.enemies)counts[e.index]=(counts[e.index]||0)+1;b.enemies=[];}for(const type of b.enemyPool())assert.ok(counts[type]>0,`${ENEMIES[type].name}: ${counts[type]}`);b.spawnBudget=100;budgetSpawns(b,0,.01,180,()=>({x:900,y:500}));assert.ok(b.enemies.length<=4);assert.ok(b.spawnBudget<=10);});
for(const kind of ['escape','break','hunt','pursuit'])for(let variant=0;variant<3;variant++)void test('M14 '+kind+'/'+variant+' stops all ordinary reinforcements but still permits required targets',()=>{const b=fixture(kind,variant);const needed=b.enemies.filter(e=>e.mission).length;for(let i=0;i<200;i++)b.spawn(0);assert.equal(b.enemies.filter(e=>!e.mission).length,ordinaryLimit(b));b.time=b.waveTime=b.pursuitState.deadline;b.updateDirector(0);assert.ok(clearing(b));assert.equal(b.pursuitState.phase,'clearing');assert.equal(b.spawnBudget,0);assert.equal(b.spawn(0,{noDrop:true}),null);assert.equal(b.spawn(3,{elite:true}),null);assert.ok(b.enemies.filter(e=>e.mission).length>=needed);assert.equal(b.modeState,'battle');if(kind==='hunt'){b.objective.spawned=2;b.spawnMarked();assert.equal(b.objective.spawned,3);}if(kind==='escape'||kind==='break'){b.spawnRuneGuard();assert.ok(b.objective.guard);}assert.match(b.objectiveText(),/追兵已尽/);normalizeSave({...initialSave(),checkpoint:b.serialize()});});
void test('new state cannot silently appear in old-rule saves; missing markers retain original rules',()=>{const b=run({growthVersion:1,contentVersion:2,encounterVersion:1}),d=b.serialize();delete d.options.growthVersion;delete d.options.encounterVersion;const old=Expedition.restore(d);assert.equal(old.options.growthVersion,1);assert.equal(old.options.encounterVersion,1);assert.equal(old.options.contentVersion,2);assert.equal(old.growth,null);for(const key of ['growthVersion','encounterVersion','contentVersion']){const bad=run().serialize();bad.options[key]=99;assert.throws(()=>Expedition.restore(bad),/版本/);}});
for(const kind of ['escape','break','hunt','pursuit'])for(let variant=0;variant<3;variant++)void test('M14 '+kind+'/'+variant+' can finish required objectives after clearing',()=>{const b=fixture(kind,variant);b.time=b.waveTime=b.pursuitState.deadline;b.updateDirector(0);for(let step=0;step<24&&b.modeState==='battle';step++){b.time+=8;b.waveTime+=8;b.updateDirector(0);b.rebuildHash();for(const e of b.enemies.slice())if(e.mission&&!e.untargetable&&e.hp>0){b.hit(e,1e9,'thunder',false);if(b.modeState!=='battle')break;}b.enemies=b.enemies.filter(e=>e.hp>0);if(kind==='escape'&&b.objective?.done===2){b.player.x=b.objective.exit.x;b.player.y=b.objective.exit.y;b.updateDirector(0);}}assert.equal(b.scene,'intermission');assert.equal(b.receipts.length,1);normalizeSave({...initialSave(),checkpoint:b.serialize()});});
void test('M14 entering clearing checkpoints once at the end of the update and survives reload',()=>{const b=fixture('escape'),snapshots=[];b.emit=e=>{if(e.type==='checkpoint')snapshots.push(e.checkpoint);};b.time=b.waveTime=b.pursuitState.deadline-.01;b.update(.02);assert.equal(snapshots.length,1);assert.equal(snapshots[0].expedition.pursuitState.phase,'clearing');const c=Expedition.restore(snapshots[0]);for(let i=0;i<5;i++)b.update(.02);assert.equal(snapshots.length,1);assert.equal(c.spawn(0),null);});
void test('M11 existing gear and other branches also satisfy independent effects and cap lightning shields',()=>{const b=run();b.relics=['kit-4-3','kit-5-4','kit-3-2'];b.recalc();for(const id of ['talisman-4','guard-7','thunder-5'])assert.equal(traitReadiness(trait(id),b).eligible,false,id);b.relics=[];b.traits={'thunder-6':2};b.recalc();assert.equal(traitReadiness(trait('thunder-6'),b).eligible,false);b.traits['guard-1']=1;b.recalc();assert.equal(traitReadiness(trait('thunder-6'),b).eligible,true);});
void test('missing or string-valued deadlines and reward summaries never masquerade as matching numbers',()=>{const b=fixture('escape');for(const value of [undefined,'130']){const d=b.serialize();d.expedition.pursuitState.deadline=value;assert.throws(()=>Expedition.restore(d),/截止/);}const c=run();c.completeNode();for(const mutate of [d=>delete d.expedition.growth.settlements[0].base,d=>d.expedition.rest.growthReward.total='80',d=>delete d.expedition.rest.growthReward.performance]){const d=structuredClone(c.serialize());mutate(d);assert.throws(()=>Expedition.restore(d),/经验/);}});
void test('new growth also validates a combat choice temporarily covered by a replay cinematic',()=>{const b=run();b.queuedChoices=1;b.openChoices();b.playCinematic('bamboo','rest',true);Expedition.restore(b.serialize());const d=b.serialize();d.expedition.growth.ledger=null;assert.throws(()=>Expedition.restore(d),/经验账本/);const e=b.serialize();e.expedition.growth.firstOfferUsed=false;assert.throws(()=>Expedition.restore(e),/悟道状态/);});
