/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {SaveVault,SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY} from '../gameplay/save-store.js';
import {initialSave} from '../gameplay/data.js';
import {Expedition} from '../gameplay/expedition.js';
const memory=()=>{const map=new Map();return {map,getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
const old=()=>({...initialSave(),insight:420,kills:98765,best:72});
for(const journal of ['{{bad','{}','null','{"key":"future"}','{"before":42}','{"before":null}','{"key":'])void test('M01 invalid journal stays exportable while primary remains readable: '+journal,()=>{
 const s=memory(),raw=JSON.stringify(old());s.setItem(SAVE_KEY,raw);s.setItem(JOURNAL_KEY,journal);const v=new SaveVault(s),profile=v.load(),before=[...s.map];assert.equal(profile.insight,420);assert.ok(v.recoveryIssue);assert.deepEqual([...s.map],before);assert.throws(()=>v.commit(profile),e=>e.code==='recovery');
 const saved=v.resolveRecovery(profile);assert.equal(saved.insight,420);assert.equal(v.recoveryIssue,null);assert.ok(v.rawRecords().some(r=>JSON.parse(r.raw).pendingBackup===journal));assert.equal(new SaveVault(s).load().kills,98765);
});
for(const primary of [null,''])void test('M02 orphaned backup survives three confirmed new saves: '+primary,()=>{
 const s=memory();if(primary!==null)s.setItem(SAVE_KEY,primary);s.setItem(BACKUP_KEY,JSON.stringify({raw:JSON.stringify(old()),savedAt:1}));const v=new SaveVault(s);try{v.load();}catch(e){assert.equal(e.code,'invalid');}assert.ok(v.recoveryIssue);assert.equal(v.backup().save.insight,420);assert.throws(()=>v.commit(initialSave(),{backup:true,allowCorrupt:true}),e=>e.code==='recovery');v.resolveRecovery(initialSave());for(let i=0;i<3;i++)v.commit(initialSave(),{backup:true});assert.ok(v.recoveryCandidates().some(c=>c.label==='受保护的旧备份'&&c.save.insight===420));
});
for(const failKey of [RAW_BACKUP_KEY,JOURNAL_KEY,BACKUP_KEY,SAVE_KEY])void test('M01 recovery interruptions retain an independently recoverable previous state: '+failKey,()=>{
 const s=memory(),raw=JSON.stringify(old()),backup=JSON.stringify({raw:JSON.stringify({...old(),insight:321}),savedAt:1});s.setItem(SAVE_KEY,raw);s.setItem(BACKUP_KEY,backup);s.setItem(JOURNAL_KEY,'bad');const v=new SaveVault(s),value=v.load(),write=s.setItem,remove=s.removeItem;
 s.setItem=(k,x)=>{if(k===failKey)throw Error('quota');write(k,x);};s.removeItem=k=>{if(k===failKey)throw Error('blocked');remove(k);};assert.throws(()=>v.resolveRecovery({...value,insight:999}));assert.equal(s.getItem(SAVE_KEY),raw);
 s.setItem=write;s.removeItem=remove;const records=v.rawRecords();assert.ok(s.getItem(JOURNAL_KEY)==='bad'||records.some(r=>JSON.parse(r.raw).pendingBackup==='bad'));assert.ok(s.getItem(BACKUP_KEY)===backup||records.some(r=>JSON.parse(r.raw).backup===backup));
});
void test('M01 recovery rejects another window changing any protected input',()=>{const s=memory();s.setItem(SAVE_KEY,JSON.stringify(old()));s.setItem(JOURNAL_KEY,'bad');const v=new SaveVault(s),p=v.load();s.setItem(BACKUP_KEY,'newer');const before=[...s.map];assert.throws(()=>v.resolveRecovery(p),e=>e.code==='conflict');assert.deepEqual([...s.map],before);});
void test('M01 multiple recoveries keep earlier preserved histories',()=>{const s=memory();s.setItem(SAVE_KEY,JSON.stringify(old()));const v=new SaveVault(s);for(const j of ['bad-a','bad-b']){s.setItem(JOURNAL_KEY,j);const p=v.load();v.resolveRecovery(p);}assert.equal(v.rawRecords().length,2);assert.deepEqual(v.rawRecords().map(r=>JSON.parse(r.raw).pendingBackup),['bad-a','bad-b']);});
function battle(inputVersion=2){const b=new Expedition({seed:'r10-input',inputVersion,mode:'training'});b.cinematicSeen=['bamboo'];b.beginNode();b.updateDirector=()=>{};b.updateEnvironment=()=>{};return b;}
for(const seconds of [.06,.12,.2])void test('M07 only buffers a dash within 120ms: '+seconds,()=>{const b=battle(),events=[];b.emit=e=>events.push(e);b.player.dashCD=seconds;const last=b.player.lastDash;b.requestDash();for(let i=0;i<20;i++)b.update(.01);assert.equal(events.filter(e=>e.type==='sound'&&e.name==='dash').length,seconds<=.12?1:0);if(seconds>.12)assert.equal(b.player.lastDash,last);});
void test('M07 one intent uses execution direction and clears on pause, choice and scene transitions',()=>{for(const interrupt of [b=>b.pause(),b=>b.openChoices(),b=>b.showScene('intermission')]){const b=battle();b.player.dashCD=.1;b.requestDash();b.requestDash();interrupt(b);assert.equal(b.dashIntent,null);}
 const b=battle();b.player.dashCD=.06;b.input.x=1;b.requestDash();b.input.x=0;b.input.y=-1;for(let i=0;i<8;i++)b.update(.01);assert.equal(b.player.dx,0);assert.equal(b.player.dy,-1);assert.equal(b.dashIntent,null);
});
void test('M07 old runs have original input timing, and pending input is not serialized',()=>{const b=battle(1);b.player.dashCD=.08;b.requestDash();assert.ok(!b.dashIntent);const next=battle();next.player.dashCD=.08;next.requestDash();const snap=next.serialize();assert.ok(!('dashIntent' in snap));const restored=Expedition.restore(snap);assert.equal(restored.options.inputVersion,2);assert.ok(!restored.dashIntent);delete snap.options.inputVersion;assert.equal(Expedition.restore(snap).options.inputVersion,1);snap.options.inputVersion=99;assert.throws(()=>Expedition.restore(snap),/输入规则版本/);});
void test('M01 valid stale journal still rolls back before deciding orphan recovery',()=>{const s=memory(),before=JSON.stringify({raw:JSON.stringify(old()),savedAt:1});s.setItem(BACKUP_KEY,'temporary');s.setItem(JOURNAL_KEY,JSON.stringify({key:BACKUP_KEY,before,after:'temporary',primaryAfter:'new-primary',createdAt:0}));const v=new SaveVault(s);v.load();assert.equal(s.getItem(BACKUP_KEY),before);assert.equal(s.getItem(JOURNAL_KEY),null);assert.ok(v.recoveryIssue);assert.equal(v.backup().save.insight,420);});
void test('M08 defend cue only responds to actual objective hits while focus is active and is throttled',()=>{const b=battle();b.objective={kind:'defend',hp:360,maxHp:360,invuln:0,x:640,y:360};b.time=10;b.input.focus=false;b.hitObjective(10);assert.ok(!b.defendAlertUntil);b.input.focus=true;b.objective.invuln=0;b.hitObjective(10);assert.equal(b.defendAlertUntil,13);const next=b.defendHintAt;b.time=11;b.objective.invuln=0;b.hitObjective(10);assert.equal(b.defendHintAt,next);assert.equal(b.input.focus,true);});
void test('M10 blocked hits emit no success audio; repeated kills and hits never change RNG through feedback',()=>{const b=battle(),events=[];b.emit=e=>events.push(e);const state=b.rng.state();b.feedbackSound('kill',.1);b.feedbackSound('kill',.1);assert.equal(events.length,1);assert.equal(b.rng.state(),state);const e=b.spawn(0,{x:700,y:400,hp:100});e.untargetable=true;events.length=0;b.hit(e,20,'guard',false);assert.equal(events.filter(e=>e.type==='sound').length,0);});
void test('M10 same-target dense critical hits show their effective total and count',()=>{const b=battle(),e=b.spawn(0,{x:700,y:400,hp:100000});b.rng=()=>0;b.stats.crit=1;b.fx=[];for(let i=0;i<6;i++)b.hit(e,10,'sword',true);const numbers=b.fx.filter(f=>f.critical);assert.equal(numbers.length,1);assert.equal(numbers[0].count,6);assert.match(numbers[0].text,/暴击合计.*6次/);assert.equal(numbers[0].total,b.damageSources.sword);});
void test('M01 inspecting a changed journal never authorizes overwriting another window primary',()=>{const s=memory();s.setItem(SAVE_KEY,JSON.stringify(old()));const v=new SaveVault(s);v.load();s.setItem(SAVE_KEY,JSON.stringify({...old(),insight:777}));s.setItem(JOURNAL_KEY,'broken later');v.inspectRecovery();const before=[...s.map];assert.throws(()=>v.resolveRecovery(old()),e=>e.code==='conflict');assert.deepEqual([...s.map],before);});
