/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';import {Expedition} from '../gameplay/expedition.js';import {Battle} from '../gameplay/engine.js';import {META,initialSave,CONSUMABLES} from '../gameplay/data.js';import {normalizeSave,SaveVault,SAVE_KEY,BACKUP_KEY} from '../gameplay/save-store.js';import {applyBalanceExperiment,prepareSnapshotTrial} from '../scripts/balance-experiments.mjs';import {applySlow} from '../gameplay/slow.js';
const copy=x=>JSON.parse(JSON.stringify(x)),own=p=>META.filter(m=>m.path===p).map(m=>m.id);
function arena(path=0){const b=new Expedition({seed:'round4-tests',path,difficulty:1,meta:own(path)});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};b.player.x=640;b.player.y=400;b.player.invuln=0;return b;}
const saved=p=>copy(arena(p).serialize());
function finale(){const b=arena(1);b.chapter=5;b.wave=3;b.beginNode();b.player.invuln=0;b.boss.spawn=0;for(let i=0;i<3;i++){b.boss.phaseShield=0;b.hit(b.boss,1e9,'thunder',false);}b.updateSwords=()=>{};b.updateAllies=()=>{};b.hitPlayer=()=>{};return b;}
void test('reserve and derived limits must agree with real difficulty and loadout',()=>{for(const mutate of [d=>d.player.reserve=9999,d=>d.player.maxReserve=1e6,d=>d.player.maxReserve=151,d=>d.player.maxHp=1e6,d=>d.player.maxShield=100]){const d=saved(1);mutate(d);assert.throws(()=>normalizeSave({...initialSave(),checkpoint:d}),/上限|配置/);}for(const difficulty of [0,1,2]){const b=new Expedition({path:1,difficulty,meta:own(1)});b.traits['thunder-1']=1;b.recalc();const r=Expedition.restore(copy(b.serialize()));assert.equal(r.player.maxReserve,b.player.maxReserve);assert.equal(r.player.reserve,b.player.reserve);}});
void test('core-scaled shield caps and extra shields remain valid',()=>{for(const id of ['K11','K12']){const b=arena(5);b.relics=[id];b.recalc();b.player.shield=195;const r=Expedition.restore(copy(b.serialize()));assert.equal(r.player.shield,195);assert.equal(r.player.maxShield,b.player.maxShield);}const b=arena(0);b.player.shield=195;assert.equal(Expedition.restore(copy(b.serialize())).player.shield,195);});
void test('both empty and excessive sword arrays are refused rather than silently remade',()=>{for(const [level,count] of [[100,0],[1,72],[30,29],[30,31]]){const d=saved();d.level=level;d.expedition.swords=Array.from({length:count},()=>copy(d.expedition.swords[0]));assert.throws(()=>Expedition.restore(d),/飞剑数量与等级/);}const b=arena();b.level=100;b.syncSwords();assert.equal(Expedition.restore(copy(b.serialize())).swords.length,72);});
void test('future action times and exaggerated remaining timers are rejected',()=>{for(const mutate of [d=>d.player.invuln=1e6,d=>d.player.dashCD=100,d=>d.player.lastDash=1,d=>d.lastCounter=1,d=>d.expedition.thunderTime=1e7,d=>d.expedition.coreArcUntil=100,d=>d.player.buffs.metaGuardSwift=100,d=>d.expedition.swords[0].cool=99]){const d=saved(1);mutate(d);assert.throws(()=>Expedition.restore(d),/时刻|计时|冷却/);}});
void test('real cast, potion, dodge and expired timers survive roundtrip',()=>{const b=arena(1);b.player.mana=100;b.thunder();b.consumables=[{id:'guard',count:1},{id:'puppet',count:1}];b.consume(0);b.consume(1);b.dash();const r=Expedition.restore(copy(b.serialize()));assert.equal(r.player.invuln,3);assert.equal(r.player.buffs.puppet,30);assert.equal(r.player.dash,.2);const d=copy(b.serialize());d.time=100;d.player.invuln=-50;d.player.dash=-99;d.player.buffs.puppet=30;assert.equal(Expedition.restore(d).player.buffs.puppet,30);});
void test('outlier coordinates are refused while one-screen margin remains readable',()=>{for(const mutate of [d=>d.player.x=1e7,d=>d.expedition.swords[0].px=1e7,d=>d.expedition.insects[0].x=-1e8]){const b=arena(3);b.updateAllies(.01);const d=copy(b.serialize());mutate(d);assert.throws(()=>Expedition.restore(d),/位置与战场/);}const b=arena(3);b.updateAllies(.01);b.insects[0].x=-100;assert.equal(Expedition.restore(copy(b.serialize())).insects[0].x,-100);});
void test('allied extra fields are removed on import, restore and later serialization without altering input',()=>{const b=arena(3);b.updateAllies(.01);const d=copy(b.serialize());d.expedition.insects[0].gnaw='x';d.expedition.insects[0].hp=null;const before=JSON.stringify(d),n=normalizeSave({...initialSave(),checkpoint:d});assert.equal(JSON.stringify(d),before);assert.deepEqual(Object.keys(n.checkpoint.expedition.insects[0]),['x','y','cool']);const r=Expedition.restore(d);assert.equal(r.insects[0].gnaw,undefined);r.insects[0].debugPayload={anything:1};assert.equal(r.serialize().expedition.insects[0].debugPayload,undefined);});
void test('puppet canonical fields retain independent sixth-shot counters',()=>{const b=arena(2);b.updateAllies(.01);Object.assign(b.puppets[0],{metaShots:5,coreShots:1,debug:'ignore'});const r=Expedition.restore(copy(b.serialize()));assert.equal(r.puppets[0].metaShots,5);assert.equal(r.puppets[0].coreShots,1);assert.equal(r.puppets[0].debug,undefined);});
void test('unsupported zone kinds and missing boss references fail before play',()=>{for(const kind of [123,'__proto__','typo',null]){const d=saved();d.expedition.zones=[{x:640,y:400,r:80,ttl:1,warn:0,damage:10,kind}];assert.throws(()=>Expedition.restore(d),/场地效果类型/);}const d=saved();d.expedition.boss={id:999};assert.throws(()=>Expedition.restore(d),/首领关联/);});
void test('save failures preserve original records and backups rather than clamp resources',()=>{const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},v=new SaveVault(storage);v.load();v.commit({...initialSave(),insight:100,checkpoint:saved(1)});map.set(BACKUP_KEY,'existing-backup');const before=map.get(SAVE_KEY),d=saved(1);d.player.reserve=9999;assert.throws(()=>v.commit({...initialSave(),checkpoint:d},{backup:true}),/雷源与上限/);assert.equal(map.get(SAVE_KEY),before);assert.equal(map.get(BACKUP_KEY),'existing-backup');assert.equal(v.load().insight,100);});
void test('missing optional legacy fields preserve the original rules and defaults',()=>{const b=arena(2),d=copy(b.serialize());delete d.expedition.lastShieldBreak;delete d.expedition.stillTime;delete d.player.metaSwitchAt;assert.equal(Expedition.restore(d).stillTime,0);for(const rulesVersion of [1,2]){const old=new Battle({path:1,rulesVersion});const r=Battle.restore(copy(old.serialize()));assert.equal(r.rulesVersion,rulesVersion);assert.equal(r.player.reserve,old.player.reserve);}});
void test('one thunder cannot delay the thirteen-second finale or its scheduled fires',()=>{const plain=finale(),cast=finale();cast.player.mana=100;cast.thunder();for(let i=0;i<300;i++){plain.update(1/60);cast.update(1/60);}assert.ok(Math.abs(plain.bossEnding-8)<1e-5);assert.equal(cast.bossEnding,plain.bossEnding);assert.equal(cast.zones.filter(z=>z.kind==='sacred').length,plain.zones.filter(z=>z.kind==='sacred').length);});
void test('repeated legitimate item refills still cannot freeze the finale',()=>{const b=finale();b.consumables=[{id:'mana2',count:6}];for(let i=0;i<180;i++){if(i%18===0&&b.player.reserve>=b.thunderReadiness().cost){b.consume(0);b.thunder();}b.update(1/60);}assert.ok(b.thunders>=3);assert.ok(Math.abs(b.bossEnding-10)<1e-5);});
void test('paused and saved finales preserve remaining time and settle only once',()=>{const b=finale();for(let i=0;i<60;i++)b.update(1/60);b.pause();const remaining=b.bossEnding;b.update(.05);assert.equal(b.bossEnding,remaining);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.bossEnding,remaining);r.hitPlayer=()=>{};r.updateAllies=()=>{};r.updateSwords=()=>{};r.resume();for(let i=0;i<800;i++)r.update(1/60);assert.equal(r.bossEnding,0);assert.equal(r.receipts.filter(id=>id==='5:3').length,1);assert.equal(r.scene,'intermission');});
void test('normal boss stun still pauses normal boss movement',()=>{const b=arena();b.chapter=0;b.wave=3;b.beginNode();b.boss.spawn=0;b.boss.stun=.35;const x=b.boss.x,y=b.boss.y;b.update(.05);assert.equal(b.boss.x,x);assert.equal(b.boss.y,y);assert.ok(b.boss.stun<.35);});
void test('shield item and event labels use the same extra-shield term',()=>{assert.match(CONSUMABLES.find(c=>c.id==='shield').desc,/额外护盾/);assert.match(arena().singleEffectText('shield'),/额外护盾/);});
void test('burn candidates do not exponentiate burns on rejected or repeated hits',()=>{const b=arena(4),e=b.spawn(1,{x:800,y:400,hp:1e6,spawn:0});const experiment=applyBalanceExperiment(b,'burn2');assert.equal(experiment.hypothetical,true);b.hit(e,1,'sword',false);const burn=e.burnDamage;e.phaseShield=2;for(let i=0;i<20;i++)b.hit(e,1,'sword',false);assert.equal(e.burnDamage,burn);e.phaseShield=0;b.hit(e,1,'sword',false);assert.equal(e.burnDamage,burn);});
void test('hypothetical ring slow is independent of ember refresh and not a production save',()=>{const b=arena(4),e=b.spawn(1,{x:680,y:400,hp:1e6,spawn:0});b.rebuildHash();b.zones=[{x:640,y:400,r:90,ttl:1,warn:.8,kind:'sigil',sigil:true,friendly:true,damage:50}];applyBalanceExperiment(b,'slowring');b.update(.01);applySlow(e,'ember',.3,.4);const ring=e.slows.find(v=>v.source==='experimentRing');assert.ok(ring.left>1.9);assert.throws(()=>Expedition.restore(copy(b.serialize())),/减速来源/);});
void test('fixed-level snapshot trials actually rebuild the exact sword count and freeze XP',()=>{const b=arena(2);b.level=59;b.syncSwords();b.xp=200;const r=prepareSnapshotTrial(copy(b.serialize()),{level:50,meta:'all'});assert.equal(r.level,50);assert.equal(r.swords.length,50);assert.equal(r.xp,0);r.addXP(1e6);assert.equal(r.level,50);assert.equal(r.swords.length,50);});
