/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';
import {Battle} from '../gameplay/engine.js';
import {gnawStatus,gnawTargets} from '../gameplay/targeting.js';
const copy=structuredClone;
function arena(path=0,options={},emit=()=>{}){const b=new Expedition({path,seed:'round9',difficulty:1,...options},emit);b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=b.updateEnvironment=b.updateAllies=b.updateEnemy=()=>{};return b;}
function enemy(b,dx=200,dy=0){const e=b.spawn(0,{x:b.player.x+dx,y:b.player.y+dy,hp:10000,spawn:0,noDrop:true});e.speed=0;b.rebuildHash();return e;}
function launch(b){b.level=12;b.swords=[];b.syncSwords();b.swords.forEach(s=>s.cool=0);b.updateSwords(0);return b.swords.map(s=>s.target?.id);}
void test('held focus assigns all new sword launches to the nearest in-range aim target, then releases to grouping',()=>{const b=arena(),a=enemy(b),z=enemy(b,220,30),c=enemy(b,180,-30);b.input={focus:true,aim:{x:a.x,y:a.y}};assert.deepEqual(launch(b),Array(12).fill(a.id));b.input.focus=false;const targets=launch(b);for(const e of [a,z,c])assert.ok(targets.includes(e.id));assert.ok(targets.filter(id=>id===a.id).length<12);});
void test('focus does not cancel an existing flight, reset cooldown, extend range or add piercing',()=>{const b=arena(),a=enemy(b),z=enemy(b,220,40);b.input={focus:true,aim:{x:a.x,y:a.y}};launch(b);const sw=b.swords[0],cool=sw.cool,pierce=sw.pierce;b.input.aim={x:z.x,y:z.y};b.updateSwords(0);assert.equal(sw.target.id,a.id);assert.equal(sw.cool,cool);assert.equal(sw.pierce,pierce);const far=arena();const e=enemy(far,500);far.input={focus:true,aim:{x:e.x,y:e.y}};assert.ok(launch(far).every(id=>id===undefined));});
void test('old unmarked focus saves retain three-way targeting, while new marker survives repeated restore',()=>{for(const focusVersion of [1,2]){const b=arena(0,{focusVersion});const a=enemy(b);enemy(b,210,20);enemy(b,190,-20);const data=copy(b.serialize());if(focusVersion===1)delete data.options.focusVersion;let r=Expedition.restore(data);r=Expedition.restore(copy(r.serialize()));assert.equal(r.options.focusVersion,focusVersion);r.input={focus:true,aim:{x:a.x,y:a.y}};const targets=launch(r);assert.equal(targets.filter(id=>id===a.id).length,focusVersion===2?12:4);}const d=copy(arena().serialize());d.options.focusVersion=4;assert.throws(()=>Expedition.restore(d),/集火规则/);});
void test('gnaw readout uses actual live stacks, expiry and both cached groups without mutating gameplay',()=>{const b=arena(3),a=enemy(b),z=enemy(b,220,20);b.time=10;a.gnaw=.08;a.gnawUntil=12.5;z.gnaw=.12;z.gnawUntil=13;b.relics=['K07'];b.targetCache={bug0:{id:a.id,until:11},bug1:{id:z.id,until:11}};const before=JSON.stringify(b.serialize());assert.match(gnawStatus(b),/A 追击 4\/6.*8%.*2.5s.*B 追击 6\/6.*12%.*3.0s/);assert.equal(JSON.stringify(b.serialize()),before);b.time=14;assert.equal(gnawTargets(b).length,0);assert.match(gnawStatus(b),/0\/6/);});
void test('temporary ally usage describes actual addition, refresh and cap without stacking quantities',()=>{const b=arena(2);b.consumables=[{id:'puppet',count:3}];b.consume(0);assert.match(b.toastText,/临时增加 1 具.*30 秒/);b.time=5;b.consume(0);assert.match(b.toastText,/剩余时间刷新为 30 秒.*数量不变（3 具）/);assert.equal(b.player.buffs.puppet,35);assert.equal(b.consumables[0].count,1);b.stats.puppets=12;b.consume(0);assert.match(b.toastText,/已达 12 具上限.*仅刷新/);assert.equal(b.player.buffs.puppet,35);const insect=arena(3);insect.consumables=[{id:'insect',count:2}];insect.consume(0);insect.consume(0);assert.match(insect.toastText,/25 秒.*数量不变（8 只）/);});
void test('resource-failure hints are limited but availability and resource accounting stay immediate',()=>{const events=[],b=arena(1,{},e=>events.push(e));events.length=0;b.player.mana=100;b.player.reserve=0;for(let i=0;i<60;i++)assert.equal(b.thunder(),false);assert.equal(events.filter(e=>e.type==='toast').length,1);assert.equal(b.player.mana,100);b.time=2.6;b.thunder();assert.equal(events.filter(e=>e.type==='toast').length,2);b.player.reserve=140;assert.equal(b.thunder(),true);assert.equal(b.player.mana,0);assert.ok(b.combatCues.some(c=>c.key==='thunder-cast'&&/已施放/.test(c.text)),'thunder confirmation now uses the cue channel (round-2 C-1)');});
void test('first full-mana reserve-short branch remains reachable',()=>{const b=arena(1);b.player.mana=99.99;b.player.reserve=0;b.update(.01);assert.match(b.toastText,/灵力已满.*雷源不足/);});
void test('training allows counter practice without harming the player',()=>{const b=arena(5,{mode:'training'});enemy(b,30);const hp=b.player.hp;b.dash();b.hitPlayer(30);assert.equal(b.player.hp,hp);assert.ok(b.damageSources.guard>0);});
void test('range, pursuit speed and burn duration remain effective in the scenarios they govern',()=>{const shots=[];for(const boost of [false,true]){const b=arena(2,{meta:boost?['puppet-meta-2']:[]});enemy(b,460);b.puppets=Array.from({length:2},()=>({x:b.player.x,y:b.player.y,cool:0}));Battle.prototype.updateAllies.call(b,0);shots.push(b.shots.length);}assert.deepEqual(shots,[0,2]);const times=[];for(const boost of [false,true]){const b=arena(3,{meta:boost?['insect-meta-1']:[]});b.stats.insects=1;b.insects=[{x:b.player.x,y:b.player.y,cool:0}];enemy(b,280);for(let i=0;i<200&&!b.damageSources.insect;i++){b.time+=1/60;Battle.prototype.updateAllies.call(b,1/60);}times.push(b.time);}assert.ok(times[1]<times[0]);const burns=[];for(const boost of [false,true]){const b=arena(4,{meta:boost?['talisman-meta-2']:[]}),e=enemy(b);b.hit(e,1,'sword',false);for(let i=0;i<100;i++){b.time+=.05;Battle.prototype.updateEnemy.call(b,e,.05);}burns.push(b.damageSources.fire);}assert.ok(burns[1]>burns[0]);});
