/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {CORES} from '../gameplay/expedition-data.js';import {META,initialSave,TRAITS} from '../gameplay/data.js';import {META_V2,cultivationMods,cultivationDetail,needsCultivationUpgrade} from '../gameplay/cultivation.js';import {planCultivationUpgrade} from '../gameplay/respec.js';import {SaveVault,SAVE_KEY,BACKUP_KEY,normalizeSave} from '../gameplay/save-store.js';import {puppetReady,stationaryActive,sigilGrowth,reserveRestoration} from '../gameplay/balance.js';import {usefulCore} from '../gameplay/economy-rules.js';import {traitReadiness} from '../gameplay/growth-rules.js';import {traitDescription} from '../gameplay/descriptions.js';import {coreDescription} from '../gameplay/core-description.js';import {starterDetails,starterStatus} from '../gameplay/starters.js';import {gnawTargets} from '../gameplay/targeting.js';
const copy=structuredClone,close=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`),all=p=>META.filter(m=>m.path===p).map(m=>m.id);
function arena(path=0,options={}){const b=new Expedition({segmentVersion:0,challengeVersion:0,seed:'round10-phase3',path,economyVersion:2,growthVersion:3,encounterVersion:3,...options});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=b.updateEnvironment=b.updateSwords=b.updateAllies=b.updateEnemy=()=>{};b.player.invuln=0;return b;}
function enemy(b,extra={}){const e=b.spawn(4,{x:800,y:400,hp:100000,spawn:0,speed:0,...extra});b.rebuildHash();return e;}
function tick(b,n,dt=.05){for(let i=0;i<n;i++)b.update(dt);}
function prep(){const b=arena();b.chapter=2;b.nextChapter();return b;}
function bad(d,mutate,pattern){const raw=copy(d);mutate(raw);const before=JSON.stringify(raw);assert.throws(()=>Expedition.restore(raw),pattern);assert.equal(JSON.stringify(raw),before);}
void test('M15/M16/M17 new markers are independent; absent markers retain old rules and reject future versions',()=>{
 const b=arena();assert.equal(b.options.balanceVersion,4);assert.equal(b.options.metaRulesVersion,3);assert.equal(b.options.economyVersion,2);assert.equal(initialSave().version,1);
 const old=arena(1,{balanceVersion:1,metaRulesVersion:1,economyVersion:1}),d=copy(old.serialize());for(const k of ['balanceVersion','metaRulesVersion','economyVersion'])delete d.options[k];const r=Expedition.restore(d);for(const k of ['balanceVersion','metaRulesVersion','economyVersion'])assert.equal(r.options[k],1);assert.equal(r.thunderReadiness().cost,25);
 for(const [k,v] of [['balanceVersion',5],['metaRulesVersion',4],['economyVersion',5]])bad(b.serialize(),d=>d.options[k]=v,/版本/);
 bad(b.serialize(),d=>delete d.expedition.setupUntil,/衔接/);bad(b.serialize(),d=>d.expedition.setupUntil='0',/衔接/);bad(b.serialize(),d=>d.expedition.setupUntil=2,/衔接/);bad(b.serialize(),d=>delete d.expedition.economy,/账本/);
});
void test('M15 thunder uses 22 only for new thunder starts; savings clamp before K03, with real consumption and restore',()=>{
 for(const version of [1,2,3])for(let path=0;path<6;path++){const b=arena(path,{balanceVersion:version});assert.equal(b.thunderReadiness().cost,path===1&&version===3?22:25);b.player.mana=100;b.relics=['K03'];b.stats.thunderSave=99;assert.equal(b.thunderReadiness().cost,11);const before=b.player.reserve;b.thunder();close(b.player.reserve,before-11);}
 const b=arena(1,{meta:all(1)});assert.equal(b.thunderReadiness().cost,20);b.relics=['K03'];assert.equal(b.thunderReadiness().cost,23);b.player.mana=100;b.thunder();const r=Expedition.restore(copy(b.serialize()));assert.equal(r.thunderReadiness().cost,23);assert.equal(r.player.reserve,b.player.reserve);
 const t=TRAITS.find(t=>t.mods.thunderSave);assert.ok(t);b.stats.thunderSave=14;assert.equal(traitReadiness(t,b).eligible,false);
});
void test('M15 sigil scaling begins after 12 swords, caps at 72 and stores one original damage snapshot',()=>{
 for(const level of [1,12,13,36,72,100])for(const core of [null,'K09','K10']){const b=arena(4,{balanceVersion:3});b.level=level;b.relics=core?[core]:[];b.stats.burnDamage=.15;b.stats.dashFire=1;b.dash();const z=b.zones[0],expected=(55+level*1.2)*1.35*1.15*(1+.08*Math.max(0,Math.min(72,level)-12));close(z.originalDamage,expected);close(z.damage,expected*(core==='K09'?.8:core==='K10'?.7:1));b.level=160;b.recalc();close(z.originalDamage,expected);}
 assert.equal(sigilGrowth(arena(4,{balanceVersion:2})),1);
});
void test('M15 trigger and effective explosion both include a target whose body intersects the outer edge',()=>{
 for(const version of [2,3]){const b=arena(4,{balanceVersion:version});b.dash();const z=b.zones[0];const e=enemy(b,{x:z.x+z.r+19,y:z.y,r:20});b.input={x:0,y:0};tick(b,8);if(version===3){assert.equal(z.fired,true);assert.ok(e.hp<100000);assert.equal(b.sigilStats.sigil.hits,1);}else{assert.ok(!z.fired);assert.equal(e.hp,100000);}}
 const b=arena(4);b.dash();const z=b.zones[0],e=enemy(b,{x:z.x+z.r+21,y:z.y,r:20});tick(b,8);assert.ok(!z.fired);assert.equal(e.hp,100000);
});
void test('M15 edge shielded targets cannot trigger and are counted as blocked at timeout',()=>{const b=arena(4);b.dash();const z=b.zones[0],e=enemy(b,{x:z.x+z.r+10,y:z.y,r:20,untargetable:true});tick(b,49);assert.equal(e.hp,100000);assert.equal(b.sigilStats.sigil.blocked,1);assert.equal(b.sigilStats.sigil.damage,0);});
void test('M15 echo, ember and twin line derive from the original snapshot once, without recursion',()=>{
 const b=arena(4,{meta:all(4)});b.level=72;b.relics=['K09'];b.dash();const z=b.zones[0];b.zones=[];b.onSigilDetonate(z);const echo=b.zones.find(z=>z.metaEcho),ember=b.zones.find(z=>z.ember===undefined&&!z.sigil);close(echo.damage,z.originalDamage*.2);close(echo.r,z.r*.8);close(ember.damage,z.originalDamage*.1);const count=b.zones.length;b.onSigilDetonate(echo);assert.equal(b.zones.length,count);
 const c=arena(4,{meta:all(4)});c.level=72;c.relics=['K10'];c.dash();c.time=6;c.player.dashCD=0;c.player.x+=100;c.dash();const pair=c.zones;assert.equal(pair.length,2);close(pair[1].line.damage,pair[1].originalDamage);c.zones=[];c.onSigilDetonate(pair[1]);assert.ok(!c.zones.some(z=>z.metaEcho));
});
void test('M15 guard gives one half-power counter and 3 shield per successful dash, including same-frame barrages',()=>{
 const b=arena(5,{balanceVersion:3});b.stats.dashHaste=.65;b.stats.shieldRegen=0;b.player.shield=0;enemy(b,{x:b.player.x+50,y:b.player.y});b.dash();for(let i=0;i<30;i++)b.hitPlayer(10);close(b.damageSources.guard,16+b.level*.45);assert.equal(b.player.shield,3);const first=b.lastCounter;tick(b,18);assert.equal(b.dash(),true);b.hitPlayer(10);assert.ok(b.lastCounter>first);assert.equal(b.player.shield,6);assert.ok(!b.combatCues.some(c=>c.key==='counter-wait'));
 for(let k=0;k<60;k++){tick(b,18);b.dash();for(let i=0;i<20;i++)b.hitPlayer(10);}assert.ok(b.player.shield<=b.player.maxShield+12);b.player.shield=200;tick(b,18);b.dash();b.hitPlayer(10);assert.equal(b.player.shield,200);
});
void test('M15 guard missed dashes grant nothing, and restoring a used dodge does not counter twice',()=>{const b=arena(5);b.player.shield=0;b.dash();assert.equal(b.player.shield,0);b.hitPlayer(10);const d=copy(b.serialize()),r=Expedition.restore(d);const shield=r.player.shield;r.hitPlayer(10);assert.equal(r.player.shield,shield);assert.equal(r.lastCounter,b.lastCounter);});
void test('M15 puppet setup retains 0.3 seconds, expires after moving and never stacks with mobile core',()=>{
 const b=arena(2,{meta:all(2)});b.input={x:0,y:0};tick(b,13);assert.ok(puppetReady(b));b.input={x:1,y:0};tick(b,4);assert.ok(puppetReady(b));assert.ok(stationaryActive(b));assert.equal(b.puppetHasteBonus(),.25);const r=Expedition.restore(copy(b.serialize()));assert.ok(puppetReady(r));assert.equal(r.setupUntil,b.setupUntil);tick(b,3);assert.ok(!puppetReady(b));assert.ok(!stationaryActive(b));b.setupUntil=b.time+.3;b.relics=['K06'];assert.equal(b.puppetHasteBonus(),.35);assert.equal(stationaryActive(b),false);
});
void test('M15 K05 extra volley uses the retained setup window and stops after it expires',()=>{const b=arena(2);b.relics=['K05'];b.puppets=[{},{}];b.player.moving=true;b.stillTime=0;b.time=1;b.setupUntil=1.3;const a={x:650,y:520,coreShots:1},e=enemy(b);b.onPuppetShot(a,e,10);assert.equal(b.shots.length,2);b.time=1.31;a.coreShots=1;b.onPuppetShot(a,e,10);assert.equal(b.shots.length,2);});
void test('M16 all 36 new nodes remain isolated to their branch and old definitions are retained',()=>{for(const m of META){const opts={metaRulesVersion:3,meta:[m.id]};assert.deepEqual(cultivationMods(opts,m.path),m.mods);assert.deepEqual(cultivationMods(opts,(m.path+1)%6),{});}for(const id of ['thunder-meta-3','insect-meta-5','talisman-meta-3']){const old=META_V2.find(m=>m.id===id),current=META.find(m=>m.id===id);assert.notDeepEqual(old.mods,current.mods);assert.deepEqual(cultivationMods({metaRulesVersion:2,meta:[id]},old.path),old.mods);}});
void test('M16 reserve rest adds five once, respects cap and all excluded rooms',()=>{
 for(const version of [2,3]){const b=arena(1,{balanceVersion:3,metaRulesVersion:version,meta:['thunder-meta-3']});b.player.reserve=0;b.completeNode();assert.equal(b.rest.reserveGain,version===3?20:15);const r=Expedition.restore(copy(b.serialize()));r.completeNode();assert.equal(r.player.reserve,b.player.reserve);}
 const b=arena(1,{balanceVersion:3,meta:all(1)});b.player.reserve=b.player.maxReserve-2;assert.equal(reserveRestoration(b),2);for(const chapter of [0,1,2,3,4,5]){b.chapter=chapter;b.wave=b.routes[chapter].length-1;b.player.reserve=0;assert.equal(reserveRestoration(b),0);}for(const chapter of [3,5]){b.chapter=chapter;b.wave=0;assert.equal(reserveRestoration(b),0);}
});
void test('M16 normal and upgraded arming is shorter; K09 shares it; K10 pair is 0.65 seconds, never retroactive',()=>{
 for(const core of [null,'K09','K10'])for(const upgraded of [false,true]){const b=arena(4,{balanceVersion:3,meta:['talisman-meta-3']});b.relics=core?[core]:[];if(upgraded)b.traits['talisman-10']=1;b.recalc();b.dash();const z=b.zones[0];if(core!=='K10')close(z.arming,upgraded?.1:.2);else{assert.equal(z.warn,8);b.time=6;b.player.dashCD=0;b.dash();close(z.warn,.65);close(b.zones[1].warn,.65);}assert.equal(b.sigilReadiness().left,6);}
 const b=arena(4);b.dash();const z=b.zones[0];b.stats.metaSigilArming=.15;assert.equal(z.arming,.35);
});
void test('M16 insect assist counts sword finishes within three seconds, not blocked damage, no-drop units or repeats',()=>{
 const b=arena(3,{meta:all(3)});b.player.hp=50;for(let i=0;i<7;i++){const e=enemy(b,{hp:20});b.hit(e,1,'insect',false);b.hit(e,1e4,'sword',false);b.kill(e);}assert.equal(b.player.metaInsectKills,7);
 const noDrop=enemy(b,{hp:20,noDrop:true});b.hit(noDrop,1,'insect',false);b.hit(noDrop,1e4,'sword',false);assert.equal(b.player.metaInsectKills,7);
 const runeBattle=arena(3,{meta:all(3)});runeBattle.player.hp=50;runeBattle.objective={kind:'break',done:0,total:3};const rune=enemy(runeBattle,{hp:20,mission:'rune'});runeBattle.hit(rune,1,'insect',false);runeBattle.hit(rune,1e4,'sword',false);assert.equal(runeBattle.player.metaInsectKills||0,0);
 const stale=enemy(b,{hp:20});b.hit(stale,1,'insect',false);b.time=3.01;b.hit(stale,1e4,'sword',false);assert.equal(b.player.metaInsectKills,7);
 const e=enemy(b,{hp:20});b.hit(e,1,'insect',false);const r=Expedition.restore(copy(b.serialize()));const target=r.enemies.find(x=>x.id===e.id);r.hit(target,1e4,'sword',false);assert.equal(r.player.hp,53);assert.equal(r.player.metaInsectKills,8);
 const blocked=enemy(b,{hp:20,phaseShield:1});b.hit(blocked,1,'insect',false);assert.equal(blocked.lastInsectHit,undefined);
});
void test('M16 full-health assist kills do not bank progress and recovery is limited to missing health',()=>{const b=arena(3,{meta:all(3)});for(let i=0;i<15;i++)b.hit(enemy(b,{hp:1}),100,'insect',false);assert.equal(b.player.metaInsectKills,0);b.player.hp=b.player.maxHp-.5;for(let i=0;i<8;i++)b.hit(enemy(b,{hp:1}),100,'insect',false);assert.equal(b.player.hp,b.player.maxHp);assert.match(b.combatCues.find(c=>c.key==='recovery').text,/0.5/);});
void test('M16 version-2 conversion refunds its real prices, preserves checkpoint, backs up, and a failed write changes no record',()=>{
 const map=new Map(),storage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};const old={...initialSave(),metaRulesVersion:2,meta:all(4),insight:9,checkpoint:arena(4,{balanceVersion:2,economyVersion:1,metaRulesVersion:2,meta:all(4)}).serialize()};map.set(SAVE_KEY,JSON.stringify(old));const vault=new SaveVault(storage),s=vault.load(),raw=map.get(SAVE_KEY),plan=planCultivationUpgrade(s);assert.equal(needsCultivationUpgrade(s),true);assert.equal(plan.refund,345);assert.equal(plan.save.insight,354);assert.equal(plan.save.metaRulesVersion,3);assert.deepEqual(plan.save.checkpoint,s.checkpoint);assert.equal(plan.nodes[3].desc,META_V2.find(m=>m.id==='talisman-meta-3').desc);assert.equal(map.get(SAVE_KEY),raw);
 const write=storage.setItem;storage.setItem=(k,v)=>{if(k===SAVE_KEY)throw Error('quota');write(k,v);};assert.throws(()=>vault.commit(plan.save,{backup:true}));assert.equal(map.get(SAVE_KEY),raw);storage.setItem=write;vault.commit(plan.save,{backup:true});assert.equal(JSON.parse(map.get(BACKUP_KEY)).raw,raw);assert.equal(Expedition.restore(plan.save.checkpoint).stats.metaSigilCooldown,.6);
});
void test('M16 text distinguishes basis, relative improvement, concrete range and actual new timing',()=>{const b=arena(4,{meta:all(4)}),t=TRAITS.find(t=>t.id==='talisman-10');assert.match(traitDescription(t,b),/0.1 秒/);assert.match(coreDescription(CORES.find(c=>c.id==='K10'),b),/0.65 秒/);assert.match(starterDetails(4,b.options).action,/0.2 秒/);const insect=arena(3,{meta:all(3)});assert.match(cultivationDetail(META.find(m=>m.id==='insect-meta-3'),insect),/480/);assert.match(cultivationDetail(META.find(m=>m.id==='insect-meta-2'),insect),/相对未修持/);assert.match(starterDetails(5).action,/最多回盾 3/);assert.match(starterDetails(5,{balanceVersion:2}).action,/回盾 6/);});
void test('M15 sword stance and insect pursuit feedback reflect actual targets without consuming randomness',()=>{const b=arena(0);b.formation=1;assert.match(starterStatus(b),/环护/);const i=arena(3),e=enemy(i);i.insectPursuits=[e.id];const rng=i.rng.state();assert.equal(gnawTargets(i)[0].pursuing,true);assert.equal(gnawTargets(i)[0].percent,0);e.hp=0;assert.equal(gnawTargets(i).length,0);assert.equal(i.rng.state(),rng);});
void test('M17 first cores give one own and one useful cross-path option over six paths and 100 seeds, without duplicates',()=>{for(let path=0;path<6;path++)for(let seed=0;seed<100;seed++){const b=arena(path,{seed:'cores-'+seed}),ids=b.makeCoreOffers(),cores=ids.map(id=>CORES.find(c=>c.id===id));assert.equal(ids.length,3);assert.equal(new Set(ids).size,3);assert.equal(cores[0].path,path);assert.notEqual(cores[1].path,path);assert.ok(cores.every(c=>usefulCore(c,b)));}});
void test('M17 second cores prioritize unheld useful directions; generated draft survives edits and restore',()=>{
 const b=arena(3);b.chapter=2;b.wave=b.routes[2].length-1;b.node.selected=0;b.beginNode();b.relics=['K07'];b.completeNode();b.advanceCinematic(true);const ids=[...b.rest.coreOffers];assert.ok(ids.every(id=>!['K07','K08'].includes(id)));const before={gold:b.gold,relics:[...b.relics],rerolls:b.rerolls};b.selectCore(ids[0]);b.selectCore(ids[1]);assert.deepEqual(b.rest.coreOffers,ids);assert.equal(b.gold,before.gold);assert.deepEqual(b.relics,before.relics);assert.equal(b.rerolls,before.rerolls);const r=Expedition.restore(copy(b.serialize()));assert.deepEqual(r.rest.coreOffers,ids);assert.equal(r.rest.coreSelection.id,ids[1]);
});
void test('M17 purchases cost 80 then 120, only add rerolls, persist proof, and cannot exceed two across endless loops',()=>{
 const b=prep();b.gold=300;const count=b.rerolls,choices=copy(b.choices),shop=copy(b.shop);assert.equal(b.rerollPurchaseReadiness().price,80);assert.equal(b.buyReroll(),true);assert.equal(b.gold,220);assert.equal(b.rerolls,count+1);assert.deepEqual(b.choices,choices);assert.deepEqual(b.shop,shop);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.buyReroll(),true);assert.equal(r.gold,100);assert.equal(r.rerolls,count+2);const raw=JSON.stringify(r.serialize());assert.equal(r.buyReroll(),false);assert.equal(JSON.stringify(r.serialize()),raw);r.endlessLoop=1;assert.equal(r.buyReroll(),false);normalizeSave({...initialSave(),checkpoint:r.serialize()});
});
void test('M17 poor, early, old-rule and paused purchase attempts change nothing',()=>{for(const b of [arena(),arena(0,{economyVersion:1}),prep(),prep()]){if(b.scene==='intermission'){if(b.gold<80)b.gold=79;else b.scene='pause';}const raw=JSON.stringify(b.serialize());assert.equal(b.buyReroll(),false);assert.equal(JSON.stringify(b.serialize()),raw);}const b=prep();b.gold=100;b.scene='pause';assert.equal(b.buyReroll(),false);});
void test('M17 corrupt, duplicated and future purchase receipts are rejected without changing their raw input',()=>{const b=prep();b.gold=300;b.buyReroll();const d=b.serialize();for(const mutate of [d=>d.expedition.economy.rerollPurchases[0].price=120,d=>d.expedition.economy.rerollPurchases[0].afterGold=300,d=>d.expedition.economy.rerollPurchases[0].node='0:0',d=>d.expedition.economy.rerollPurchases[0].loop=1,d=>d.expedition.economy.rerollPurchases.push(copy(d.expedition.economy.rerollPurchases[0]))])bad(d,mutate,/购置|付款/);});

void test('M17 a stale 80-price click cannot buy the next 120-price stock',()=>{const b=prep();b.gold=300;assert.equal(b.buyReroll(80),true);const before=JSON.stringify(b.serialize());assert.equal(b.buyReroll(80),false);assert.equal(JSON.stringify(b.serialize()),before);assert.equal(b.buyReroll(120),true);});
void test('M15-M17 all 108 independent balance, cultivation and economy configurations roundtrip without changing stats',()=>{for(let path=0;path<6;path++)for(const balanceVersion of [1,2,3])for(const metaRulesVersion of [1,2,3])for(const economyVersion of [1,2]){const b=arena(path,{balanceVersion,metaRulesVersion,economyVersion,meta:all(path)}),d=copy(b.serialize()),raw=JSON.stringify(d),r=Expedition.restore(d);assert.equal(JSON.stringify(d),raw);assert.deepEqual(r.stats,b.stats);for(const key of Object.keys(b.options))assert.deepEqual(r.options[key],b.options[key]);for(const key of ['maxHp','maxShield','maxReserve','reserve','mana'])assert.equal(r.player[key],b.player[key]);}});

void test('M16 relative sword contribution includes conditional stats and does not mutate the run',()=>{const b=arena(0,{meta:all(0)});b.level=72;b.stats.swordScale=.2;b.stats.fullMana=.2;b.player.mana=100;const raw=JSON.stringify(b.serialize()),node=META.find(m=>m.id==='sword-meta-0');const without=Object.create(b);without.stats={...b.stats,damage:b.stats.damage-.08};const ratio=Number(((b.swordDamage(null)/without.swordDamage(null)-1)*100).toFixed(2));assert.ok(cultivationDetail(node,b).includes('增加 '+ratio+'%'));assert.equal(JSON.stringify(b.serialize()),raw);});
