/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';
import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';
import {EVENTS,META} from '../gameplay/data.js';
import {dashCooldown,reserveRestoration} from '../gameplay/balance.js';
const copy=structuredClone;
function arena(path=4,options={}){const b=new Expedition({balanceVersion:2,metaRulesVersion:2,seed:'round7',contentVersion:1,path,difficulty:1,...options});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.player.invuln=0;b.updateDirector=b.updateEnvironment=b.updateSwords=b.updateAllies=b.updateEnemy=()=>{};return b;}
function advance(b,time){for(let i=0;i<Math.round(time/.01);i++)b.update(.01);}
function enemy(b,x,y){const e=b.spawn(4,{hp:1000,noDrop:true,spawn:0});e.x=x;e.y=y;b.rebuildHash();return e;}
void test('new sigils wait for arming then catch late pursuers; snapshot keeps the trigger and does not double-burst',()=>{const b=arena();b.dash();const z=b.zones[0];advance(b,1);assert.equal(b.sigilStats.sigil.casts,0);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.zones[0].arming,0);assert.equal(r.zones[0].fuseDuration,2.4);for(const x of [b,r]){x.updateDirector=x.updateEnvironment=x.updateSwords=x.updateAllies=x.updateEnemy=()=>{};enemy(x,z.x+40,z.y);advance(x,.1);assert.equal(x.sigilStats.sigil.casts,1);assert.equal(x.sigilStats.sigil.hits,1);advance(x,.5);assert.equal(x.sigilStats.sigil.casts,1);}});
void test('arming delay, expiry, enhanced arming and inward edge placement are real rules',()=>{const b=arena();b.player.x=30;b.player.y=40;b.dash();const z=b.zones[0];assert.ok(z.x>=z.r&&z.y>=z.r);enemy(b,z.x,z.y);advance(b,.2);assert.equal(b.sigilStats.sigil.casts,0);advance(b,.2);assert.equal(b.sigilStats.sigil.casts,1);const empty=arena();empty.dash();advance(empty,2.5);assert.equal(empty.sigilStats.sigil.empty,1);assert.equal(empty.combatCues.some(c=>/落空/.test(c.text)),false);const boosted=arena();boosted.traits['talisman-10']=1;boosted.recalc();boosted.dash();assert.equal(boosted.zones[0].arming,.2);});
void test('unmarked historical runs retain fixed fuses, dash cooldown and route engine across repeated restores',()=>{for(const path of [4,5]){const b=arena(path,{balanceVersion:1});const d=copy(b.serialize());delete d.options.balanceVersion;let r=Expedition.restore(d);assert.equal(r.options.balanceVersion,1);r=Expedition.restore(copy(r.serialize()));r.resume();r.dash();if(path===4){assert.equal(r.zones[0].fuseDuration,.8);assert.equal(r.zones[0].arming,undefined);}else assert.equal(r.player.dashCD,3);assert.deepEqual(r.routes,b.routes);assert.equal(r.options.rulesVersion,3);}});
void test('new guard cooldown shortens movement recovery while preserving the four-second counter gate',()=>{const b=arena(5);assert.equal(dashCooldown(b),2);b.dash();b.hitPlayer(10);assert.equal(b.lastCounter,0);advance(b,2);b.dash();b.hitPlayer(10);assert.equal(b.lastCounter,0);advance(b,2.01);b.dash();b.hitPlayer(10);assert.ok(b.lastCounter>=4);assert.match(b.combatCues.find(c=>c.key==='counter').text,/守元反击/);});
void test('thunder rest reserve is capped, recorded once, and excluded from treasure and final chapter',()=>{const b=arena(1);b.player.reserve=0;b.completeNode();assert.equal(b.player.reserve,15);assert.equal(b.rest.reserveGain,15);b.completeNode();assert.equal(b.player.reserve,15);const r=Expedition.restore(copy(b.serialize()));r.completeNode();assert.equal(r.player.reserve,15);const capped=arena(1);capped.player.reserve=capped.player.maxReserve-3;capped.completeNode();assert.equal(capped.rest.reserveGain,3);const legacy=arena(1,{balanceVersion:1});legacy.player.reserve=0;legacy.completeNode();assert.equal(legacy.player.reserve,0);for(const chapter of [3,5]){const x=arena(1);x.chapter=chapter;x.wave=0;x.player.reserve=0;assert.equal(reserveRestoration(x),0);}});
void test('event previews are read-only, distinguish full resources, cash and stackable supplies',()=>{const b=arena();b.completeNode();const set=effect=>{const index=EVENTS.findIndex(e=>e.choices.some(c=>c.effect===effect));b.rest.event={type:'single',index,choice:null};return EVENTS[index].choices.findIndex(c=>c.effect===effect);};let i=set('heal');const before=JSON.stringify(b.serialize());assert.equal(b.interactionReadiness(i).noBenefit,true);assert.match(b.eventText().choices[i],/当前可恢复 0 生命/);assert.equal(JSON.stringify(b.serialize()),before);i=set('buyHeal');b.gold=0;assert.match(b.interactionReadiness(i).reason,/还缺 25/);const disk=JSON.stringify(b.serialize());assert.equal(b.chooseInteraction(i),false);assert.equal(JSON.stringify(b.serialize()),disk);i=set('medicine');b.consumables=[{id:'mana',count:1},{id:'guard',count:1}];assert.equal(b.interactionReadiness(i).blocked,true);b.consumables[1]={id:'heal',count:1};assert.equal(b.interactionReadiness(i).blocked,false);});
void test('echo still follows an empty main burst; purchased cultivation values remain unchanged',()=>{const b=arena(4,{meta:META.filter(m=>m.path===4).map(m=>m.id)});b.dash();advance(b,2.9);assert.equal(b.sigilStats.sigil.empty,1);assert.equal(b.sigilStats.echo.empty,1);assert.equal(b.stats.metaSigilEcho,1);assert.equal(META.find(m=>m.name==='轻步留隙').mods.iframes,.03);});
void test('invalid balance markers and trap timing are rejected without changing input',()=>{const b=arena();b.dash();for(const change of [d=>d.options.balanceVersion=3,d=>d.expedition.zones[0].arming=5,d=>d.expedition.zones[0].twin=true]){const d=copy(b.serialize());change(d);const before=JSON.stringify(d);assert.throws(()=>Expedition.restore(d));assert.equal(JSON.stringify(d),before);}});
void test('starter supplies get three equal probability units while old shops keep eighteen equal units',()=>{for(const [path,id] of [[1,'mana'],[2,'puppet'],[3,'insect'],[4,'fire'],[5,'guard']]){const b=arena(path),counts={};for(let i=0;i<20;i++){b.rng=()=> (i+.5)/20;b.makeShop();const selected=b.shop.at(-1).id;counts[selected]=(counts[selected]||0)+1;}assert.equal(counts[id],3);assert.equal(Object.keys(counts).length,18);const old=arena(path,{balanceVersion:1}),legacy={};for(let i=0;i<18;i++){old.rng=()=> (i+.5)/18;old.makeShop();legacy[old.shop.at(-1).id]=(legacy[old.shop.at(-1).id]||0)+1;}assert.deepEqual(Object.values(legacy),Array(18).fill(1));}});
