/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
// Historical balance/cultivation assertions stay on their original rule versions. Phase 3 is tested separately.
import test from 'node:test';
import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';
import {ENEMIES,EVENTS,CHAPTERS} from '../gameplay/data.js';
import {NEW_ENEMIES_BY_CHAPTER} from '../gameplay/content-rules.js';
const copy=structuredClone;
function arena(path=0,options={},emit=()=>{}){const b=new Expedition({balanceVersion:2,metaRulesVersion:2,path,difficulty:1,seed:'round8-tests',...options},emit);b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.player.invuln=0;b.updateDirector=b.updateEnvironment=b.updateSwords=b.updateAllies=()=>{};return b;}
function enemy(b,index){const e=b.spawn(index,{x:900,y:520,spawn:0,hp:1000});e.timer=0;b.rebuildHash();return e;}
function tick(b,n){for(let i=0;i<n;i++)b.update(.05);}
void test('four new enemies join only new content, while missing-marker saves retain the old roster',()=>{assert.equal(ENEMIES.length,28);const b=arena();for(let chapter=0;chapter<6;chapter++){b.chapter=chapter;assert.deepEqual(b.enemyPool(),[...CHAPTERS[chapter].enemies,...NEW_ENEMIES_BY_CHAPTER[chapter]]);}const old=arena(0,{contentVersion:1}),d=copy(old.serialize());delete d.options.contentVersion;const r=Expedition.restore(d);assert.equal(r.options.contentVersion,1);assert.deepEqual(r.enemyPool(),CHAPTERS[0].enemies);assert.equal(r.options.balanceVersion,2);});
void test('fanbow telegraphs and releases three separate rays; windup survives a snapshot',()=>{const b=arena();const e=enemy(b,24);b.updateEnemy(e,.05);assert.equal(b.shots.length,0);assert.equal(e.charge,.8);tick(b,7);const r=Expedition.restore(copy(b.serialize()));r.updateDirector=r.updateEnvironment=r.updateSwords=r.updateAllies=()=>{};tick(b,11);tick(r,11);assert.equal(b.shots.length,3);assert.equal(r.shots.length,3);assert.deepEqual(r.shots.map(s=>[s.vx,s.vy]),b.shots.map(s=>[s.vx,s.vy]));assert.equal(new Set(b.shots.map(s=>s.vy)).size,3);});
void test('frost silk warns before slowing and deals no direct area damage',()=>{const b=arena(),e=enemy(b,25);b.updateEnemy(e,.05);assert.equal(b.zones[0].kind,'frost');assert.equal(b.zones[0].warn,1.1);assert.equal(b.zones[0].damage,0);b.updateEnemy=()=>{};tick(b,12);assert.equal(b.player.webSlow||0,0);tick(b,12);assert.equal(b.player.webSlow,.4);assert.equal(b.player.hp,100);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.zones[0].kind,'frost');});
void test('bulwark reduces front sword hits only while raised; sides and lowered guard remain vulnerable',()=>{const b=arena(),e=enemy(b,26);e.a=0;e.timer=4;b.player.x=e.x+100;let hp=e.hp;b.hit(e,100,'sword',false);assert.equal(hp-e.hp,60);b.player.x=e.x-100;hp=e.hp;b.hit(e,100,'sword',false);assert.equal(hp-e.hp,100);e.timer=1;b.player.x=e.x+100;hp=e.hp;b.hit(e,100,'sword',false);assert.equal(hp-e.hp,100);b.player.x=e.x-100;b.updateEnemy(e,.05);assert.ok(Math.abs(e.a)<=.04501);});
void test('orbit fire actually moves sideways and fires a slow hostile bolt after its warning',()=>{const b=arena(),e=enemy(b,27),y=e.y;b.updateEnemy(e,.05);assert.notEqual(e.y,y);assert.equal(b.shots.length,0);tick(b,14);assert.equal(b.shots.length,1);assert.ok(Math.abs(Math.hypot(b.shots[0].vx,b.shots[0].vy)-115)<1e-8);assert.equal(b.shots[0].friendly,false);});
void test('boss defeat presentation is emitted once without duplicating node rewards',()=>{const events=[],b=arena(0,{},e=>events.push(e));b.wave=3;b.beginNode();const boss=b.boss;events.length=0;b.kill(boss);const xp=b.totalXP,gold=b.gold;assert.equal(events.filter(e=>e.type==='boss-defeat').length,1);assert.ok(events.findIndex(e=>e.type==='boss-defeat')<events.findIndex(e=>e.type==='scene'));assert.equal(b.modeState,'rest');b.kill(boss);assert.equal(b.totalXP,xp);assert.equal(b.gold,gold);assert.equal(events.filter(e=>e.type==='boss-defeat').length,1);assert.equal(b.receipts.filter(id=>id==='0:3').length,1);const r=Expedition.restore(copy(b.serialize()));assert.equal(r.receipts.filter(id=>id==='0:3').length,1);});
void test('Xuan Gu defeat effect waits for the complete canonical fire countdown',()=>{const events=[],b=arena(0,{},e=>events.push(e));b.chapter=5;b.wave=3;b.beginNode();const boss=b.boss;boss.phase=2;boss.hp=1;boss.phaseShield=0;events.length=0;b.hit(boss,999,'sword',false);assert.equal(b.bossEnding,13);assert.equal(events.filter(e=>e.type==='boss-defeat').length,0);for(let i=0;i<259;i++)b.updateBossEnding(boss,.05);assert.equal(events.filter(e=>e.type==='boss-defeat').length,0);b.updateBossEnding(boss,.051);assert.equal(events.filter(e=>e.type==='boss-defeat').length,1);});
void test('invalidated paid drafts block departure and retain resources until a new valid selection',()=>{const b=arena();b.completeNode();b.rest.event={type:'single',index:EVENTS.findIndex(e=>e.choices.some(c=>c.effect==='buyHeal')),choice:null};const choices=EVENTS[b.rest.event.index].choices,i=choices.findIndex(c=>c.effect==='buyHeal');b.gold=30;b.player.hp=60;b.chooseInteraction(i);b.gold=20;const before=JSON.stringify(b.serialize());assert.equal(b.restReadiness().event,false);assert.match(b.restReadiness().eventReason,/还缺 5/);b.continueRest();assert.equal(JSON.stringify(b.serialize()),before);assert.match(b.toastText,/暂选机缘已失效/);});
void test('same-path core preview preserves the equipped core and records an explicit replacement target',()=>{const b=arena();b.completeNode();b.relics=['K01'];b.recalc();b.rest.coreOffers=['K02'];b.rest.coreApplied=false;assert.equal(b.selectCore('K02'),true);assert.deepEqual(b.relics,['K01']);assert.deepEqual(b.rest.coreSelection,{id:'K02',replaceId:'K01'});const r=Expedition.restore(copy(b.serialize()));assert.deepEqual(r.relics,['K01']);assert.deepEqual(r.rest.coreSelection,b.rest.coreSelection);});
void test('guard supply correction changes only new content; both item effects remain distinct',()=>{for(const [contentVersion,id] of [[1,'guard'],[2,'shield']]){const b=arena(5,{contentVersion}),counts={};for(let i=0;i<20;i++){b.rng=()=> (i+.5)/20;b.makeShop();const c=b.shop.at(-1);counts[c.id]=(counts[c.id]||0)+1;}assert.equal(counts[id],3);assert.equal(counts[id==='guard'?'shield':'guard'],1);}});
void test('blocked counter feedback is once per independent dodge and never replaces its successful counter',()=>{const b=arena(5);b.dash();b.hitPlayer(10);for(let i=0;i<8;i++)b.hitPlayer(10);assert.equal(b.combatCues.filter(c=>c.key==='counter-wait').length,0);b.time=2.1;b.player.dashCD=0;b.dash();for(let i=0;i<8;i++)b.hitPlayer(10);assert.equal(b.combatCues.filter(c=>c.key==='counter-wait').length,1);assert.equal(b.lastCounter,0);});
void test('equal defense configurations receive equal direct damage across all six starters',()=>{for(let path=0;path<6;path++){const b=arena(path);b.stats={};b.player.shield=0;b.player.hp=100;b.hitPlayer(18);assert.equal(b.player.hp,82);}});
void test('unknown content markers and new enemies in an old-content snapshot are rejected',()=>{const b=arena();enemy(b,24);for(const contentVersion of [0,4,1]){const d=copy(b.serialize());d.options.contentVersion=contentVersion;assert.throws(()=>Expedition.restore(d),/内容规则|内容版本/);}});
