/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';import {META,initialSave,CONSUMABLES} from '../gameplay/data.js';
import {applySlow,tickSlow} from '../gameplay/slow.js';import {normalizeSave,readableSaveError,SaveVault,SAVE_KEY,BACKUP_KEY,JOURNAL_KEY} from '../gameplay/save-store.js';import {starterDetails} from '../gameplay/starters.js';
const own=path=>META.filter(m=>m.path===path).map(m=>m.id),copy=v=>JSON.parse(JSON.stringify(v));
function arena(path=4){const b=new Expedition({seed:'round2-fixes',path,meta:own(path),balanceVersion:3});b.cinematicSeen=['bamboo'];b.beginNode();b.clearField();b.updateDirector=()=>{};b.updateEnvironment=()=>{};return b;}
void test('weak sword hits preserve a binding consumable and its original expiration',()=>{const b=arena(),e=b.spawn(0,{hp:1e6,spawn:0,speed:0});b.consumables=[{id:CONSUMABLES.find(c=>c.effect==='slow').id,count:1}];b.consume(0);tickSlow(e,5.5);b.hit(e,1,'sword',false);assert.equal(e.slow,.65);assert.equal(e.slowTime,.5);tickSlow(e,.6);assert.equal(e.slow,.04);assert.ok(Math.abs(e.slowTime-.6)<1e-8);});
void test('weak long effects cannot inherit the strength of a short effect',()=>{const e={slow:0,slowTime:0};applySlow(e,'binding',.65,.5);applySlow(e,'sword',.1,6);tickSlow(e,.6);assert.equal(e.slow,.1);assert.equal(e.slowTime,5.4);tickSlow(e,5.5);assert.equal(e.slow,0);assert.equal(e.slows.length,0);});
void test('ward, puppet and ember refreshes do not extend binding or erase each other',()=>{const e={slow:0,slowTime:0};applySlow(e,'binding',.65,1);for(let i=0;i<12;i++){applySlow(e,'ward',.5,.4);applySlow(e,'puppet',.2,1.5);applySlow(e,'ember',.3,.4);tickSlow(e,.1);}assert.equal(e.slow,.5);tickSlow(e,.5);assert.equal(e.slow,.2);assert.ok(e.slowTime<1);});
void test('legacy scalar slow survives migration, and the new source timers survive a save roundtrip',()=>{const b=arena(),e=b.spawn(0,{hp:1e6,slow:.65,slowTime:3});applySlow(e,'sword',.04,1.2);tickSlow(e,1);const restored=Expedition.restore(copy(b.serialize())),enemy=restored.enemies[0];assert.equal(enemy.slow,.65);assert.deepEqual(enemy.slows,e.slows);tickSlow(enemy,2.1);assert.equal(enemy.slow,0);});
void test('bosses and fixed rune mechanisms remain immune to slows',()=>{for(const e of [{boss:true},{mission:'rune'}]){Object.assign(e,{slow:.65,slowTime:2});applySlow(e,'sword',.04,1.2);tickSlow(e,.01);assert.equal(e.slow,0);assert.deepEqual(e.slows,[]);}});
void test('binding, ward and allied projectile writes use independent live combat sources',()=>{const b=arena(2),e=b.spawn(0,{x:640,y:400,hp:1e6,spawn:0,speed:0});b.stats.puppetSlow=.2;b.updateAllies=()=>{};b.updateSwords=()=>{};applySlow(e,'binding',.65,6);b.shoot(e.x,e.y,0,1,0,true);b.zones=[{x:e.x,y:e.y,r:80,damage:0,ttl:4,warn:0,friendly:true,kind:'ward'}];b.update(.01);assert.equal(e.slow,.65);assert.deepEqual(new Set(e.slows.map(s=>s.source)),new Set(['binding','puppet','ward']));});
void test('invalid puppet counters and still-time are rejected without modifying input',()=>{for(const key of ['metaShots','coreShots','stillTime'])for(const value of ['abc',-1,.5,Infinity]){if(key==='stillTime'&&value===.5)continue;const b=arena(2);b.updateAllies(.01);const d=copy(b.serialize());if(key==='stillTime')d.expedition.stillTime=value;else d.expedition.puppets[0][key]=value;const raw=JSON.stringify(d);assert.throws(()=>normalizeSave({...initialSave(),checkpoint:d}),/计时|计数/);assert.equal(JSON.stringify(d),raw);}});
void test('missing optional counters in older snapshots remain readable and initialize normally',()=>{const b=arena(2);b.updateAllies(.01);const d=copy(b.serialize());delete d.expedition.stillTime;d.expedition.puppets.forEach(a=>{delete a.metaShots;delete a.coreShots;});const r=Expedition.restore(d);assert.equal(r.stillTime,0);r.spawn(0,{x:820,y:400,hp:1e6,spawn:0,speed:0});r.rebuildHash();r.puppets.forEach(a=>a.cool=0);r.updateAllies(.01);assert.ok(r.puppets.every(a=>a.metaShots===1));});
void test('malformed slow sources, duplicated sources and invalid focus counters are rejected',()=>{for(const mutate of [e=>e.slows=[{source:'unknown',strength:.2,left:1}],e=>e.slows=[{source:'sword',strength:.2,left:1},{source:'sword',strength:.2,left:2}],e=>e.slows=[{source:'sword',strength:.9,left:1}],e=>e.slows=[{source:'sword',strength:.2,left:'abc'}],e=>e.focusHits='4']){const b=arena();b.spawn(0,{hp:1e6});const d=copy(b.serialize());mutate(d.expedition.enemies[0]);assert.throws(()=>Expedition.restore(d),/减速|聚锋/);}});
void test('switching formation without a cooling sword leaves recall available',()=>{const b=arena(0);b.swords.forEach(s=>s.cool=.2);b.changeFormation();assert.equal(b.player.metaSwitchAt,undefined);b.swords[0].cool=1;b.time=1;b.changeFormation();assert.equal(b.player.metaSwitchAt,1);assert.equal(b.swords[0].cool,.25);b.swords[0].cool=1;b.time=2;b.changeFormation();assert.equal(b.swords[0].cool,1);});
void test('starter text uses only the selected cultivation branch and distinguishes adjacent-hit windows',()=>{const options={metaRulesVersion:2,meta:META.map(m=>m.id),balanceVersion:3};assert.match(starterDetails(1,options).initial,/65/);assert.match(starterDetails(1,{...options,meta:own(0)}).initial,/50/);assert.match(starterDetails(0,options).action,/相邻间隔不超过 2.6 秒/);assert.match(starterDetails(3,options).initial,/5 只/);assert.match(starterDetails(4,options).action,/5.4 秒/);assert.match(starterDetails(5,options).initial,/33 护盾/);});
void test('restoring an expedition marks it as restored without changing its scene or position',()=>{for(const b of [new Expedition({seed:'intro'}),arena(0)]){const d=copy(b.serialize()),r=Expedition.restore(d);assert.equal(r.restored,true);assert.equal(r.scene,d.scene);assert.equal(r.modeState,d.modeState);assert.equal(r.player.x,d.player.x);}});
void test('interrupted backup protection reports waiting, then restores the old backup safely',()=>{const raw=JSON.stringify(initialSave()),before=JSON.stringify({raw,savedAt:1}),map=new Map([[SAVE_KEY,raw],[BACKUP_KEY,'after']]),st={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},j={key:BACKUP_KEY,before,after:'after',primaryAfter:'pending',owner:'previous-page',createdAt:Date.now()};st.setItem(JOURNAL_KEY,JSON.stringify(j));const v=new SaveVault(st),s=v.load();assert.throws(()=>v.commit(s),e=>e.code==='busy'&&/页面刚刷新/.test(e.message));assert.equal(st.getItem(SAVE_KEY),raw);j.createdAt-=5001;st.setItem(JOURNAL_KEY,JSON.stringify(j));v.commit(s);assert.equal(st.getItem(BACKUP_KEY),before);assert.equal(st.getItem(JOURNAL_KEY),null);});
void test('import feedback retains useful Chinese validation causes without exposing parser text',()=>{assert.equal(readableSaveError(Error('傀儡压制计数无效，原记录未被修改')),'傀儡压制计数无效');assert.match(readableSaveError(new SyntaxError('Unexpected token private contents')),/JSON 格式/);assert.equal(readableSaveError(Error('secret details')),'存档内容无法识别');});
