/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';import assert from 'node:assert/strict';import {Expedition} from '../gameplay/expedition.js';import {xpCost,CHAPTERS,EVENTS,initialSave} from '../gameplay/data.js';import {EXPEDITIONS,CINEMATICS} from '../gameplay/expedition-data.js';import {EVENT_STORIES,eligibleEvents,chapterEventText,storyCatalogMatches} from '../gameplay/story-rules.js';import {CHAPTER_NAMES,legacyChapterAchievement} from '../gameplay/chapter-names.js';import {normalizeSave} from '../gameplay/save-store.js';
const copy=structuredClone,close=(a,b)=>assert.ok(Math.abs(a-b)<.051,`${a} != ${b}`);
function run(options={}){const b=new Expedition({seed:'phase4-tests',difficulty:1,...options});b.cinematicSeen=CINEMATICS.map(c=>c.id);b.node.selected=0;b.beginNode();return b;}
function tick(b,seconds){for(let t=0;t<seconds-1e-8;t+=.05)b.update(.05);}
function bad(d,mutate,re){const x=copy(d);mutate(x);const raw=JSON.stringify(x);assert.throws(()=>Expedition.restore(x),re);assert.equal(JSON.stringify(x),raw);}
void test('M18 growth3 reallocates exactly 900 late XP and preserves 11960 base XP, 22 nodes and legacy schedules',()=>{const current=new Expedition({growthVersion:3}),old=new Expedition({growthVersion:2});assert.deepEqual(current.routes[4].map(n=>n.xp),[680,760,1160,1500]);assert.deepEqual(current.routes[5].map(n=>n.xp),[1200,700,1000,300]);assert.deepEqual(old.routes.map(ch=>ch.map(n=>n.xp)),EXPEDITIONS.map(ch=>ch.xp));for(const b of [current,old]){assert.equal(b.routes.flat().length,22);assert.equal(b.routes.flat().reduce((n,r)=>n+r.xp,0),11960);assert.equal(b.routes.flat().slice(0,-1).reduce((n,r)=>n+r.xp,0),11660);}});
void test('M18 revised late-node reward and its restoration use the saved XP version without paying twice',()=>{for(const growthVersion of [1,2,3]){const b=new Expedition({growthVersion,chapter:4,storyVersion:1});b.wave=2;b.node.selected=0;b.beginNode();b.completeNode();const xp=b.totalXP,r=Expedition.restore(copy(b.serialize()));assert.equal(r.options.growthVersion,growthVersion);assert.equal(r.node.xp,growthVersion===3?1160:860);r.completeNode();assert.equal(r.totalXP,xp);assert.equal(r.receipts.length,1);if(growthVersion===3)bad(b.serialize(),d=>d.options.growthVersion=2,/经验/);}});
void test('M18 crossing 72, including a multi-level jump, emits one cosmetic moment without changing RNG, scene or in-flight swords',()=>{const events=[],b=run();b.emit=e=>events.push(e);b.level=71;b.swords=[];b.syncSwords();const first=b.swords[0];first.cool=.7;first.life=.8;first.hits=[900];const rng=b.rng.state(),scene=b.scene,state=b.modeState;b.addXP(xpCost(71)+xpCost(72)+1);assert.equal(b.level,73);assert.equal(b.swords.length,72);assert.equal(b.swords[0],first);assert.equal(first.cool,.7);assert.deepEqual(first.hits,[900]);assert.equal(b.rng.state(),rng);assert.equal(b.scene,scene);assert.equal(b.modeState,state);assert.equal(events.filter(e=>e.type==='formation-ready').length,1);b.addXP(1);assert.equal(events.filter(e=>e.type==='formation-ready').length,1);});
for(const version of [2,3])void test('M18 treasure timing '+version+' requires all three occupied positions and survives midway restore',()=>{let b=run({chapter:3,encounterVersion:version});b.updateEnvironment=()=>{};const duration=version===3?30:42,start=b.time;assert.equal(b.mechanism.goal,duration);b.player.x=80;b.player.y=700;tick(b,3);assert.equal(b.mechanism.progress,0);b.player.x=b.mechanism.x;b.player.y=b.mechanism.y;tick(b,duration/3+.05);assert.equal(b.mechanism.step,1);const progress=b.mechanism.progress;tick(b,2);assert.equal(b.mechanism.progress,progress);b=Expedition.restore(copy(b.serialize()));assert.equal(b.mechanism.goal,duration);assert.equal(b.mechanism.step,1);for(let n=0;n<1000&&b.modeState==='battle';n++){b.player.x=b.mechanism.x;b.player.y=b.mechanism.y;b.update(.05);}assert.equal(b.receipts.includes('3:0'),true);assert.ok(b.storyInventory.includes('five-rings')&&b.storyInventory.includes('cape'));assert.equal(b.enemies.length,0);assert.ok(b.time-start>=duration+5);const xp=b.totalXP;b.completeNode();assert.equal(b.totalXP,xp);});
void test('M18 new illusion opens first at seven seconds; false gate visibly returns player without rewards, then correct gates finish once',()=>{let b=new Expedition({chapter:3});b.wave=1;b.beginNode();assert.equal(b.objective.next,7);const q=b.objective;b.player.x=q.gates[q.trueGate].x;b.player.y=q.gates[q.trueGate].y;tick(b,6.9);assert.equal(q.done,0);b.player.x=q.gates[(q.trueGate+1)%3].x;b.player.y=q.gates[(q.trueGate+1)%3].y;tick(b,.15);assert.equal(q.done,0);assert.equal(b.player.y,560);assert.equal(b.receipts.length,0);assert.ok(b.combatCues.some(c=>c.key==='illusion-false'));tick(b,2);b.player.x=q.gates[q.trueGate].x;b.player.y=q.gates[q.trueGate].y;b.update(.05);assert.equal(q.done,1);assert.equal(q.next,17);b=Expedition.restore(copy(b.serialize()));assert.equal(b.objective.done,1);for(let n=0;n<700&&b.modeState==='battle';n++){const q=b.objective;b.player.x=q.gates[q.trueGate].x;b.player.y=q.gates[q.trueGate].y;b.update(.05);}assert.equal(b.receipts.includes('3:1'),true);assert.equal(b.enemies.length,0);close(b.waveTime,27);});
void test('M18 corrupted new pacing is rejected before overwriting; explicit old and missing versions retain their own timers',()=>{const b=run({chapter:3});bad(b.serialize(),d=>d.expedition.mechanism.goal=42,/节奏/);bad(b.serialize(),d=>d.expedition.mechanism.step=1,/节奏/);const c=new Expedition({chapter:3});c.wave=1;c.beginNode();bad(c.serialize(),d=>d.expedition.objective.next=10,/节奏/);bad(c.serialize(),d=>d.expedition.objective.next='7',/计时|节奏/);const old=run({chapter:3,encounterVersion:1,storyVersion:1,growthVersion:1}),d=copy(old.serialize());for(const k of ['encounterVersion','growthVersion','storyVersion'])delete d.options[k];const r=Expedition.restore(d);assert.equal(r.mechanism.goal,42);assert.equal(r.options.storyVersion,1);for(const [k,v] of [['growthVersion',6],['encounterVersion',99],['storyVersion',4]])bad(b.serialize(),d=>d.options[k]=v,/版本/);});
for(const [chapter,id] of [[1,'ghostFog'],[4,'innerHall']])void test('M19 new chapter '+chapter+' cinematic resumes and skips without rewards or rerolling its battle',()=>{const make=()=>new Expedition({seed:'chapter-story',runId:'story-fixed',chapter});const a=make(),b=make(),gold=a.gold,stats=a.rng.state();a.start();b.start();assert.equal(a.cinematic.id,id);assert.equal(a.gold,gold);assert.equal(a.rng.state(),stats);a.advanceCinematic();const restored=Expedition.restore(copy(a.serialize()));assert.equal(restored.cinematic.panel,1);a.advanceCinematic();a.advanceCinematic();b.advanceCinematic(true);assert.equal(a.modeState,'battle');assert.equal(b.modeState,'battle');assert.deepEqual(a.enemies,b.enemies);assert.equal(a.rng.state(),b.rng.state());assert.equal(a.gold,gold);assert.equal(a.receipts.length,0);assert.ok(a.cinematicSeen.includes(id));const before=JSON.stringify(a.serialize());a.advanceCinematic(true);assert.equal(JSON.stringify(a.serialize()),before);const old=new Expedition({chapter,storyVersion:1});old.start();assert.equal(old.cinematic,null);assert.equal(old.modeState,'battle');});
void test('M19 every old cinematic retains three addressable panels; eight scenes separate actions and notes from character speech',()=>{assert.equal(CINEMATICS.length,8);for(const c of CINEMATICS){assert.equal(c.panels.length,3);assert.ok(c.note);for(const p of c.panels){assert.equal(p.length,4);assert.ok(p[3]);assert.doesNotMatch(p[2],/随机起手|商店|游戏规则|不会提前开放|雷源|\d+\s*秒/);}}for(const id of ['bamboo','ruins','yuanyao','treasure','cauldron','ending']){const b=run({storyVersion:1});b.playCinematic(id,'rest',true);b.cinematic.panel=2;assert.equal(Expedition.restore(copy(b.serialize())).cinematic.panel,2);}});
void test('M19 all 24 event stories are chapter scoped, with unchanged reward choices, and old story1 retains all events',()=>{assert.equal(storyCatalogMatches(),true);assert.equal(EVENT_STORIES.length,24);for(let chapter=0;chapter<6;chapter++){const b=new Expedition({chapter}),allowed=eligibleEvents(b).map(e=>e.id);assert.ok(allowed.length>=8);b.chains=[];const ids=new Set();for(let n=0;n<800;n++){const e=b.makeEvent();assert.equal(e.type,'single');assert.ok(allowed.includes(e.index));ids.add(e.index);const text=chapterEventText(b,e.index);assert.ok(text.name&&text.desc);assert.equal(EVENTS[e.index].choices.length,3);}assert.equal(ids.size,allowed.length);const old=new Expedition({chapter,storyVersion:1});old.chains=[];const seen=new Set(Array.from({length:800},()=>old.makeEvent().index));assert.equal(seen.size,24);}const b=new Expedition({path:0});assert.equal(b.stats.insects||0,0);assert.ok(eligibleEvents(b).some(e=>e.name==='微弱虫鸣'));assert.doesNotMatch(chapterEventText(b,10).desc,/储物袋中躁动/);});
void test('M19 selected contextual event survives restore and repeated reads without reroll or rewards',()=>{const b=run({chapter:4});b.chains=[];b.completeNode();const e=copy(b.rest.event),before=JSON.stringify(b.serialize());assert.ok(eligibleEvents(b).some(x=>x.id===e.index));const text=b.eventText();assert.match(text.desc,/内殿石门/);assert.equal(JSON.stringify(b.serialize()),before);const r=Expedition.restore(copy(b.serialize()));assert.deepEqual(r.rest.event,e);assert.deepEqual(r.eventText(),text);const invalid=EVENT_STORIES.find(e=>!e.chapters.includes(4));bad(b.serialize(),d=>d.expedition.rest.event.index=invalid.id,/章节/);});
void test('M19 chapter display names share one source and the old chapter-four achievement keeps an alias',()=>{assert.deepEqual(CHAPTERS.map(c=>c.name),CHAPTER_NAMES);assert.deepEqual(EXPEDITIONS.map(c=>c.name),CHAPTER_NAMES);assert.equal(legacyChapterAchievement(3),'历经·宝光禁制');assert.equal(new Expedition({chapter:3}).chapterInfo.name,'宝光与幻境');});
void test('M18-M19 legacy encounter3 ice still requires forty seconds; ordinary empty-field gaps do not complete nodes',()=>{const b=new Expedition({chapter:5,encounterVersion:3});b.wave=2;b.beginNode();b.player.x=b.objective.exit.x;b.player.y=b.objective.exit.y;tick(b,39.9);assert.equal(b.receipts.length,0);tick(b,.2);assert.equal(b.receipts.includes('5:2'),true);const ordinary=run();ordinary.clearField();ordinary.updateDirector(0);assert.equal(ordinary.receipts.length,0);});
void test('M19 Xuangu must endure the entire backlash; skipping absent cinematics cannot kill him or pay twice',()=>{const b=new Expedition({chapter:5});b.wave=3;b.beginNode();b.boss.phase=2;b.boss.phaseShield=0;b.player.shield=100000;b.hit(b.boss,1e9,'thunder',false);assert.equal(b.bossEnding,13);b.advanceCinematic(true);assert.equal(b.receipts.length,0);tick(b,12.9);assert.equal(b.receipts.length,0);tick(b,.2);assert.equal(b.receipts.includes('5:3'),true);assert.equal(b.finished,false);b.queuedChoices=0;b.chooseInteraction(2);b.continueRest();assert.equal(b.cinematic.id,'ending');b.advanceCinematic(true);assert.equal(b.won,true);const raw=JSON.stringify(b.summary());b.advanceCinematic(true);assert.equal(JSON.stringify(b.summary()),raw);});
void test('M18/M19 independent old/new growth, pacing and story combinations survive normal saves',()=>{for(const growthVersion of [1,2,3])for(const encounterVersion of [1,2,3])for(const storyVersion of [1,2]){const b=run({chapter:3,growthVersion,encounterVersion,storyVersion});const s=normalizeSave({...initialSave(),checkpoint:b.serialize()});const r=Expedition.restore(s.checkpoint);assert.equal(r.options.growthVersion,growthVersion);assert.equal(r.options.encounterVersion,encounterVersion);assert.equal(r.options.storyVersion,storyVersion);assert.equal(r.mechanism.goal,encounterVersion===3?30:42);}});

void test('M18/M19 an omitted launch seed restores from the saved seed instead of wall-clock route regeneration',()=>{const b=new Expedition({chapter:4});b.seed='saved-fallback-seed';const seeded=new Expedition({...b.options,seed:b.seed});b.routes=seeded.routes;b.chains=seeded.chains;b.contentRng=seeded.contentRng;b.wave=2;b.node.selected=0;b.beginNode();const d=copy(b.serialize());delete d.options.seed;const r=Expedition.restore(d);assert.equal(r.seed,d.seed);assert.deepEqual(r.routes,b.routes);assert.equal(r.encounter.kind,b.encounter.kind);});

void test('M19 all 48 event reward choices keep identical transaction results under old and new story rules',()=>{for(let index=0;index<EVENTS.length;index++)for(const choice of [0,1]){const outcomes=[];for(const storyVersion of [1,2]){const b=run({storyVersion,seed:'event-reward-parity'});b.completeNode();b.rest.event={type:'single',index,choice:null};b.rest.eventDone=false;b.gold=1000;b.player.hp=50;b.player.mana=20;b.consumables=[{id:'heal',count:0},{id:'mana',count:0}];const selected=b.chooseInteraction(choice),committed=selected?b.commitRestSelections():false;outcomes.push({selected,committed,gold:b.gold,rerolls:b.rerolls,consumables:b.consumables,hp:b.player.hp,shield:b.player.shield,mana:b.player.mana});}assert.deepEqual(outcomes[0],outcomes[1],EVENTS[index].name+'/'+choice);}});
