/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {Battle} from '../gameplay/engine.js';
import {TRAITS,RELICS,ENEMIES,CONSUMABLES,COMBOS,META,xpCost} from '../gameplay/data.js';
void test('content catalog has unique ids and all modifiers are numeric',()=>{for(const [array,n]of [[TRAITS,72],[RELICS,36],[ENEMIES,28],[CONSUMABLES,18],[META,36]]){assert.equal(array.length,n);assert.equal(new Set(array.map(x=>x.id)).size,n);}assert.equal(COMBOS.length,12);for(const x of [...TRAITS,...RELICS])for(const v of Object.values(x.mods))assert.ok(Number.isFinite(v));});
void test('multi-level experience grants exactly 72 real swords and caps sword count',()=>{const b=new Battle({seed:'xp'});let total=0;for(let l=1;l<72;l++)total+=xpCost(l);assert.equal(total,10971);b.addXP(total);assert.equal(b.level,72);assert.equal(b.swords.length,72);assert.equal(b.queuedChoices,18);b.addXP(5000);assert.ok(b.level>72);assert.equal(b.swords.length,72);});
void test('paused time never restores mana or advances difficulty',()=>{const b=new Battle({seed:'pause'});b.start();b.update(.05);b.pause();const t=b.time,m=b.player.mana;for(let i=0;i<1000;i++)b.update(.05);assert.equal(b.time,t);assert.equal(b.player.mana,m);});
void test('divine lightning consumes mana and finite reserve; mana consumable does not replenish reserve',()=>{const b=new Battle({seed:'thunder'});b.start();b.player.mana=100;const reserve=b.player.reserve;b.spawn(0,{x:600,y:400,hp:100});assert.equal(b.thunder(),true);assert.equal(b.player.mana,0);assert.equal(b.player.reserve,reserve-25);b.consume(1);assert.equal(b.player.reserve,reserve-25);b.player.mana=100;b.player.reserve=0;assert.equal(b.thunder(),false);assert.equal(b.player.mana,100);});
void test('contact invulnerability prevents same-frame overlap deaths',()=>{const b=new Battle({seed:'hit'});b.start();b.hitPlayer(10);const hp=b.player.hp;for(let i=0;i<100;i++)b.hitPlayer(10);assert.equal(b.player.hp,hp);});
void test('chapter-gated treasures never enter early shop',()=>{const b=new Battle({seed:'shop'});for(let i=0;i<30;i++){b.makeShop();assert.ok(b.shop.every(x=>!x.story));}b.chapter=4;b.grantStoryItems();assert.ok(b.storyInventory.includes('cape'));});
void test('safe checkpoint roundtrip preserves build, level and resources',()=>{const b=new Battle({seed:'save'});b.addXP(1500);b.traits['sword-0']=2;b.recalc();b.player.hp=56;b.player.reserve=45;b.gold=311;b.wave=2;const c=Battle.restore(b.serialize(),()=>{});assert.equal(c.level,b.level);assert.equal(c.swords.length,b.swords.length);assert.equal(c.player.hp,56);assert.equal(c.player.reserve,45);assert.equal(c.gold,311);assert.equal(c.traits['sword-0'],2);assert.throws(()=>Battle.restore({version:1,level:999,chapter:0},()=>{}));});
void test('Xuan Gu cannot be erased by lethal raw damage; survival window completes canon event',()=>{const b=new Battle({seed:'boss'});b.start();b.chapter=5;b.wave=3;b.spawnBoss();const e=b.boss;e.spawn=0;b.player.invuln=100;for(let phase=0;phase<2;phase++){b.hit(e,1e9,'thunder',false);assert.ok(e.hp>1);assert.ok(e.phaseShield>0);for(let i=0;i<180;i++)b.update(1/60);}b.hit(e,1e9,'thunder',false);assert.equal(e.hp,1);assert.ok(b.bossEnding>0);assert.equal(b.modeState,'battle');b.player.invuln=100;for(let i=0;i<800;i++)b.update(1/60);assert.equal(b.modeState,'chapterEnd');assert.equal(b.boss,null);});
void test('summoned enemies grant no experience',()=>{const b=new Battle({seed:'summon'}),e=b.spawn(0,{noDrop:true});b.kill(e);assert.equal(b.drops.length,0);});
void test('all six permanent health nodes add at most twelve health',()=>{const b=new Battle({meta:META.filter(m=>m.step===2).map(m=>m.id)});assert.equal(b.player.maxHp,112);assert.equal(b.player.hp,112);});
void test('boss projectiles remain hostile',()=>{const b=new Battle({seed:'serpent'});b.start();b.wave=3;b.spawnBoss();b.boss.spawn=0;b.boss.timer=0;b.update(.01);assert.ok(b.shots.length>0);assert.ok(b.shots.every(x=>x.friendly===false));});

void test('weeping soul is unavailable before completing the lava route',()=>{const b=new Battle({chapter:2});assert.ok(!b.storyInventory.includes('weeping'));b.chapter=3;b.grantStoryItems();assert.ok(b.storyInventory.includes('weeping'));});
void test('a full consumable bag can replace a selected slot without losing both slots',()=>{const b=new Battle();b.modeState='rest';b.gold=500;b.shop=[{...CONSUMABLES[2],kind:'consumable',price:30}];assert.equal(b.buy(0),'slots');assert.equal(b.gold,500);assert.equal(b.buy(0,1),true);assert.equal(b.consumables[1].id,'shield');assert.equal(b.consumables[0].id,'heal');});
void test('Treasure Light Pavilion requires occupying the objective, not damage',()=>{const b=new Battle({chapter:3});b.start();b.wave=3;b.spawnBoss();assert.equal(b.boss.type,'seal');b.player.invuln=100;for(let i=0;i<600;i++)b.update(1/60);assert.equal(b.mechanism.progress,0);for(let i=0;i<3000&&b.modeState==='battle';i++){b.player.x=b.mechanism.x;b.player.y=b.mechanism.y;b.update(1/60);}assert.equal(b.modeState,'chapterEnd');});
void test('same seed and fixed input replay identical combat outcomes',()=>{const a=new Battle({seed:'repeat'}),b=new Battle({seed:'repeat'});a.start();b.start();for(let i=0;i<600;i++){a.input.x=.3;b.input.x=.3;a.update(1/60);b.update(1/60);}assert.deepEqual(a.summary(),b.summary());assert.equal(a.rng.state(),b.rng.state());});

void test('temporary shields above base capacity survive regeneration and an unshielded thunder cast',()=>{const b=new Battle();b.start();b.player.shield=45;b.player.mana=100;b.thunder();for(let i=0;i<120;i++)b.update(1/60);assert.equal(b.player.maxShield,0);assert.equal(b.player.shield,45);});
