/* SPDX-License-Identifier: GPL-3.0-only
 * Copyright (C) 2026 bilibili@卡布奇诺ultra
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import {Expedition} from '../gameplay/expedition.js';
import {initialSave} from '../gameplay/data.js';
import {SaveVault,SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY} from '../gameplay/save-store.js';
import {beginPracticeStep} from '../gameplay/practice.js';
import {mechanismProfile} from '../gameplay/director-rules.js';
import {recordGroup} from '../gameplay/records.js';
function vaultFixture(){const primary=JSON.stringify({...initialSave(),insight:73}),backup=JSON.stringify({raw:JSON.stringify({...initialSave(),insight:37})}),map=new Map([[SAVE_KEY,primary],[BACKUP_KEY,backup]]);let fail=true;const storage={getItem:k=>map.get(k)??null,setItem(k,v){if(k===SAVE_KEY&&fail)throw Error('quota');map.set(k,v);},removeItem:k=>map.delete(k)},vault=new SaveVault(storage);vault.load();const options={expectedSnapshot:vault.snapshot(),sourceRaw:JSON.stringify({...initialSave(),insight:123})},next=JSON.parse(options.sourceRaw);return {map,vault,options,next,primary,backup,allow:()=>{fail=false;}};}
void test('R1 own protection retries, old slots preserved and no duplicate raw records',()=>{const f=vaultFixture();for(let n=0;n<3;n++){assert.throws(()=>f.vault.adoptRecovery(f.next,f.options),e=>e.code==='storage');assert.equal(f.map.get(SAVE_KEY),f.primary);assert.equal(f.map.get(BACKUP_KEY),f.backup);assert.equal(f.vault.rawRecords().length,2);}f.allow();assert.equal(f.vault.adoptRecovery(f.next,f.options).insight,123);assert.equal(f.vault.rawRecords().length,2);assert.ok(f.vault.rawRecords().some(r=>r.raw.includes('37')));});
for(const key of [SAVE_KEY,BACKUP_KEY,JOURNAL_KEY,RAW_BACKUP_KEY])void test('R1 concurrent '+key+' blocks stale retry without writes',()=>{const f=vaultFixture();assert.throws(()=>f.vault.adoptRecovery(f.next,f.options));f.allow();f.map.set(key,'external');const before=[...f.map];assert.throws(()=>f.vault.adoptRecovery(f.next,f.options),e=>e.code==='conflict');assert.deepEqual([...f.map],before);});
function gate(version=7,correct=true,path=0){const b=new Expedition({seed:'step1-gate',chapter:3,path,difficulty:1,encounterVersion:version,recordVersion:0});b.wave=1;b.node.selected=0;b.beginNode();b.clearField();b.waveTime=7;b.time+=7;b.player.invuln=0;b.player.shield=0;const g=b.objective.gates[correct?b.objective.trueGate:(b.objective.trueGate+1)%3];b.player.x=g.x;b.player.y=g.y;return {b,x:correct?640:g.x,y:560};}
function threat(b,x,y,kind){if(kind==='melee'){const e=b.spawn(4,{x,y,hp:100000,speed:0});e.x=x;e.y=y;e.spawn=0;}else if(kind==='shot')b.shoot(x,y,0,10,0);else b.danger(x,y,50,10,0,3);}
for(const correct of [true,false])for(const kind of ['melee','shot','zone'])void test(`R2 ${correct?'true':'false'} gate ${kind}, new7 and old5/6`,()=>{for(const version of [5,6,7]){const {b,x,y}=gate(version,correct),hp=b.player.hp;threat(b,x,y,kind);b.update(1/60);assert.equal(b.objective.done,correct?1:0);assert.equal(b.objective.cool,correct?0:2);assert.equal(b.objective.next,correct?17:7);assert.equal(b.player.hp<hp,version!==7);if(version===7){const until=b.objective.returnProtectedUntil,restored=Expedition.restore(b.serialize());assert.equal(restored.objective.returnProtectedUntil,until);restored.pause();assert.equal(restored.modeState,'pause');restored.update(.05);assert.equal(restored.time,b.time);b.time=until;b.player.invuln=0;b.hitPlayer(10,kind==='zone');assert.ok(b.player.hp<hp);}}});
void test('R2 false gate cannot extend protection during two second cooldown',()=>{const {b}=gate(7,false);b.update(1/60);const until=b.objective.returnProtectedUntil;for(let i=0;i<10;i++){b.player.x=b.objective.gates[(b.objective.trueGate+1)%3].x;b.player.y=250;b.update(.05);assert.equal(b.objective.returnProtectedUntil,until);}assert.ok(b.time>until);});
void test('R2 return does not pay guard counter; actual manual dodge still pays exactly once',()=>{const {b}=gate(7,true,5);b.player.dashCD=0;b.dash();b.update(1/60);const shield=b.player.shield,counter=b.lastCounter;b.hitPlayer(10);assert.equal(b.player.shield,shield);assert.equal(b.lastCounter,counter);b.time=b.objective.returnProtectedUntil+.01;b.player.invuln=0;b.player.dashCD=0;b.dash();b.hitPlayer(10);assert.equal(b.player.shield,shield+3);b.hitPlayer(10);assert.equal(b.player.shield,shield+3);});
void test('R2 new7 inherits route RNG and pressure6, preserves old restore and separates records',()=>{const a=gate(6).b,b=gate(7).b;assert.deepEqual(a.routes,b.routes);assert.equal(a.contentRng.state(),b.contentRng.state());assert.deepEqual(mechanismProfile(a),mechanismProfile(b));assert.equal(a.spawnBudget,b.spawnBudget);assert.equal(a.nextElite,b.nextElite);const legacy=new Expedition({encounterVersion:1}).serialize();delete legacy.options.encounterVersion;assert.equal(Expedition.restore(legacy).options.encounterVersion,1);assert.equal(Expedition.restore(a.serialize()).options.encounterVersion,6);for(const value of [undefined,NaN,b.time+1]){const bad=b.serialize();bad.expedition.objective.returnProtectedUntil=value;assert.throws(()=>Expedition.restore(bad),/节奏/);}const base={mode:'story',difficulty:1,path:0,touchLockUsed:false};assert.notEqual(recordGroup({...base,rules:{encounterVersion:6}}),recordGroup({...base,rules:{encounterVersion:7}}));});
void test('R3 practice clears active dash and movement while formal pause keeps active dash',()=>{const b=new Expedition({mode:'training',guidedPractice:true});b.start();beginPracticeStep(b,1);b.input.x=1;b.dash();assert.ok(b.player.dash>0);beginPracticeStep(b,2);assert.equal(b.player.dash,0);assert.equal(b.input.x,0);b.update(.05);assert.equal(b.player.x,640);assert.equal(b.player.y,520);const f=new Expedition();f.beginNode();f.dash();const dash=f.player.dash;f.pause();assert.equal(f.player.dash,dash);});
